var gfcommands = {

// ALABAMA
autaugaal: ['Autauga, Alabama', 'https://greaterfinds.blogspot.com/search/label/autauga+al'],
baldwinal: ['Baldwin, Alabama', 'https://greaterfinds.blogspot.com/search/label/baldwin+al'],
barboural: ['Barbour, Alabama', 'https://greaterfinds.blogspot.com/search/label/barbour+al'],
bibbal: ['Bibb, Alabama', 'https://greaterfinds.blogspot.com/search/label/bibb+al'],
blountal: ['Blount, Alabama', 'https://greaterfinds.blogspot.com/search/label/blount+al'],
bullockal: ['Bullock, Alabama', 'https://greaterfinds.blogspot.com/search/label/bullock+al'],
butleral: ['Butler, Alabama', 'https://greaterfinds.blogspot.com/search/label/butler+al'],
calhounal: ['Calhoun, Alabama', 'https://greaterfinds.blogspot.com/search/label/calhoun+al'],
chambersal: ['Chambers, Alabama', 'https://greaterfinds.blogspot.com/search/label/chambers+al'],
cherokeeal: ['Cherokee, Alabama', 'https://greaterfinds.blogspot.com/search/label/cherokee+al'],
chiltonal: ['Chilton, Alabama', 'https://greaterfinds.blogspot.com/search/label/chilton+al'],
choctawal: ['Choctaw, Alabama', 'https://greaterfinds.blogspot.com/search/label/choctaw+al'],
clarkeal: ['Clarke, Alabama', 'https://greaterfinds.blogspot.com/search/label/clarke+al'],
clayal: ['Clay, Alabama', 'https://greaterfinds.blogspot.com/search/label/clay+al'],
cleburneal: ['Cleburne, Alabama', 'https://greaterfinds.blogspot.com/search/label/cleburne+al'],
coffeeal: ['Coffee, Alabama', 'https://greaterfinds.blogspot.com/search/label/coffee+al'],
colbertal: ['Colbert, Alabama', 'https://greaterfinds.blogspot.com/search/label/colbert+al'],
conecuhal: ['Conecuh, Alabama', 'https://greaterfinds.blogspot.com/search/label/conecuh+al'],
coosaal: ['Coosa, Alabama', 'https://greaterfinds.blogspot.com/search/label/coosa+al'],
covingtonal: ['Covington, Alabama', 'https://greaterfinds.blogspot.com/search/label/covington+al'],
crenshawal: ['Crenshaw, Alabama', 'https://greaterfinds.blogspot.com/search/label/crenshaw+al'],
cullmanal: ['Cullman, Alabama', 'https://greaterfinds.blogspot.com/search/label/cullman+al'],
daleal: ['Dale, Alabama', 'https://greaterfinds.blogspot.com/search/label/dale+al'],
dallasal: ['Dallas, Alabama', 'https://greaterfinds.blogspot.com/search/label/dallas+al'],
dekalbal: ['DeKalb, Alabama', 'https://greaterfinds.blogspot.com/search/label/dekalb+al'],
elmoreal: ['Elmore, Alabama', 'https://greaterfinds.blogspot.com/search/label/elmore+al'],
escambiaal: ['Escambia, Alabama', 'https://greaterfinds.blogspot.com/search/label/escambia+al'],
etowahal: ['Etowah, Alabama', 'https://greaterfinds.blogspot.com/search/label/etowah+al'],
fayetteal: ['Fayette, Alabama', 'https://greaterfinds.blogspot.com/search/label/fayette+al'],
franklinal: ['Franklin, Alabama', 'https://greaterfinds.blogspot.com/search/label/franklin+al'],
genevaal: ['Geneva, Alabama', 'https://greaterfinds.blogspot.com/search/label/geneva+al'],
greeneal: ['Greene, Alabama', 'https://greaterfinds.blogspot.com/search/label/greene+al'],
haleal: ['Hale, Alabama', 'https://greaterfinds.blogspot.com/search/label/hale+al'],
henryal: ['Henry, Alabama', 'https://greaterfinds.blogspot.com/search/label/henry+al'],
houstonal: ['Houston, Alabama', 'https://greaterfinds.blogspot.com/search/label/houston+al'],
jacksonal: ['Jackson, Alabama', 'https://greaterfinds.blogspot.com/search/label/jackson+al'],
jeffersonal: ['Jefferson, Alabama', 'https://greaterfinds.blogspot.com/search/label/jefferson+al'],
lamaral: ['Lamar, Alabama', 'https://greaterfinds.blogspot.com/search/label/lamar+al'],
lauderdaleal: ['Lauderdale, Alabama', 'https://greaterfinds.blogspot.com/search/label/lauderdale+al'],
lawrenceal: ['Lawrence, Alabama', 'https://greaterfinds.blogspot.com/search/label/lawrence+al'],
leeal: ['Lee, Alabama', 'https://greaterfinds.blogspot.com/search/label/lee+al'],
limestoneal: ['Limestone, Alabama', 'https://greaterfinds.blogspot.com/search/label/limestone+al'],
lowndesal: ['Lowndes, Alabama', 'https://greaterfinds.blogspot.com/search/label/lowndes+al'],
maconal: ['Macon, Alabama', 'https://greaterfinds.blogspot.com/search/label/macon+al'],
madisonal: ['Madison, Alabama', 'https://greaterfinds.blogspot.com/search/label/madison+al'],
marengoal: ['Marengo, Alabama', 'https://greaterfinds.blogspot.com/search/label/marengo+al'],
marional: ['Marion, Alabama', 'https://greaterfinds.blogspot.com/search/label/marion+al'],
marshallal: ['Marshall, Alabama', 'https://greaterfinds.blogspot.com/search/label/marshall+al'],
mobileal: ['Mobile, Alabama', 'https://greaterfinds.blogspot.com/search/label/mobile+al'],
monroeal: ['Monroe, Alabama', 'https://greaterfinds.blogspot.com/search/label/monroe+al'],
montgomeryal: ['Montgomery, Alabama', 'https://greaterfinds.blogspot.com/search/label/montgomery+al'],
morganal: ['Morgan, Alabama', 'https://greaterfinds.blogspot.com/search/label/morgan+al'],
perryal: ['Perry, Alabama', 'https://greaterfinds.blogspot.com/search/label/perry+al'],
pickensal: ['Pickens, Alabama', 'https://greaterfinds.blogspot.com/search/label/pickens+al'],
pikeal: ['Pike, Alabama', 'https://greaterfinds.blogspot.com/search/label/pike+al'],
randolphal: ['Randolph, Alabama', 'https://greaterfinds.blogspot.com/search/label/randolph+al'],
russellal: ['Russell, Alabama', 'https://greaterfinds.blogspot.com/search/label/russell+al'],
shelbyal: ['Shelby, Alabama', 'https://greaterfinds.blogspot.com/search/label/shelby+al'],
stclairal: ['St. Clair, Alabama', 'https://greaterfinds.blogspot.com/search/label/stclair+al'],
sumteral: ['Sumter, Alabama', 'https://greaterfinds.blogspot.com/search/label/sumter+al'],
talladegaal: ['Talladega, Alabama', 'https://greaterfinds.blogspot.com/search/label/talladega+al'],
tallapoosaal: ['Tallapoosa, Alabama', 'https://greaterfinds.blogspot.com/search/label/tallapoosa+al'],
tuscaloosaal: ['Tuscaloosa, Alabama', 'https://greaterfinds.blogspot.com/search/label/tuscaloosa+al'],
walkeral: ['Walker, Alabama', 'https://greaterfinds.blogspot.com/search/label/walker+al'],
washingtonal: ['Washington , Alabama', 'https://greaterfinds.blogspot.com/search/label/washington+al'],
wilcoxal: ['Wilcox, Alabama', 'https://greaterfinds.blogspot.com/search/label/wilcox+al'],
winstonal: ['Winston, Alabama', 'https://greaterfinds.blogspot.com/search/label/winston+al'],

// ALASKA
aleutianseastak: ['Aleutians East, Alaska', 'https://greaterfinds.blogspot.com/search/label/aleutianseast+ak'],
aleutianswestak: ['Aleutians West , Alaska', 'https://greaterfinds.blogspot.com/search/label/aleutianswest+ak'],
anchorageak: ['Anchorage, Alaska', 'https://greaterfinds.blogspot.com/search/label/anchorage+ak'],
bethelak: ['Bethel , Alaska', 'https://greaterfinds.blogspot.com/search/label/bethel+ak'],
bristolbayak: ['Bristol Bay, Alaska', 'https://greaterfinds.blogspot.com/search/label/bristolbay+ak'],
denaliak: ['Denali, Alaska', 'https://greaterfinds.blogspot.com/search/label/denali+ak'],
dillinghamak: ['Dillingham , Alaska', 'https://greaterfinds.blogspot.com/search/label/dillingham+ak'],
fairbanksnorthstarak: ['Fairbanks North Star, Alaska', 'https://greaterfinds.blogspot.com/search/label/fairbanksnorthstar+ak'],
hainesak: ['Haines, Alaska', 'https://greaterfinds.blogspot.com/search/label/haines+ak'],
hoonahangoonak: ['Hoonah-Angoon , Alaska', 'https://greaterfinds.blogspot.com/search/label/hoonahangoon+ak'],
juneauak: ['Juneau, Alaska', 'https://greaterfinds.blogspot.com/search/label/juneau+ak'],
kenaipeninsulaak: ['Kenai Peninsula, Alaska', 'https://greaterfinds.blogspot.com/search/label/kenaipeninsula+ak'],
ketchikangatewayak: ['Ketchikan Gateway, Alaska', 'https://greaterfinds.blogspot.com/search/label/ketchikangateway+ak'],
kodiakislandak: ['Kodiak Island, Alaska', 'https://greaterfinds.blogspot.com/search/label/kodiakisland+ak'],
kusilvakak: ['Kusilvak , Alaska', 'https://greaterfinds.blogspot.com/search/label/kusilvak+ak'],
lakeandpeninsulaak: ['Lake and Peninsula, Alaska', 'https://greaterfinds.blogspot.com/search/label/lakeandpeninsula+ak'],
matanuskasusitnaak: ['Matanuska-Susitna, Alaska', 'https://greaterfinds.blogspot.com/search/label/matanuskasusitna+ak'],
nomeak: ['Nome , Alaska', 'https://greaterfinds.blogspot.com/search/label/nome+ak'],
northslopeak: ['North Slope, Alaska', 'https://greaterfinds.blogspot.com/search/label/northslope+ak'],
northwestarcticak: ['Northwest Arctic, Alaska', 'https://greaterfinds.blogspot.com/search/label/northwestarctic+ak'],
petersburgak: ['Petersburg, Alaska', 'https://greaterfinds.blogspot.com/search/label/petersburg+ak'],
princeofwaleshyderak: ['Prince of Wales-Hyder, Alaska', 'https://greaterfinds.blogspot.com/search/label/princeofwaleshyder+ak'],
sitkaak: ['Sitka, Alaska', 'https://greaterfinds.blogspot.com/search/label/sitka+ak'],
skagwayak: ['Skagway, Alaska', 'https://greaterfinds.blogspot.com/search/label/skagway+ak'],
southeastfairbanksak: ['Southeast Fairbanks , Alaska', 'https://greaterfinds.blogspot.com/search/label/southeastfairbanks+ak'],
valdezcordovaak: ['Valdez-Cordova , Alaska', 'https://greaterfinds.blogspot.com/search/label/valdezcordova+ak'],
wrangellak: ['Wrangell, Alaska', 'https://greaterfinds.blogspot.com/search/label/wrangell+ak'],
yakutatak: ['Yakutat, Alaska', 'https://greaterfinds.blogspot.com/search/label/yakutat+ak'],
yukonkoyukukak: ['Yukon-Koyukuk , Alaska', 'https://greaterfinds.blogspot.com/search/label/yukonkoyukuk+ak'],

// ARIZONA

apacheaz: ['Apache, Arizona', 'https://greaterfinds.blogspot.com/search/label/apache+az'],
cochiseaz: ['Cochise, Arizona', 'https://greaterfinds.blogspot.com/search/label/cochise+az'],
coconinoaz: ['Coconino, Arizona', 'https://greaterfinds.blogspot.com/search/label/coconino+az'],
gilaaz: ['Gila, Arizona', 'https://greaterfinds.blogspot.com/search/label/gila+az'],
grahamaz: ['Graham, Arizona', 'https://greaterfinds.blogspot.com/search/label/graham+az'],
greenleeaz: ['Greenlee, Arizona', 'https://greaterfinds.blogspot.com/search/label/greenlee+az'],
lapazaz: ['La Paz, Arizona', 'https://greaterfinds.blogspot.com/search/label/lapaz+az'],
maricopaaz: ['Maricopa, Arizona', 'https://greaterfinds.blogspot.com/search/label/maricopa+az'],
mohaveaz: ['Mohave, Arizona', 'https://greaterfinds.blogspot.com/search/label/mohave+az'],
navajoaz: ['Navajo, Arizona', 'https://greaterfinds.blogspot.com/search/label/navajo+az'],
pimaaz: ['Pima, Arizona', 'https://greaterfinds.blogspot.com/search/label/pima+az'],
pinalaz: ['Pinal, Arizona', 'https://greaterfinds.blogspot.com/search/label/pinal+az'],
santacruzaz: ['Santa Cruz, Arizona', 'https://greaterfinds.blogspot.com/search/label/santacruz+az'],
yavapaiaz: ['Yavapai, Arizona', 'https://greaterfinds.blogspot.com/search/label/yavapai+az'],
yumaaz: ['Yuma, Arizona', 'https://greaterfinds.blogspot.com/search/label/yuma+az'],

// ARKANSAS


arkansasar: ['Arkansas , Arkansas', 'https://greaterfinds.blogspot.com/search/label/arkansas+ar'],
ashleyar: ['Ashley, Arkansas', 'https://greaterfinds.blogspot.com/search/label/ashley+ar'],
baxterar: ['Baxter, Arkansas', 'https://greaterfinds.blogspot.com/search/label/baxter+ar'],
bentonar: ['Benton, Arkansas', 'https://greaterfinds.blogspot.com/search/label/benton+ar'],
boonear: ['Boone, Arkansas', 'https://greaterfinds.blogspot.com/search/label/boone+ar'],
bradleyar: ['Bradley, Arkansas', 'https://greaterfinds.blogspot.com/search/label/bradley+ar'],
calhounar: ['Calhoun, Arkansas', 'https://greaterfinds.blogspot.com/search/label/calhoun+ar'],
carrollar: ['Carroll, Arkansas', 'https://greaterfinds.blogspot.com/search/label/carroll+ar'],
chicotar: ['Chicot, Arkansas', 'https://greaterfinds.blogspot.com/search/label/chicot+ar'],
clarkar: ['Clark, Arkansas', 'https://greaterfinds.blogspot.com/search/label/clark+ar'],
clayar: ['Clay, Arkansas', 'https://greaterfinds.blogspot.com/search/label/clay+ar'],
cleburnear: ['Cleburne, Arkansas', 'https://greaterfinds.blogspot.com/search/label/cleburne+ar'],
clevelandar: ['Cleveland, Arkansas', 'https://greaterfinds.blogspot.com/search/label/cleveland+ar'],
columbiaar: ['Columbia, Arkansas', 'https://greaterfinds.blogspot.com/search/label/columbia+ar'],
conwayar: ['Conway, Arkansas', 'https://greaterfinds.blogspot.com/search/label/conway+ar'],
craigheadar: ['Craighead, Arkansas', 'https://greaterfinds.blogspot.com/search/label/craighead+ar'],
crawfordar: ['Crawford, Arkansas', 'https://greaterfinds.blogspot.com/search/label/crawford+ar'],
crittendenar: ['Crittenden, Arkansas', 'https://greaterfinds.blogspot.com/search/label/crittenden+ar'],
crossar: ['Cross, Arkansas', 'https://greaterfinds.blogspot.com/search/label/cross+ar'],
dallasar: ['Dallas, Arkansas', 'https://greaterfinds.blogspot.com/search/label/dallas+ar'],
deshaar: ['Desha, Arkansas', 'https://greaterfinds.blogspot.com/search/label/desha+ar'],
drewar: ['Drew, Arkansas', 'https://greaterfinds.blogspot.com/search/label/drew+ar'],
faulknerar: ['Faulkner, Arkansas', 'https://greaterfinds.blogspot.com/search/label/faulkner+ar'],
franklinar: ['Franklin, Arkansas', 'https://greaterfinds.blogspot.com/search/label/franklin+ar'],
fultonar: ['Fulton, Arkansas', 'https://greaterfinds.blogspot.com/search/label/fulton+ar'],
garlandar: ['Garland, Arkansas', 'https://greaterfinds.blogspot.com/search/label/garland+ar'],
grantar: ['Grant, Arkansas', 'https://greaterfinds.blogspot.com/search/label/grant+ar'],
greenear: ['Greene, Arkansas', 'https://greaterfinds.blogspot.com/search/label/greene+ar'],
hempsteadar: ['Hempstead, Arkansas', 'https://greaterfinds.blogspot.com/search/label/hempstead+ar'],
hotspringar: ['Hot Spring, Arkansas', 'https://greaterfinds.blogspot.com/search/label/hotspring+ar'],
howardar: ['Howard, Arkansas', 'https://greaterfinds.blogspot.com/search/label/howard+ar'],
independencear: ['Independence, Arkansas', 'https://greaterfinds.blogspot.com/search/label/independence+ar'],
izardar: ['Izard, Arkansas', 'https://greaterfinds.blogspot.com/search/label/izard+ar'],
jacksonar: ['Jackson, Arkansas', 'https://greaterfinds.blogspot.com/search/label/jackson+ar'],
jeffersonar: ['Jefferson, Arkansas', 'https://greaterfinds.blogspot.com/search/label/jefferson+ar'],
johnsonar: ['Johnson, Arkansas', 'https://greaterfinds.blogspot.com/search/label/johnson+ar'],
lafayettear: ['Lafayette, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lafayette+ar'],
lawrencear: ['Lawrence, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lawrence+ar'],
leear: ['Lee, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lee+ar'],
lincolnar: ['Lincoln, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lincoln+ar'],
littleriverar: ['Little River, Arkansas', 'https://greaterfinds.blogspot.com/search/label/littleriver+ar'],
loganar: ['Logan, Arkansas', 'https://greaterfinds.blogspot.com/search/label/logan+ar'],
lonokear: ['Lonoke, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lonoke+ar'],
madisonar: ['Madison, Arkansas', 'https://greaterfinds.blogspot.com/search/label/madison+ar'],
marionar: ['Marion, Arkansas', 'https://greaterfinds.blogspot.com/search/label/marion+ar'],
millerar: ['Miller, Arkansas', 'https://greaterfinds.blogspot.com/search/label/miller+ar'],
mississippiar: ['Mississippi , Arkansas', 'https://greaterfinds.blogspot.com/search/label/mississippi+ar'],
monroear: ['Monroe, Arkansas', 'https://greaterfinds.blogspot.com/search/label/monroe+ar'],
montgomeryar: ['Montgomery, Arkansas', 'https://greaterfinds.blogspot.com/search/label/montgomery+ar'],
nevadaar: ['Nevada , Arkansas', 'https://greaterfinds.blogspot.com/search/label/nevada+ar'],
newtonar: ['Newton, Arkansas', 'https://greaterfinds.blogspot.com/search/label/newton+ar'],
ouachitaar: ['Ouachita, Arkansas', 'https://greaterfinds.blogspot.com/search/label/ouachita+ar'],
perryar: ['Perry, Arkansas', 'https://greaterfinds.blogspot.com/search/label/perry+ar'],
phillipsar: ['Phillips, Arkansas', 'https://greaterfinds.blogspot.com/search/label/phillips+ar'],
pikear: ['Pike, Arkansas', 'https://greaterfinds.blogspot.com/search/label/pike+ar'],
poinsettar: ['Poinsett, Arkansas', 'https://greaterfinds.blogspot.com/search/label/poinsett+ar'],
polkar: ['Polk, Arkansas', 'https://greaterfinds.blogspot.com/search/label/polk+ar'],
popear: ['Pope, Arkansas', 'https://greaterfinds.blogspot.com/search/label/pope+ar'],
prairiear: ['Prairie, Arkansas', 'https://greaterfinds.blogspot.com/search/label/prairie+ar'],
pulaskiar: ['Pulaski, Arkansas', 'https://greaterfinds.blogspot.com/search/label/pulaski+ar'],
randolphar: ['Randolph, Arkansas', 'https://greaterfinds.blogspot.com/search/label/randolph+ar'],
salinear: ['Saline, Arkansas', 'https://greaterfinds.blogspot.com/search/label/saline+ar'],
scottar: ['Scott, Arkansas', 'https://greaterfinds.blogspot.com/search/label/scott+ar'],
searcyar: ['Searcy, Arkansas', 'https://greaterfinds.blogspot.com/search/label/searcy+ar'],
sebastianar: ['Sebastian, Arkansas', 'https://greaterfinds.blogspot.com/search/label/sebastian+ar'],
sevierar: ['Sevier, Arkansas', 'https://greaterfinds.blogspot.com/search/label/sevier+ar'],
sharpar: ['Sharp, Arkansas', 'https://greaterfinds.blogspot.com/search/label/sharp+ar'],
stfrancisar: ['St. Francis, Arkansas', 'https://greaterfinds.blogspot.com/search/label/stfrancis+ar'],
stonear: ['Stone, Arkansas', 'https://greaterfinds.blogspot.com/search/label/stone+ar'],
unionar: ['Union, Arkansas', 'https://greaterfinds.blogspot.com/search/label/union+ar'],
vanburenar: ['Van Buren, Arkansas', 'https://greaterfinds.blogspot.com/search/label/vanburen+ar'],
washingtonar: ['Washington , Arkansas', 'https://greaterfinds.blogspot.com/search/label/washington+ar'],
whitear: ['White, Arkansas', 'https://greaterfinds.blogspot.com/search/label/white+ar'],
woodruffar: ['Woodruff, Arkansas', 'https://greaterfinds.blogspot.com/search/label/woodruff+ar'],
yellar: ['Yell, Arkansas', 'https://greaterfinds.blogspot.com/search/label/yell+ar'],
}