var shortcuts = {

// ALABAMA
autaugaal: ['Autauga, Alabama', 'https://greaterfinds.blogspot.com/search/label/autauga+al'],
baldwinal: ['Baldwin, Alabama', 'https://greaterfinds.blogspot.com/search/label/baldwin+al'],
barboural: ['Barbour, Alabama', 'https://greaterfinds.blogspot.com/search/label/barbour+al'],
bibbal: ['Bibb, Alabama', 'https://greaterfinds.blogspot.com/search/label/bibb+al'],
blountal: ['Blount, Alabama', 'https://greaterfinds.blogspot.com/search/label/blount+al'],
bullockal: ['Bullock, Alabama', 'https://greaterfinds.blogspot.com/search/label/bullock+al'],
butleral: ['Butler, Alabama', 'https://greaterfinds.blogspot.com/search/label/butler+al'],
calhounal: ['Calhoun, Alabama', 'https://greaterfinds.blogspot.com/search/label/calhoun+al'],
chambersal: ['Chambers, Alabama', 'https://greaterfinds.blogspot.com/search/label/chambers+al'],
cherokeeal: ['Cherokee, Alabama', 'https://greaterfinds.blogspot.com/search/label/cherokee+al'],
chiltonal: ['Chilton, Alabama', 'https://greaterfinds.blogspot.com/search/label/chilton+al'],
choctawal: ['Choctaw, Alabama', 'https://greaterfinds.blogspot.com/search/label/choctaw+al'],
clarkeal: ['Clarke, Alabama', 'https://greaterfinds.blogspot.com/search/label/clarke+al'],
clayal: ['Clay, Alabama', 'https://greaterfinds.blogspot.com/search/label/clay+al'],
cleburneal: ['Cleburne, Alabama', 'https://greaterfinds.blogspot.com/search/label/cleburne+al'],
coffeeal: ['Coffee, Alabama', 'https://greaterfinds.blogspot.com/search/label/coffee+al'],
colbertal: ['Colbert, Alabama', 'https://greaterfinds.blogspot.com/search/label/colbert+al'],
conecuhal: ['Conecuh, Alabama', 'https://greaterfinds.blogspot.com/search/label/conecuh+al'],
coosaal: ['Coosa, Alabama', 'https://greaterfinds.blogspot.com/search/label/coosa+al'],
covingtonal: ['Covington, Alabama', 'https://greaterfinds.blogspot.com/search/label/covington+al'],
crenshawal: ['Crenshaw, Alabama', 'https://greaterfinds.blogspot.com/search/label/crenshaw+al'],
cullmanal: ['Cullman, Alabama', 'https://greaterfinds.blogspot.com/search/label/cullman+al'],
daleal: ['Dale, Alabama', 'https://greaterfinds.blogspot.com/search/label/dale+al'],
dallasal: ['Dallas, Alabama', 'https://greaterfinds.blogspot.com/search/label/dallas+al'],
dekalbal: ['DeKalb, Alabama', 'https://greaterfinds.blogspot.com/search/label/dekalb+al'],
elmoreal: ['Elmore, Alabama', 'https://greaterfinds.blogspot.com/search/label/elmore+al'],
escambiaal: ['Escambia, Alabama', 'https://greaterfinds.blogspot.com/search/label/escambia+al'],
etowahal: ['Etowah, Alabama', 'https://greaterfinds.blogspot.com/search/label/etowah+al'],
fayetteal: ['Fayette, Alabama', 'https://greaterfinds.blogspot.com/search/label/fayette+al'],
franklinal: ['Franklin, Alabama', 'https://greaterfinds.blogspot.com/search/label/franklin+al'],
genevaal: ['Geneva, Alabama', 'https://greaterfinds.blogspot.com/search/label/geneva+al'],
greeneal: ['Greene, Alabama', 'https://greaterfinds.blogspot.com/search/label/greene+al'],
haleal: ['Hale, Alabama', 'https://greaterfinds.blogspot.com/search/label/hale+al'],
henryal: ['Henry, Alabama', 'https://greaterfinds.blogspot.com/search/label/henry+al'],
houstonal: ['Houston, Alabama', 'https://greaterfinds.blogspot.com/search/label/houston+al'],
jacksonal: ['Jackson, Alabama', 'https://greaterfinds.blogspot.com/search/label/jackson+al'],
jeffersonal: ['Jefferson, Alabama', 'https://greaterfinds.blogspot.com/search/label/jefferson+al'],
lamaral: ['Lamar, Alabama', 'https://greaterfinds.blogspot.com/search/label/lamar+al'],
lauderdaleal: ['Lauderdale, Alabama', 'https://greaterfinds.blogspot.com/search/label/lauderdale+al'],
lawrenceal: ['Lawrence, Alabama', 'https://greaterfinds.blogspot.com/search/label/lawrence+al'],
leeal: ['Lee, Alabama', 'https://greaterfinds.blogspot.com/search/label/lee+al'],
limestoneal: ['Limestone, Alabama', 'https://greaterfinds.blogspot.com/search/label/limestone+al'],
lowndesal: ['Lowndes, Alabama', 'https://greaterfinds.blogspot.com/search/label/lowndes+al'],
maconal: ['Macon, Alabama', 'https://greaterfinds.blogspot.com/search/label/macon+al'],
madisonal: ['Madison, Alabama', 'https://greaterfinds.blogspot.com/search/label/madison+al'],
marengoal: ['Marengo, Alabama', 'https://greaterfinds.blogspot.com/search/label/marengo+al'],
marional: ['Marion, Alabama', 'https://greaterfinds.blogspot.com/search/label/marion+al'],
marshallal: ['Marshall, Alabama', 'https://greaterfinds.blogspot.com/search/label/marshall+al'],
mobileal: ['Mobile, Alabama', 'https://greaterfinds.blogspot.com/search/label/mobile+al'],
monroeal: ['Monroe, Alabama', 'https://greaterfinds.blogspot.com/search/label/monroe+al'],
montgomeryal: ['Montgomery, Alabama', 'https://greaterfinds.blogspot.com/search/label/montgomery+al'],
morganal: ['Morgan, Alabama', 'https://greaterfinds.blogspot.com/search/label/morgan+al'],
perryal: ['Perry, Alabama', 'https://greaterfinds.blogspot.com/search/label/perry+al'],
pickensal: ['Pickens, Alabama', 'https://greaterfinds.blogspot.com/search/label/pickens+al'],
pikeal: ['Pike, Alabama', 'https://greaterfinds.blogspot.com/search/label/pike+al'],
randolphal: ['Randolph, Alabama', 'https://greaterfinds.blogspot.com/search/label/randolph+al'],
russellal: ['Russell, Alabama', 'https://greaterfinds.blogspot.com/search/label/russell+al'],
shelbyal: ['Shelby, Alabama', 'https://greaterfinds.blogspot.com/search/label/shelby+al'],
stclairal: ['St. Clair, Alabama', 'https://greaterfinds.blogspot.com/search/label/stclair+al'],
sumteral: ['Sumter, Alabama', 'https://greaterfinds.blogspot.com/search/label/sumter+al'],
talladegaal: ['Talladega, Alabama', 'https://greaterfinds.blogspot.com/search/label/talladega+al'],
tallapoosaal: ['Tallapoosa, Alabama', 'https://greaterfinds.blogspot.com/search/label/tallapoosa+al'],
tuscaloosaal: ['Tuscaloosa, Alabama', 'https://greaterfinds.blogspot.com/search/label/tuscaloosa+al'],
walkeral: ['Walker, Alabama', 'https://greaterfinds.blogspot.com/search/label/walker+al'],
washingtonal: ['Washington, Alabama', 'https://greaterfinds.blogspot.com/search/label/washington+al'],
wilcoxal: ['Wilcox, Alabama', 'https://greaterfinds.blogspot.com/search/label/wilcox+al'],
winstonal: ['Winston, Alabama', 'https://greaterfinds.blogspot.com/search/label/winston+al'],

// ALASKA
aleutianseastak: ['Aleutians East, Alaska', 'https://greaterfinds.blogspot.com/search/label/aleutianseast+ak'],
aleutianswestak: ['Aleutians West , Alaska', 'https://greaterfinds.blogspot.com/search/label/aleutianswest+ak'],
anchorageak: ['Anchorage, Alaska', 'https://greaterfinds.blogspot.com/search/label/anchorage+ak'],
bethelak: ['Bethel , Alaska', 'https://greaterfinds.blogspot.com/search/label/bethel+ak'],
bristolbayak: ['Bristol Bay, Alaska', 'https://greaterfinds.blogspot.com/search/label/bristolbay+ak'],
denaliak: ['Denali, Alaska', 'https://greaterfinds.blogspot.com/search/label/denali+ak'],
dillinghamak: ['Dillingham , Alaska', 'https://greaterfinds.blogspot.com/search/label/dillingham+ak'],
fairbanksnorthstarak: ['Fairbanks North Star, Alaska', 'https://greaterfinds.blogspot.com/search/label/fairbanksnorthstar+ak'],
hainesak: ['Haines, Alaska', 'https://greaterfinds.blogspot.com/search/label/haines+ak'],
hoonahangoonak: ['Hoonah-Angoon , Alaska', 'https://greaterfinds.blogspot.com/search/label/hoonahangoon+ak'],
juneauak: ['Juneau, Alaska', 'https://greaterfinds.blogspot.com/search/label/juneau+ak'],
kenaipeninsulaak: ['Kenai Peninsula, Alaska', 'https://greaterfinds.blogspot.com/search/label/kenaipeninsula+ak'],
ketchikangatewayak: ['Ketchikan Gateway, Alaska', 'https://greaterfinds.blogspot.com/search/label/ketchikangateway+ak'],
kodiakislandak: ['Kodiak Island, Alaska', 'https://greaterfinds.blogspot.com/search/label/kodiakisland+ak'],
kusilvakak: ['Kusilvak , Alaska', 'https://greaterfinds.blogspot.com/search/label/kusilvak+ak'],
lakeandpeninsulaak: ['Lake and Peninsula, Alaska', 'https://greaterfinds.blogspot.com/search/label/lakeandpeninsula+ak'],
matanuskasusitnaak: ['Matanuska-Susitna, Alaska', 'https://greaterfinds.blogspot.com/search/label/matanuskasusitna+ak'],
nomeak: ['Nome , Alaska', 'https://greaterfinds.blogspot.com/search/label/nome+ak'],
northslopeak: ['North Slope, Alaska', 'https://greaterfinds.blogspot.com/search/label/northslope+ak'],
northwestarcticak: ['Northwest Arctic, Alaska', 'https://greaterfinds.blogspot.com/search/label/northwestarctic+ak'],
petersburgak: ['Petersburg, Alaska', 'https://greaterfinds.blogspot.com/search/label/petersburg+ak'],
princeofwaleshyderak: ['Prince of Wales-Hyder, Alaska', 'https://greaterfinds.blogspot.com/search/label/princeofwaleshyder+ak'],
sitkaak: ['Sitka, Alaska', 'https://greaterfinds.blogspot.com/search/label/sitka+ak'],
skagwayak: ['Skagway, Alaska', 'https://greaterfinds.blogspot.com/search/label/skagway+ak'],
southeastfairbanksak: ['Southeast Fairbanks , Alaska', 'https://greaterfinds.blogspot.com/search/label/southeastfairbanks+ak'],
valdezcordovaak: ['Valdez-Cordova , Alaska', 'https://greaterfinds.blogspot.com/search/label/valdezcordova+ak'],
wrangellak: ['Wrangell, Alaska', 'https://greaterfinds.blogspot.com/search/label/wrangell+ak'],
yakutatak: ['Yakutat, Alaska', 'https://greaterfinds.blogspot.com/search/label/yakutat+ak'],
yukonkoyukukak: ['Yukon-Koyukuk , Alaska', 'https://greaterfinds.blogspot.com/search/label/yukonkoyukuk+ak'],

// ARIZONA

apacheaz: ['Apache, Arizona', 'https://greaterfinds.blogspot.com/search/label/apache+az'],
cochiseaz: ['Cochise, Arizona', 'https://greaterfinds.blogspot.com/search/label/cochise+az'],
coconinoaz: ['Coconino, Arizona', 'https://greaterfinds.blogspot.com/search/label/coconino+az'],
gilaaz: ['Gila, Arizona', 'https://greaterfinds.blogspot.com/search/label/gila+az'],
grahamaz: ['Graham, Arizona', 'https://greaterfinds.blogspot.com/search/label/graham+az'],
greenleeaz: ['Greenlee, Arizona', 'https://greaterfinds.blogspot.com/search/label/greenlee+az'],
lapazaz: ['La Paz, Arizona', 'https://greaterfinds.blogspot.com/search/label/lapaz+az'],
maricopaaz: ['Maricopa, Arizona', 'https://greaterfinds.blogspot.com/search/label/maricopa+az'],
mohaveaz: ['Mohave, Arizona', 'https://greaterfinds.blogspot.com/search/label/mohave+az'],
navajoaz: ['Navajo, Arizona', 'https://greaterfinds.blogspot.com/search/label/navajo+az'],
pimaaz: ['Pima, Arizona', 'https://greaterfinds.blogspot.com/search/label/pima+az'],
pinalaz: ['Pinal, Arizona', 'https://greaterfinds.blogspot.com/search/label/pinal+az'],
santacruzaz: ['Santa Cruz, Arizona', 'https://greaterfinds.blogspot.com/search/label/santacruz+az'],
yavapaiaz: ['Yavapai, Arizona', 'https://greaterfinds.blogspot.com/search/label/yavapai+az'],
yumaaz: ['Yuma, Arizona', 'https://greaterfinds.blogspot.com/search/label/yuma+az'],

// ARKANSAS


arkansasar: ['Arkansas , Arkansas', 'https://greaterfinds.blogspot.com/search/label/arkansas+ar'],
ashleyar: ['Ashley, Arkansas', 'https://greaterfinds.blogspot.com/search/label/ashley+ar'],
baxterar: ['Baxter, Arkansas', 'https://greaterfinds.blogspot.com/search/label/baxter+ar'],
bentonar: ['Benton, Arkansas', 'https://greaterfinds.blogspot.com/search/label/benton+ar'],
boonear: ['Boone, Arkansas', 'https://greaterfinds.blogspot.com/search/label/boone+ar'],
bradleyar: ['Bradley, Arkansas', 'https://greaterfinds.blogspot.com/search/label/bradley+ar'],
calhounar: ['Calhoun, Arkansas', 'https://greaterfinds.blogspot.com/search/label/calhoun+ar'],
carrollar: ['Carroll, Arkansas', 'https://greaterfinds.blogspot.com/search/label/carroll+ar'],
chicotar: ['Chicot, Arkansas', 'https://greaterfinds.blogspot.com/search/label/chicot+ar'],
clarkar: ['Clark, Arkansas', 'https://greaterfinds.blogspot.com/search/label/clark+ar'],
clayar: ['Clay, Arkansas', 'https://greaterfinds.blogspot.com/search/label/clay+ar'],
cleburnear: ['Cleburne, Arkansas', 'https://greaterfinds.blogspot.com/search/label/cleburne+ar'],
clevelandar: ['Cleveland, Arkansas', 'https://greaterfinds.blogspot.com/search/label/cleveland+ar'],
columbiaar: ['Columbia, Arkansas', 'https://greaterfinds.blogspot.com/search/label/columbia+ar'],
conwayar: ['Conway, Arkansas', 'https://greaterfinds.blogspot.com/search/label/conway+ar'],
craigheadar: ['Craighead, Arkansas', 'https://greaterfinds.blogspot.com/search/label/craighead+ar'],
crawfordar: ['Crawford, Arkansas', 'https://greaterfinds.blogspot.com/search/label/crawford+ar'],
crittendenar: ['Crittenden, Arkansas', 'https://greaterfinds.blogspot.com/search/label/crittenden+ar'],
crossar: ['Cross, Arkansas', 'https://greaterfinds.blogspot.com/search/label/cross+ar'],
dallasar: ['Dallas, Arkansas', 'https://greaterfinds.blogspot.com/search/label/dallas+ar'],
deshaar: ['Desha, Arkansas', 'https://greaterfinds.blogspot.com/search/label/desha+ar'],
drewar: ['Drew, Arkansas', 'https://greaterfinds.blogspot.com/search/label/drew+ar'],
faulknerar: ['Faulkner, Arkansas', 'https://greaterfinds.blogspot.com/search/label/faulkner+ar'],
franklinar: ['Franklin, Arkansas', 'https://greaterfinds.blogspot.com/search/label/franklin+ar'],
fultonar: ['Fulton, Arkansas', 'https://greaterfinds.blogspot.com/search/label/fulton+ar'],
garlandar: ['Garland, Arkansas', 'https://greaterfinds.blogspot.com/search/label/garland+ar'],
grantar: ['Grant, Arkansas', 'https://greaterfinds.blogspot.com/search/label/grant+ar'],
greenear: ['Greene, Arkansas', 'https://greaterfinds.blogspot.com/search/label/greene+ar'],
hempsteadar: ['Hempstead, Arkansas', 'https://greaterfinds.blogspot.com/search/label/hempstead+ar'],
hotspringar: ['Hot Spring, Arkansas', 'https://greaterfinds.blogspot.com/search/label/hotspring+ar'],
howardar: ['Howard, Arkansas', 'https://greaterfinds.blogspot.com/search/label/howard+ar'],
independencear: ['Independence, Arkansas', 'https://greaterfinds.blogspot.com/search/label/independence+ar'],
izardar: ['Izard, Arkansas', 'https://greaterfinds.blogspot.com/search/label/izard+ar'],
jacksonar: ['Jackson, Arkansas', 'https://greaterfinds.blogspot.com/search/label/jackson+ar'],
jeffersonar: ['Jefferson, Arkansas', 'https://greaterfinds.blogspot.com/search/label/jefferson+ar'],
johnsonar: ['Johnson, Arkansas', 'https://greaterfinds.blogspot.com/search/label/johnson+ar'],
lafayettear: ['Lafayette, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lafayette+ar'],
lawrencear: ['Lawrence, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lawrence+ar'],
leear: ['Lee, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lee+ar'],
lincolnar: ['Lincoln, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lincoln+ar'],
littleriverar: ['Little River, Arkansas', 'https://greaterfinds.blogspot.com/search/label/littleriver+ar'],
loganar: ['Logan, Arkansas', 'https://greaterfinds.blogspot.com/search/label/logan+ar'],
lonokear: ['Lonoke, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lonoke+ar'],
madisonar: ['Madison, Arkansas', 'https://greaterfinds.blogspot.com/search/label/madison+ar'],
marionar: ['Marion, Arkansas', 'https://greaterfinds.blogspot.com/search/label/marion+ar'],
millerar: ['Miller, Arkansas', 'https://greaterfinds.blogspot.com/search/label/miller+ar'],
mississippiar: ['Mississippi , Arkansas', 'https://greaterfinds.blogspot.com/search/label/mississippi+ar'],
monroear: ['Monroe, Arkansas', 'https://greaterfinds.blogspot.com/search/label/monroe+ar'],
montgomeryar: ['Montgomery, Arkansas', 'https://greaterfinds.blogspot.com/search/label/montgomery+ar'],
nevadaar: ['Nevada , Arkansas', 'https://greaterfinds.blogspot.com/search/label/nevada+ar'],
newtonar: ['Newton, Arkansas', 'https://greaterfinds.blogspot.com/search/label/newton+ar'],
ouachitaar: ['Ouachita, Arkansas', 'https://greaterfinds.blogspot.com/search/label/ouachita+ar'],
perryar: ['Perry, Arkansas', 'https://greaterfinds.blogspot.com/search/label/perry+ar'],
phillipsar: ['Phillips, Arkansas', 'https://greaterfinds.blogspot.com/search/label/phillips+ar'],
pikear: ['Pike, Arkansas', 'https://greaterfinds.blogspot.com/search/label/pike+ar'],
poinsettar: ['Poinsett, Arkansas', 'https://greaterfinds.blogspot.com/search/label/poinsett+ar'],
polkar: ['Polk, Arkansas', 'https://greaterfinds.blogspot.com/search/label/polk+ar'],
popear: ['Pope, Arkansas', 'https://greaterfinds.blogspot.com/search/label/pope+ar'],
prairiear: ['Prairie, Arkansas', 'https://greaterfinds.blogspot.com/search/label/prairie+ar'],
pulaskiar: ['Pulaski, Arkansas', 'https://greaterfinds.blogspot.com/search/label/pulaski+ar'],
randolphar: ['Randolph, Arkansas', 'https://greaterfinds.blogspot.com/search/label/randolph+ar'],
salinear: ['Saline, Arkansas', 'https://greaterfinds.blogspot.com/search/label/saline+ar'],
scottar: ['Scott, Arkansas', 'https://greaterfinds.blogspot.com/search/label/scott+ar'],
searcyar: ['Searcy, Arkansas', 'https://greaterfinds.blogspot.com/search/label/searcy+ar'],
sebastianar: ['Sebastian, Arkansas', 'https://greaterfinds.blogspot.com/search/label/sebastian+ar'],
sevierar: ['Sevier, Arkansas', 'https://greaterfinds.blogspot.com/search/label/sevier+ar'],
sharpar: ['Sharp, Arkansas', 'https://greaterfinds.blogspot.com/search/label/sharp+ar'],
stfrancisar: ['St. Francis, Arkansas', 'https://greaterfinds.blogspot.com/search/label/stfrancis+ar'],
stonear: ['Stone, Arkansas', 'https://greaterfinds.blogspot.com/search/label/stone+ar'],
unionar: ['Union, Arkansas', 'https://greaterfinds.blogspot.com/search/label/union+ar'],
vanburenar: ['Van Buren, Arkansas', 'https://greaterfinds.blogspot.com/search/label/vanburen+ar'],
washingtonar: ['Washington, Arkansas', 'https://greaterfinds.blogspot.com/search/label/washington+ar'],
whitear: ['White, Arkansas', 'https://greaterfinds.blogspot.com/search/label/white+ar'],
woodruffar: ['Woodruff, Arkansas', 'https://greaterfinds.blogspot.com/search/label/woodruff+ar'],
yellar: ['Yell, Arkansas', 'https://greaterfinds.blogspot.com/search/label/yell+ar'],

// CALIFORNIA

alamedaca: ['Alameda, California', 
'https://greaterfinds.blogspot.com/search/label/alameda+ca'],
alpineca: ['Alpine, California', 'https://greaterfinds.blogspot.com/search/label/alpine+ca'],
amadorca: ['Amador, California', 'https://greaterfinds.blogspot.com/search/label/amador+ca'],
butteca: ['Butte, California', 'https://greaterfinds.blogspot.com/search/label/butte+ca'],
calaverasca: ['Calaveras, California', 'https://greaterfinds.blogspot.com/search/label/calaveras+ca'],
colusaca: ['Colusa, California', 'https://greaterfinds.blogspot.com/search/label/colusa+ca'],
contracostaca: ['Contra Costa, California', 'https://greaterfinds.blogspot.com/search/label/contracosta+ca'],
delnorteca: ['Del Norte, California', 'https://greaterfinds.blogspot.com/search/label/delnorte+ca'],
eldoradoca: ['El Dorado, California', 'https://greaterfinds.blogspot.com/search/label/eldorado+ca'],
fresnoca: ['Fresno, California', 'https://greaterfinds.blogspot.com/search/label/fresno+ca'],
glennca: ['Glenn, California', 'https://greaterfinds.blogspot.com/search/label/glenn+ca'],
humboldtca: ['Humboldt, California', 'https://greaterfinds.blogspot.com/search/label/humboldt+ca'],
imperialca: ['Imperial, California', 'https://greaterfinds.blogspot.com/search/label/imperial+ca'],
inyoca: ['Inyo, California', 'https://greaterfinds.blogspot.com/search/label/inyo+ca'],
kernca: ['Kern, California', 'https://greaterfinds.blogspot.com/search/label/kern+ca'],
kingsca: ['Kings, California', 'https://greaterfinds.blogspot.com/search/label/kings+ca'],
lakeca: ['Lake, California', 'https://greaterfinds.blogspot.com/search/label/lake+ca'],
lassenca: ['Lassen, California', 'https://greaterfinds.blogspot.com/search/label/lassen+ca'],
losangelesca: ['Los Angeles, California', 'https://greaterfinds.blogspot.com/search/label/losangeles+ca'],
maderaca: ['Madera, California', 'https://greaterfinds.blogspot.com/search/label/madera+ca'],
marinca: ['Marin, California', 'https://greaterfinds.blogspot.com/search/label/marin+ca'],
mariposaca: ['Mariposa, California', 'https://greaterfinds.blogspot.com/search/label/mariposa+ca'],
mendocinoca: ['Mendocino, California', 'https://greaterfinds.blogspot.com/search/label/mendocino+ca'],
mercedca: ['Merced, California', 'https://greaterfinds.blogspot.com/search/label/merced+ca'],
modocca: ['Modoc, California', 'https://greaterfinds.blogspot.com/search/label/modoc+ca'],
monoca: ['Mono, California', 'https://greaterfinds.blogspot.com/search/label/mono+ca'],
montereyca: ['Monterey, California', 'https://greaterfinds.blogspot.com/search/label/monterey+ca'],
napaca: ['Napa, California', 'https://greaterfinds.blogspot.com/search/label/napa+ca'],
nevadaca: ['Nevada , California', 'https://greaterfinds.blogspot.com/search/label/nevada+ca'],
orangeca: ['Orange, California', 'https://greaterfinds.blogspot.com/search/label/orange+ca'],
placerca: ['Placer, California', 'https://greaterfinds.blogspot.com/search/label/placer+ca'],
plumasca: ['Plumas, California', 'https://greaterfinds.blogspot.com/search/label/plumas+ca'],
riversideca: ['Riverside, California', 'https://greaterfinds.blogspot.com/search/label/riverside+ca'],
sacramentoca: ['Sacramento, California', 'https://greaterfinds.blogspot.com/search/label/sacramento+ca'],
sanbenitoca: ['San Benito, California', 'https://greaterfinds.blogspot.com/search/label/sanbenito+ca'],
sanbernardinoca: ['San Bernardino, California', 'https://greaterfinds.blogspot.com/search/label/sanbernardino+ca'],
sandiegoca: ['San Diego, California', 'https://greaterfinds.blogspot.com/search/label/sandiego+ca'],
sanfranciscoca: ['San Francisco, California', 'https://greaterfinds.blogspot.com/search/label/sanfrancisco+ca'],
sanjoaquinca: ['San Joaquin, California', 'https://greaterfinds.blogspot.com/search/label/sanjoaquin+ca'],
sanluisobispoca: ['San Luis Obispo, California', 'https://greaterfinds.blogspot.com/search/label/sanluisobispo+ca'],
sanmateoca: ['San Mateo, California', 'https://greaterfinds.blogspot.com/search/label/sanmateo+ca'],
santabarbaraca: ['Santa Barbara, California', 'https://greaterfinds.blogspot.com/search/label/santabarbara+ca'],
santaclaraca: ['Santa Clara, California', 'https://greaterfinds.blogspot.com/search/label/santaclara+ca'],
santacruzca: ['Santa Cruz, California', 'https://greaterfinds.blogspot.com/search/label/santacruz+ca'],
shastaca: ['Shasta, California', 'https://greaterfinds.blogspot.com/search/label/shasta+ca'],
sierraca: ['Sierra, California', 'https://greaterfinds.blogspot.com/search/label/sierra+ca'],
siskiyouca: ['Siskiyou, California', 'https://greaterfinds.blogspot.com/search/label/siskiyou+ca'],
solanoca: ['Solano, California', 'https://greaterfinds.blogspot.com/search/label/solano+ca'],
sonomaca: ['Sonoma, California', 'https://greaterfinds.blogspot.com/search/label/sonoma+ca'],
stanislausca: ['Stanislaus, California', 'https://greaterfinds.blogspot.com/search/label/stanislaus+ca'],
sutterca: ['Sutter, California', 'https://greaterfinds.blogspot.com/search/label/sutter+ca'],
tehamaca: ['Tehama, California', 'https://greaterfinds.blogspot.com/search/label/tehama+ca'],
trinityca: ['Trinity, California', 'https://greaterfinds.blogspot.com/search/label/trinity+ca'],
tulareca: ['Tulare, California', 'https://greaterfinds.blogspot.com/search/label/tulare+ca'],
tuolumneca: ['Tuolumne, California', 'https://greaterfinds.blogspot.com/search/label/tuolumne+ca'],
venturaca: ['Ventura, California', 'https://greaterfinds.blogspot.com/search/label/ventura+ca'],
yoloca: ['Yolo, California', 'https://greaterfinds.blogspot.com/search/label/yolo+ca'],
yubaca: ['Yuba, California', 'https://greaterfinds.blogspot.com/search/label/yuba+ca'],

// COLORADO

adamsco: ['Adams, Colorado', 'https://greaterfinds.blogspot.com/search/label/adams+co'],
alamosaco: ['Alamosa, Colorado', 'https://greaterfinds.blogspot.com/search/label/alamosa+co'],
arapahoeco: ['Arapahoe, Colorado', 'https://greaterfinds.blogspot.com/search/label/arapahoe+co'],
archuletaco: ['Archuleta, Colorado', 'https://greaterfinds.blogspot.com/search/label/archuleta+co'],
bacaco: ['Baca, Colorado', 'https://greaterfinds.blogspot.com/search/label/baca+co'],
bentco: ['Bent, Colorado', 'https://greaterfinds.blogspot.com/search/label/bent+co'],
boulderco: ['Boulder, Colorado', 'https://greaterfinds.blogspot.com/search/label/boulder+co'],
broomfieldco: ['Broomfield, Colorado', 'https://greaterfinds.blogspot.com/search/label/broomfield+co'],
chaffeeco: ['Chaffee, Colorado', 'https://greaterfinds.blogspot.com/search/label/chaffee+co'],
cheyenneco: ['Cheyenne, Colorado', 'https://greaterfinds.blogspot.com/search/label/cheyenne+co'],
clearcreekco: ['Clear Creek, Colorado', 'https://greaterfinds.blogspot.com/search/label/clearcreek+co'],
conejosco: ['Conejos, Colorado', 'https://greaterfinds.blogspot.com/search/label/conejos+co'],
costillaco: ['Costilla, Colorado', 'https://greaterfinds.blogspot.com/search/label/costilla+co'],
crowleyco: ['Crowley, Colorado', 'https://greaterfinds.blogspot.com/search/label/crowley+co'],
custerco: ['Custer, Colorado', 'https://greaterfinds.blogspot.com/search/label/custer+co'],
deltaco: ['Delta, Colorado', 'https://greaterfinds.blogspot.com/search/label/delta+co'],
denverco: ['Denver, Colorado', 'https://greaterfinds.blogspot.com/search/label/denver+co'],
doloresco: ['Dolores, Colorado', 'https://greaterfinds.blogspot.com/search/label/dolores+co'],
douglasco: ['Douglas, Colorado', 'https://greaterfinds.blogspot.com/search/label/douglas+co'],
eagleco: ['Eagle, Colorado', 'https://greaterfinds.blogspot.com/search/label/eagle+co'],
elpasoco: ['El Paso, Colorado', 'https://greaterfinds.blogspot.com/search/label/elpaso+co'],
elbertco: ['Elbert, Colorado', 'https://greaterfinds.blogspot.com/search/label/elbert+co'],
fremontco: ['Fremont, Colorado', 'https://greaterfinds.blogspot.com/search/label/fremont+co'],
garfieldco: ['Garfield, Colorado', 'https://greaterfinds.blogspot.com/search/label/garfield+co'],
gilpinco: ['Gilpin, Colorado', 'https://greaterfinds.blogspot.com/search/label/gilpin+co'],
grandco: ['Grand, Colorado', 'https://greaterfinds.blogspot.com/search/label/grand+co'],
gunnisonco: ['Gunnison, Colorado', 'https://greaterfinds.blogspot.com/search/label/gunnison+co'],
hinsdaleco: ['Hinsdale, Colorado', 'https://greaterfinds.blogspot.com/search/label/hinsdale+co'],
huerfanoco: ['Huerfano, Colorado', 'https://greaterfinds.blogspot.com/search/label/huerfano+co'],
jacksonco: ['Jackson, Colorado', 'https://greaterfinds.blogspot.com/search/label/jackson+co'],
jeffersonco: ['Jefferson, Colorado', 'https://greaterfinds.blogspot.com/search/label/jefferson+co'],
kiowaco: ['Kiowa, Colorado', 'https://greaterfinds.blogspot.com/search/label/kiowa+co'],
kitcarsonco: ['Kit Carson, Colorado', 'https://greaterfinds.blogspot.com/search/label/kitcarson+co'],
laplataco: ['La Plata, Colorado', 'https://greaterfinds.blogspot.com/search/label/laplata+co'],
lakeco: ['Lake, Colorado', 'https://greaterfinds.blogspot.com/search/label/lake+co'],
larimerco: ['Larimer, Colorado', 'https://greaterfinds.blogspot.com/search/label/larimer+co'],
lasanimasco: ['Las Animas, Colorado', 'https://greaterfinds.blogspot.com/search/label/lasanimas+co'],
lincolnco: ['Lincoln, Colorado', 'https://greaterfinds.blogspot.com/search/label/lincoln+co'],
loganco: ['Logan, Colorado', 'https://greaterfinds.blogspot.com/search/label/logan+co'],
mesaco: ['Mesa, Colorado', 'https://greaterfinds.blogspot.com/search/label/mesa+co'],
mineralco: ['Mineral, Colorado', 'https://greaterfinds.blogspot.com/search/label/mineral+co'],
moffatco: ['Moffat, Colorado', 'https://greaterfinds.blogspot.com/search/label/moffat+co'],
montezumaco: ['Montezuma, Colorado', 'https://greaterfinds.blogspot.com/search/label/montezuma+co'],
montroseco: ['Montrose, Colorado', 'https://greaterfinds.blogspot.com/search/label/montrose+co'],
morganco: ['Morgan, Colorado', 'https://greaterfinds.blogspot.com/search/label/morgan+co'],
oteroco: ['Otero, Colorado', 'https://greaterfinds.blogspot.com/search/label/otero+co'],
ourayco: ['Ouray, Colorado', 'https://greaterfinds.blogspot.com/search/label/ouray+co'],
parkco: ['Park, Colorado', 'https://greaterfinds.blogspot.com/search/label/park+co'],
phillipsco: ['Phillips, Colorado', 'https://greaterfinds.blogspot.com/search/label/phillips+co'],
pitkinco: ['Pitkin, Colorado', 'https://greaterfinds.blogspot.com/search/label/pitkin+co'],
prowersco: ['Prowers, Colorado', 'https://greaterfinds.blogspot.com/search/label/prowers+co'],
puebloco: ['Pueblo, Colorado', 'https://greaterfinds.blogspot.com/search/label/pueblo+co'],
rioblancoco: ['Rio Blanco, Colorado', 'https://greaterfinds.blogspot.com/search/label/rioblanco+co'],
riograndeco: ['Rio Grande, Colorado', 'https://greaterfinds.blogspot.com/search/label/riogrande+co'],
routtco: ['Routt, Colorado', 'https://greaterfinds.blogspot.com/search/label/routt+co'],
saguacheco: ['Saguache, Colorado', 'https://greaterfinds.blogspot.com/search/label/saguache+co'],
sanjuanco: ['San Juan, Colorado', 'https://greaterfinds.blogspot.com/search/label/sanjuan+co'],
sanmiguelco: ['San Miguel, Colorado', 'https://greaterfinds.blogspot.com/search/label/sanmiguel+co'],
sedgwickco: ['Sedgwick, Colorado', 'https://greaterfinds.blogspot.com/search/label/sedgwick+co'],
summitco: ['Summit, Colorado', 'https://greaterfinds.blogspot.com/search/label/summit+co'],
tellerco: ['Teller, Colorado', 'https://greaterfinds.blogspot.com/search/label/teller+co'],
washingtonco: ['Washington, Colorado', 'https://greaterfinds.blogspot.com/search/label/washington+co'],
weldco: ['Weld, Colorado', 'https://greaterfinds.blogspot.com/search/label/weld+co'],
yumaco: ['Yuma, Colorado', 'https://greaterfinds.blogspot.com/search/label/yuma+co'],
fairfieldct: ['Fairfield, Connecticut', 'https://greaterfinds.blogspot.com/search/label/fairfield+ct'],
hartfordct: ['Hartford, Connecticut', 'https://greaterfinds.blogspot.com/search/label/hartford+ct'],
litchfieldct: ['Litchfield, Connecticut', 'https://greaterfinds.blogspot.com/search/label/litchfield+ct'],
middlesexct: ['Middlesex, Connecticut', 'https://greaterfinds.blogspot.com/search/label/middlesex+ct'],
newhavenct: ['New Haven, Connecticut', 'https://greaterfinds.blogspot.com/search/label/newhaven+ct'],
newlondonct: ['New London, Connecticut', 'https://greaterfinds.blogspot.com/search/label/newlondon+ct'],
tollandct: ['Tolland, Connecticut', 'https://greaterfinds.blogspot.com/search/label/tolland+ct'],
windhamct: ['Windham, Connecticut', 'https://greaterfinds.blogspot.com/search/label/windham+ct'],

// DELAWARE

kentde: ['Kent, Delaware', 'https://greaterfinds.blogspot.com/search/label/kent+de'],
newcastlede: ['New Castle, Delaware', 'https://greaterfinds.blogspot.com/search/label/newcastle+de'],
sussexde: ['Sussex, Delaware', 'https://greaterfinds.blogspot.com/search/label/sussex+de'],

// DC

washingtondc: ['Washington, District of Columbia', 'https://greaterfinds.blogspot.com/search/label/washington+dc'],

// FLORIDA

alachuafl: ['Alachua, Florida', 'https://greaterfinds.blogspot.com/search/label/alachua+fl'],
bakerfl: ['Baker, Florida', 'https://greaterfinds.blogspot.com/search/label/baker+fl'],
bayfl: ['Bay, Florida', 'https://greaterfinds.blogspot.com/search/label/bay+fl'],
bradfordfl: ['Bradford, Florida', 'https://greaterfinds.blogspot.com/search/label/bradford+fl'],
brevardfl: ['Brevard, Florida', 'https://greaterfinds.blogspot.com/search/label/brevard+fl'],
browardfl: ['Broward, Florida', 'https://greaterfinds.blogspot.com/search/label/broward+fl'],
calhounfl: ['Calhoun, Florida', 'https://greaterfinds.blogspot.com/search/label/calhoun+fl'],
charlottefl: ['Charlotte, Florida', 'https://greaterfinds.blogspot.com/search/label/charlotte+fl'],
citrusfl: ['Citrus, Florida', 'https://greaterfinds.blogspot.com/search/label/citrus+fl'],
clayfl: ['Clay, Florida', 'https://greaterfinds.blogspot.com/search/label/clay+fl'],
collierfl: ['Collier, Florida', 'https://greaterfinds.blogspot.com/search/label/collier+fl'],
columbiafl: ['Columbia, Florida', 'https://greaterfinds.blogspot.com/search/label/columbia+fl'],
desotofl: ['DeSoto, Florida', 'https://greaterfinds.blogspot.com/search/label/desoto+fl'],
dixiefl: ['Dixie, Florida', 'https://greaterfinds.blogspot.com/search/label/dixie+fl'],
duvalfl: ['Duval, Florida', 'https://greaterfinds.blogspot.com/search/label/duval+fl'],
escambiafl: ['Escambia, Florida', 'https://greaterfinds.blogspot.com/search/label/escambia+fl'],
flaglerfl: ['Flagler, Florida', 'https://greaterfinds.blogspot.com/search/label/flagler+fl'],
franklinfl: ['Franklin, Florida', 'https://greaterfinds.blogspot.com/search/label/franklin+fl'],
gadsdenfl: ['Gadsden, Florida', 'https://greaterfinds.blogspot.com/search/label/gadsden+fl'],
gilchristfl: ['Gilchrist, Florida', 'https://greaterfinds.blogspot.com/search/label/gilchrist+fl'],
gladesfl: ['Glades, Florida', 'https://greaterfinds.blogspot.com/search/label/glades+fl'],
gulffl: ['Gulf, Florida', 'https://greaterfinds.blogspot.com/search/label/gulf+fl'],
hamiltonfl: ['Hamilton, Florida', 'https://greaterfinds.blogspot.com/search/label/hamilton+fl'],
hardeefl: ['Hardee, Florida', 'https://greaterfinds.blogspot.com/search/label/hardee+fl'],
hendryfl: ['Hendry, Florida', 'https://greaterfinds.blogspot.com/search/label/hendry+fl'],
hernandofl: ['Hernando, Florida', 'https://greaterfinds.blogspot.com/search/label/hernando+fl'],
highlandsfl: ['Highlands, Florida', 'https://greaterfinds.blogspot.com/search/label/highlands+fl'],
hillsboroughfl: ['Hillsborough, Florida', 'https://greaterfinds.blogspot.com/search/label/hillsborough+fl'],
holmesfl: ['Holmes, Florida', 'https://greaterfinds.blogspot.com/search/label/holmes+fl'],
indianriverfl: ['Indian River, Florida', 'https://greaterfinds.blogspot.com/search/label/indianriver+fl'],
jacksonfl: ['Jackson, Florida', 'https://greaterfinds.blogspot.com/search/label/jackson+fl'],
jeffersonfl: ['Jefferson, Florida', 'https://greaterfinds.blogspot.com/search/label/jefferson+fl'],
lafayettefl: ['Lafayette, Florida', 'https://greaterfinds.blogspot.com/search/label/lafayette+fl'],
lakefl: ['Lake, Florida', 'https://greaterfinds.blogspot.com/search/label/lake+fl'],
leefl: ['Lee, Florida', 'https://greaterfinds.blogspot.com/search/label/lee+fl'],
leonfl: ['Leon, Florida', 'https://greaterfinds.blogspot.com/search/label/leon+fl'],
levyfl: ['Levy, Florida', 'https://greaterfinds.blogspot.com/search/label/levy+fl'],
libertyfl: ['Liberty, Florida', 'https://greaterfinds.blogspot.com/search/label/liberty+fl'],

madisonfl: ['Madison, Florida', 'https://greaterfinds.blogspot.com/search/label/madison+fl'],
manateefl: ['Manatee, Florida', 'https://greaterfinds.blogspot.com/search/label/manatee+fl'],
marionfl: ['Marion, Florida', 'https://greaterfinds.blogspot.com/search/label/marion+fl'],
martinfl: ['Martin, Florida', 'https://greaterfinds.blogspot.com/search/label/martin+fl'],
miamidadefl: ['Miami-Dade, Florida', 'https://greaterfinds.blogspot.com/search/label/miamidade+fl'],
monroefl: ['Monroe, Florida', 'https://greaterfinds.blogspot.com/search/label/monroe+fl'],
nassaufl: ['Nassau, Florida', 'https://greaterfinds.blogspot.com/search/label/nassau+fl'],
okaloosafl: ['Okaloosa, Florida', 'https://greaterfinds.blogspot.com/search/label/okaloosa+fl'],
okeechobeefl: ['Okeechobee, Florida', 'https://greaterfinds.blogspot.com/search/label/okeechobee+fl'],
orangefl: ['Orange, Florida', 'https://greaterfinds.blogspot.com/search/label/orange+fl'],
osceolafl: ['Osceola, Florida', 'https://greaterfinds.blogspot.com/search/label/osceola+fl'],
palmbeachfl: ['Palm Beach, Florida', 'https://greaterfinds.blogspot.com/search/label/palmbeach+fl'],
pascofl: ['Pasco, Florida', 'https://greaterfinds.blogspot.com/search/label/pasco+fl'],
pinellasfl: ['Pinellas, Florida', 'https://greaterfinds.blogspot.com/search/label/pinellas+fl'],
polkfl: ['Polk, Florida', 'https://greaterfinds.blogspot.com/search/label/polk+fl'],
putnamfl: ['Putnam, Florida', 'https://greaterfinds.blogspot.com/search/label/putnam+fl'],
santarosafl: ['Santa Rosa, Florida', 'https://greaterfinds.blogspot.com/search/label/santarosa+fl'],
sarasotafl: ['Sarasota, Florida', 'https://greaterfinds.blogspot.com/search/label/sarasota+fl'],
seminolefl: ['Seminole, Florida', 'https://greaterfinds.blogspot.com/search/label/seminole+fl'],
stjohnsfl: ['St. Johns, Florida', 'https://greaterfinds.blogspot.com/search/label/stjohns+fl'],
stluciefl: ['St. Lucie, Florida', 'https://greaterfinds.blogspot.com/search/label/stlucie+fl'],
sumterfl: ['Sumter, Florida', 'https://greaterfinds.blogspot.com/search/label/sumter+fl'],
suwanneefl: ['Suwannee, Florida', 'https://greaterfinds.blogspot.com/search/label/suwannee+fl'],
taylorfl: ['Taylor, Florida', 'https://greaterfinds.blogspot.com/search/label/taylor+fl'],
unionfl: ['Union, Florida', 'https://greaterfinds.blogspot.com/search/label/union+fl'],
volusiafl: ['Volusia, Florida', 'https://greaterfinds.blogspot.com/search/label/volusia+fl'],
wakullafl: ['Wakulla, Florida', 'https://greaterfinds.blogspot.com/search/label/wakulla+fl'],
waltonfl: ['Walton, Florida', 'https://greaterfinds.blogspot.com/search/label/walton+fl'],
washingtonfl: ['Washington, Florida', 'https://greaterfinds.blogspot.com/search/label/washington+fl'],

applingga: ['Appling, Georgia', 'https://greaterfinds.blogspot.com/search/label/appling+ga'],
atkinsonga: ['Atkinson, Georgia', 'https://greaterfinds.blogspot.com/search/label/atkinson+ga'],
baconga: ['Bacon, Georgia', 'https://greaterfinds.blogspot.com/search/label/bacon+ga'],
bakerga: ['Baker, Georgia', 'https://greaterfinds.blogspot.com/search/label/baker+ga'],
baldwinga: ['Baldwin, Georgia', 'https://greaterfinds.blogspot.com/search/label/baldwin+ga'],
banksga: ['Banks, Georgia', 'https://greaterfinds.blogspot.com/search/label/banks+ga'],
barrowga: ['Barrow, Georgia', 'https://greaterfinds.blogspot.com/search/label/barrow+ga'],
bartowga: ['Bartow, Georgia', 'https://greaterfinds.blogspot.com/search/label/bartow+ga'],
benhillga: ['Ben Hill, Georgia', 'https://greaterfinds.blogspot.com/search/label/benhill+ga'],
berrienga: ['Berrien, Georgia', 'https://greaterfinds.blogspot.com/search/label/berrien+ga'],
bibbga: ['Bibb, Georgia', 'https://greaterfinds.blogspot.com/search/label/bibb+ga'],
bleckleyga: ['Bleckley, Georgia', 'https://greaterfinds.blogspot.com/search/label/bleckley+ga'],
brantleyga: ['Brantley, Georgia', 'https://greaterfinds.blogspot.com/search/label/brantley+ga'],
brooksga: ['Brooks, Georgia', 'https://greaterfinds.blogspot.com/search/label/brooks+ga'],
bryanga: ['Bryan, Georgia', 'https://greaterfinds.blogspot.com/search/label/bryan+ga'],
bullochga: ['Bulloch, Georgia', 'https://greaterfinds.blogspot.com/search/label/bulloch+ga'],
burkega: ['Burke, Georgia', 'https://greaterfinds.blogspot.com/search/label/burke+ga'],
buttsga: ['Butts, Georgia', 'https://greaterfinds.blogspot.com/search/label/butts+ga'],
calhounga: ['Calhoun, Georgia', 'https://greaterfinds.blogspot.com/search/label/calhoun+ga'],
camdenga: ['Camden, Georgia', 'https://greaterfinds.blogspot.com/search/label/camden+ga'],
candlerga: ['Candler, Georgia', 'https://greaterfinds.blogspot.com/search/label/candler+ga'],
carrollga: ['Carroll, Georgia', 'https://greaterfinds.blogspot.com/search/label/carroll+ga'],
catoosaga: ['Catoosa, Georgia', 'https://greaterfinds.blogspot.com/search/label/catoosa+ga'],
charltonga: ['Charlton, Georgia', 'https://greaterfinds.blogspot.com/search/label/charlton+ga'],
chathamga: ['Chatham, Georgia', 'https://greaterfinds.blogspot.com/search/label/chatham+ga'],
chattahoocheega: ['Chattahoochee, Georgia', 'https://greaterfinds.blogspot.com/search/label/chattahoochee+ga'],
chattoogaga: ['Chattooga, Georgia', 'https://greaterfinds.blogspot.com/search/label/chattooga+ga'],
cherokeega: ['Cherokee, Georgia', 'https://greaterfinds.blogspot.com/search/label/cherokee+ga'],
clarkega: ['Clarke, Georgia', 'https://greaterfinds.blogspot.com/search/label/clarke+ga'],
clayga: ['Clay, Georgia', 'https://greaterfinds.blogspot.com/search/label/clay+ga'],
claytonga: ['Clayton, Georgia', 'https://greaterfinds.blogspot.com/search/label/clayton+ga'],
clinchga: ['Clinch, Georgia', 'https://greaterfinds.blogspot.com/search/label/clinch+ga'],
cobbga: ['Cobb, Georgia', 'https://greaterfinds.blogspot.com/search/label/cobb+ga'],
coffeega: ['Coffee, Georgia', 'https://greaterfinds.blogspot.com/search/label/coffee+ga'],
colquittga: ['Colquitt, Georgia', 'https://greaterfinds.blogspot.com/search/label/colquitt+ga'],
columbiaga: ['Columbia, Georgia', 'https://greaterfinds.blogspot.com/search/label/columbia+ga'],
cookga: ['Cook, Georgia', 'https://greaterfinds.blogspot.com/search/label/cook+ga'],
cowetaga: ['Coweta, Georgia', 'https://greaterfinds.blogspot.com/search/label/coweta+ga'],
crawfordga: ['Crawford, Georgia', 'https://greaterfinds.blogspot.com/search/label/crawford+ga'],
crispga: ['Crisp, Georgia', 'https://greaterfinds.blogspot.com/search/label/crisp+ga'],
dadega: ['Dade, Georgia', 'https://greaterfinds.blogspot.com/search/label/dade+ga'],
dawsonga: ['Dawson, Georgia', 'https://greaterfinds.blogspot.com/search/label/dawson+ga'],
decaturga: ['Decatur, Georgia', 'https://greaterfinds.blogspot.com/search/label/decatur+ga'],
dekalbga: ['DeKalb, Georgia', 'https://greaterfinds.blogspot.com/search/label/dekalb+ga'],
dodgega: ['Dodge, Georgia', 'https://greaterfinds.blogspot.com/search/label/dodge+ga'],
doolyga: ['Dooly, Georgia', 'https://greaterfinds.blogspot.com/search/label/dooly+ga'],
doughertyga: ['Dougherty, Georgia', 'https://greaterfinds.blogspot.com/search/label/dougherty+ga'],
douglasga: ['Douglas, Georgia', 'https://greaterfinds.blogspot.com/search/label/douglas+ga'],
earlyga: ['Early, Georgia', 'https://greaterfinds.blogspot.com/search/label/early+ga'],
echolsga: ['Echols, Georgia', 'https://greaterfinds.blogspot.com/search/label/echols+ga'],
effinghamga: ['Effingham, Georgia', 'https://greaterfinds.blogspot.com/search/label/effingham+ga'],
elbertga: ['Elbert, Georgia', 'https://greaterfinds.blogspot.com/search/label/elbert+ga'],
emanuelga: ['Emanuel, Georgia', 'https://greaterfinds.blogspot.com/search/label/emanuel+ga'],
evansga: ['Evans, Georgia', 'https://greaterfinds.blogspot.com/search/label/evans+ga'],
fanninga: ['Fannin, Georgia', 'https://greaterfinds.blogspot.com/search/label/fannin+ga'],
fayettega: ['Fayette, Georgia', 'https://greaterfinds.blogspot.com/search/label/fayette+ga'],
floydga: ['Floyd, Georgia', 'https://greaterfinds.blogspot.com/search/label/floyd+ga'],
forsythga: ['Forsyth, Georgia', 'https://greaterfinds.blogspot.com/search/label/forsyth+ga'],
franklinga: ['Franklin, Georgia', 'https://greaterfinds.blogspot.com/search/label/franklin+ga'],
fultonga: ['Fulton, Georgia', 'https://greaterfinds.blogspot.com/search/label/fulton+ga'],
gilmerga: ['Gilmer, Georgia', 'https://greaterfinds.blogspot.com/search/label/gilmer+ga'],
glascockga: ['Glascock, Georgia', 'https://greaterfinds.blogspot.com/search/label/glascock+ga'],
glynnga: ['Glynn, Georgia', 'https://greaterfinds.blogspot.com/search/label/glynn+ga'],
gordonga: ['Gordon, Georgia', 'https://greaterfinds.blogspot.com/search/label/gordon+ga'],
gradyga: ['Grady, Georgia', 'https://greaterfinds.blogspot.com/search/label/grady+ga'],
greenega: ['Greene, Georgia', 'https://greaterfinds.blogspot.com/search/label/greene+ga'],
gwinnettga: ['Gwinnett, Georgia', 'https://greaterfinds.blogspot.com/search/label/gwinnett+ga'],
habershamga: ['Habersham, Georgia', 'https://greaterfinds.blogspot.com/search/label/habersham+ga'],
hallga: ['Hall, Georgia', 'https://greaterfinds.blogspot.com/search/label/hall+ga'],
hancockga: ['Hancock, Georgia', 'https://greaterfinds.blogspot.com/search/label/hancock+ga'],
haralsonga: ['Haralson, Georgia', 'https://greaterfinds.blogspot.com/search/label/haralson+ga'],
harrisga: ['Harris, Georgia', 'https://greaterfinds.blogspot.com/search/label/harris+ga'],
hartga: ['Hart, Georgia', 'https://greaterfinds.blogspot.com/search/label/hart+ga'],
heardga: ['Heard, Georgia', 'https://greaterfinds.blogspot.com/search/label/heard+ga'],
henryga: ['Henry, Georgia', 'https://greaterfinds.blogspot.com/search/label/henry+ga'],
houstonga: ['Houston, Georgia', 'https://greaterfinds.blogspot.com/search/label/houston+ga'],
irwinga: ['Irwin, Georgia', 'https://greaterfinds.blogspot.com/search/label/irwin+ga'],
jacksonga: ['Jackson, Georgia', 'https://greaterfinds.blogspot.com/search/label/jackson+ga'],
jasperga: ['Jasper, Georgia', 'https://greaterfinds.blogspot.com/search/label/jasper+ga'],
jeffdavisga: ['Jeff Davis, Georgia', 'https://greaterfinds.blogspot.com/search/label/jeffdavis+ga'],
jeffersonga: ['Jefferson, Georgia', 'https://greaterfinds.blogspot.com/search/label/jefferson+ga'],
jenkinsga: ['Jenkins, Georgia', 'https://greaterfinds.blogspot.com/search/label/jenkins+ga'],
johnsonga: ['Johnson, Georgia', 'https://greaterfinds.blogspot.com/search/label/johnson+ga'],
jonesga: ['Jones, Georgia', 'https://greaterfinds.blogspot.com/search/label/jones+ga'],
lamarga: ['Lamar, Georgia', 'https://greaterfinds.blogspot.com/search/label/lamar+ga'],
lanierga: ['Lanier, Georgia', 'https://greaterfinds.blogspot.com/search/label/lanier+ga'],
laurensga: ['Laurens, Georgia', 'https://greaterfinds.blogspot.com/search/label/laurens+ga'],
leega: ['Lee, Georgia', 'https://greaterfinds.blogspot.com/search/label/lee+ga'],
libertyga: ['Liberty, Georgia', 'https://greaterfinds.blogspot.com/search/label/liberty+ga'],
lincolnga: ['Lincoln, Georgia', 'https://greaterfinds.blogspot.com/search/label/lincoln+ga'],
longga: ['Long, Georgia', 'https://greaterfinds.blogspot.com/search/label/long+ga'],
lowndesga: ['Lowndes, Georgia', 'https://greaterfinds.blogspot.com/search/label/lowndes+ga'],
lumpkinga: ['Lumpkin, Georgia', 'https://greaterfinds.blogspot.com/search/label/lumpkin+ga'],
maconga: ['Macon, Georgia', 'https://greaterfinds.blogspot.com/search/label/macon+ga'],
madisonga: ['Madison, Georgia', 'https://greaterfinds.blogspot.com/search/label/madison+ga'],
marionga: ['Marion, Georgia', 'https://greaterfinds.blogspot.com/search/label/marion+ga'],
mcduffiega: ['McDuffie, Georgia', 'https://greaterfinds.blogspot.com/search/label/mcduffie+ga'],
mcintoshga: ['McIntosh, Georgia', 'https://greaterfinds.blogspot.com/search/label/mcintosh+ga'],
meriwetherga: ['Meriwether, Georgia', 'https://greaterfinds.blogspot.com/search/label/meriwether+ga'],
millerga: ['Miller, Georgia', 'https://greaterfinds.blogspot.com/search/label/miller+ga'],
mitchellga: ['Mitchell, Georgia', 'https://greaterfinds.blogspot.com/search/label/mitchell+ga'],
monroega: ['Monroe, Georgia', 'https://greaterfinds.blogspot.com/search/label/monroe+ga'],
montgomeryga: ['Montgomery, Georgia', 'https://greaterfinds.blogspot.com/search/label/montgomery+ga'],
morganga: ['Morgan, Georgia', 'https://greaterfinds.blogspot.com/search/label/morgan+ga'],
murrayga: ['Murray, Georgia', 'https://greaterfinds.blogspot.com/search/label/murray+ga'],
muscogeega: ['Muscogee, Georgia', 'https://greaterfinds.blogspot.com/search/label/muscogee+ga'],
newtonga: ['Newton, Georgia', 'https://greaterfinds.blogspot.com/search/label/newton+ga'],
oconeega: ['Oconee, Georgia', 'https://greaterfinds.blogspot.com/search/label/oconee+ga'],
oglethorpega: ['Oglethorpe, Georgia', 'https://greaterfinds.blogspot.com/search/label/oglethorpe+ga'],
pauldingga: ['Paulding, Georgia', 'https://greaterfinds.blogspot.com/search/label/paulding+ga'],
peachga: ['Peach, Georgia', 'https://greaterfinds.blogspot.com/search/label/peach+ga'],
pickensga: ['Pickens, Georgia', 'https://greaterfinds.blogspot.com/search/label/pickens+ga'],
piercega: ['Pierce, Georgia', 'https://greaterfinds.blogspot.com/search/label/pierce+ga'],
pikega: ['Pike, Georgia', 'https://greaterfinds.blogspot.com/search/label/pike+ga'],
polkga: ['Polk, Georgia', 'https://greaterfinds.blogspot.com/search/label/polk+ga'],
pulaskiga: ['Pulaski, Georgia', 'https://greaterfinds.blogspot.com/search/label/pulaski+ga'],
putnamga: ['Putnam, Georgia', 'https://greaterfinds.blogspot.com/search/label/putnam+ga'],
quitmanga: ['Quitman, Georgia', 'https://greaterfinds.blogspot.com/search/label/quitman+ga'],
rabunga: ['Rabun, Georgia', 'https://greaterfinds.blogspot.com/search/label/rabun+ga'],
randolphga: ['Randolph, Georgia', 'https://greaterfinds.blogspot.com/search/label/randolph+ga'],
richmondga: ['Richmond, Georgia', 'https://greaterfinds.blogspot.com/search/label/richmond+ga'],
rockdalega: ['Rockdale, Georgia', 'https://greaterfinds.blogspot.com/search/label/rockdale+ga'],
schleyga: ['Schley, Georgia', 'https://greaterfinds.blogspot.com/search/label/schley+ga'],
screvenga: ['Screven, Georgia', 'https://greaterfinds.blogspot.com/search/label/screven+ga'],
seminolega: ['Seminole, Georgia', 'https://greaterfinds.blogspot.com/search/label/seminole+ga'],
spaldingga: ['Spalding, Georgia', 'https://greaterfinds.blogspot.com/search/label/spalding+ga'],
stephensga: ['Stephens, Georgia', 'https://greaterfinds.blogspot.com/search/label/stephens+ga'],
stewartga: ['Stewart, Georgia', 'https://greaterfinds.blogspot.com/search/label/stewart+ga'],
sumterga: ['Sumter, Georgia', 'https://greaterfinds.blogspot.com/search/label/sumter+ga'],
talbotga: ['Talbot, Georgia', 'https://greaterfinds.blogspot.com/search/label/talbot+ga'],
taliaferroga: ['Taliaferro, Georgia', 'https://greaterfinds.blogspot.com/search/label/taliaferro+ga'],
tattnallga: ['Tattnall, Georgia', 'https://greaterfinds.blogspot.com/search/label/tattnall+ga'],
taylorga: ['Taylor, Georgia', 'https://greaterfinds.blogspot.com/search/label/taylor+ga'],
telfairga: ['Telfair, Georgia', 'https://greaterfinds.blogspot.com/search/label/telfair+ga'],
terrellga: ['Terrell, Georgia', 'https://greaterfinds.blogspot.com/search/label/terrell+ga'],
thomasga: ['Thomas, Georgia', 'https://greaterfinds.blogspot.com/search/label/thomas+ga'],
tiftga: ['Tift, Georgia', 'https://greaterfinds.blogspot.com/search/label/tift+ga'],
toombsga: ['Toombs, Georgia', 'https://greaterfinds.blogspot.com/search/label/toombs+ga'],
townsga: ['Towns, Georgia', 'https://greaterfinds.blogspot.com/search/label/towns+ga'],
treutlenga: ['Treutlen, Georgia', 'https://greaterfinds.blogspot.com/search/label/treutlen+ga'],
troupga: ['Troup, Georgia', 'https://greaterfinds.blogspot.com/search/label/troup+ga'],
turnerga: ['Turner, Georgia', 'https://greaterfinds.blogspot.com/search/label/turner+ga'],
twiggsga: ['Twiggs, Georgia', 'https://greaterfinds.blogspot.com/search/label/twiggs+ga'],
unionga: ['Union, Georgia', 'https://greaterfinds.blogspot.com/search/label/union+ga'],
upsonga: ['Upson, Georgia', 'https://greaterfinds.blogspot.com/search/label/upson+ga'],
walkerga: ['Walker, Georgia', 'https://greaterfinds.blogspot.com/search/label/walker+ga'],
waltonga: ['Walton, Georgia', 'https://greaterfinds.blogspot.com/search/label/walton+ga'],
warega: ['Ware, Georgia', 'https://greaterfinds.blogspot.com/search/label/ware+ga'],
warrenga: ['Warren, Georgia', 'https://greaterfinds.blogspot.com/search/label/warren+ga'],
washingtonga: ['Washington, Georgia', 'https://greaterfinds.blogspot.com/search/label/washington+ga'],
waynega: ['Wayne, Georgia', 'https://greaterfinds.blogspot.com/search/label/wayne+ga'],
websterga: ['Webster, Georgia', 'https://greaterfinds.blogspot.com/search/label/webster+ga'],
wheelerga: ['Wheeler, Georgia', 'https://greaterfinds.blogspot.com/search/label/wheeler+ga'],
whitega: ['White, Georgia', 'https://greaterfinds.blogspot.com/search/label/white+ga'],
whitfieldga: ['Whitfield, Georgia', 'https://greaterfinds.blogspot.com/search/label/whitfield+ga'],
wilcoxga: ['Wilcox, Georgia', 'https://greaterfinds.blogspot.com/search/label/wilcox+ga'],
wilkesga: ['Wilkes, Georgia', 'https://greaterfinds.blogspot.com/search/label/wilkes+ga'],
wilkinsonga: ['Wilkinson, Georgia', 'https://greaterfinds.blogspot.com/search/label/wilkinson+ga'],
worthga: ['Worth, Georgia', 'https://greaterfinds.blogspot.com/search/label/worth+ga'],
hawaiihi: ['Hawaii , Hawaii', 'https://greaterfinds.blogspot.com/search/label/hawaii+hi'],
honoluluhi: ['Honolulu, Hawaii', 'https://greaterfinds.blogspot.com/search/label/honolulu+hi'],
kalawaohi: ['Kalawao, Hawaii', 'https://greaterfinds.blogspot.com/search/label/kalawao+hi'],
kauaihi: ['Kauai, Hawaii', 'https://greaterfinds.blogspot.com/search/label/kauai+hi'],
mauihi: ['Maui, Hawaii', 'https://greaterfinds.blogspot.com/search/label/maui+hi'],
adaid: ['Ada, Idaho', 'https://greaterfinds.blogspot.com/search/label/ada+id'],
adamsid: ['Adams, Idaho', 'https://greaterfinds.blogspot.com/search/label/adams+id'],
bannockid: ['Bannock, Idaho', 'https://greaterfinds.blogspot.com/search/label/bannock+id'],
bearlakeid: ['Bear Lake, Idaho', 'https://greaterfinds.blogspot.com/search/label/bearlake+id'],
benewahid: ['Benewah, Idaho', 'https://greaterfinds.blogspot.com/search/label/benewah+id'],
binghamid: ['Bingham, Idaho', 'https://greaterfinds.blogspot.com/search/label/bingham+id'],
blaineid: ['Blaine, Idaho', 'https://greaterfinds.blogspot.com/search/label/blaine+id'],
boiseid: ['Boise, Idaho', 'https://greaterfinds.blogspot.com/search/label/boise+id'],
bonnerid: ['Bonner, Idaho', 'https://greaterfinds.blogspot.com/search/label/bonner+id'],
bonnevilleid: ['Bonneville, Idaho', 'https://greaterfinds.blogspot.com/search/label/bonneville+id'],
boundaryid: ['Boundary, Idaho', 'https://greaterfinds.blogspot.com/search/label/boundary+id'],
butteid: ['Butte, Idaho', 'https://greaterfinds.blogspot.com/search/label/butte+id'],
camasid: ['Camas, Idaho', 'https://greaterfinds.blogspot.com/search/label/camas+id'],
canyonid: ['Canyon, Idaho', 'https://greaterfinds.blogspot.com/search/label/canyon+id'],
caribouid: ['Caribou, Idaho', 'https://greaterfinds.blogspot.com/search/label/caribou+id'],
cassiaid: ['Cassia, Idaho', 'https://greaterfinds.blogspot.com/search/label/cassia+id'],
clarkid: ['Clark, Idaho', 'https://greaterfinds.blogspot.com/search/label/clark+id'],
clearwaterid: ['Clearwater, Idaho', 'https://greaterfinds.blogspot.com/search/label/clearwater+id'],
custerid: ['Custer, Idaho', 'https://greaterfinds.blogspot.com/search/label/custer+id'],
elmoreid: ['Elmore, Idaho', 'https://greaterfinds.blogspot.com/search/label/elmore+id'],
franklinid: ['Franklin, Idaho', 'https://greaterfinds.blogspot.com/search/label/franklin+id'],
fremontid: ['Fremont, Idaho', 'https://greaterfinds.blogspot.com/search/label/fremont+id'],
gemid: ['Gem, Idaho', 'https://greaterfinds.blogspot.com/search/label/gem+id'],
goodingid: ['Gooding, Idaho', 'https://greaterfinds.blogspot.com/search/label/gooding+id'],
idahoid: ['Idaho , Idaho', 'https://greaterfinds.blogspot.com/search/label/idaho+id'],
jeffersonid: ['Jefferson, Idaho', 'https://greaterfinds.blogspot.com/search/label/jefferson+id'],
jeromeid: ['Jerome, Idaho', 'https://greaterfinds.blogspot.com/search/label/jerome+id'],
kootenaiid: ['Kootenai, Idaho', 'https://greaterfinds.blogspot.com/search/label/kootenai+id'],
latahid: ['Latah, Idaho', 'https://greaterfinds.blogspot.com/search/label/latah+id'],
lemhiid: ['Lemhi, Idaho', 'https://greaterfinds.blogspot.com/search/label/lemhi+id'],
lewisid: ['Lewis, Idaho', 'https://greaterfinds.blogspot.com/search/label/lewis+id'],
lincolnid: ['Lincoln, Idaho', 'https://greaterfinds.blogspot.com/search/label/lincoln+id'],
madisonid: ['Madison, Idaho', 'https://greaterfinds.blogspot.com/search/label/madison+id'],
minidokaid: ['Minidoka, Idaho', 'https://greaterfinds.blogspot.com/search/label/minidoka+id'],
nezperceid: ['Nez Perce, Idaho', 'https://greaterfinds.blogspot.com/search/label/nezperce+id'],
oneidaid: ['Oneida, Idaho', 'https://greaterfinds.blogspot.com/search/label/oneida+id'],
owyheeid: ['Owyhee, Idaho', 'https://greaterfinds.blogspot.com/search/label/owyhee+id'],
payetteid: ['Payette, Idaho', 'https://greaterfinds.blogspot.com/search/label/payette+id'],
powerid: ['Power, Idaho', 'https://greaterfinds.blogspot.com/search/label/power+id'],
shoshoneid: ['Shoshone, Idaho', 'https://greaterfinds.blogspot.com/search/label/shoshone+id'],
tetonid: ['Teton, Idaho', 'https://greaterfinds.blogspot.com/search/label/teton+id'],
twinfallsid: ['Twin Falls, Idaho', 'https://greaterfinds.blogspot.com/search/label/twinfalls+id'],
valleyid: ['Valley, Idaho', 'https://greaterfinds.blogspot.com/search/label/valley+id'],
washingtonid: ['Washington, Idaho', 'https://greaterfinds.blogspot.com/search/label/washington+id'],
adamsil: ['Adams, Illinois', 'https://greaterfinds.blogspot.com/search/label/adams+il'],
alexanderil: ['Alexander, Illinois', 'https://greaterfinds.blogspot.com/search/label/alexander+il'],
bondil: ['Bond, Illinois', 'https://greaterfinds.blogspot.com/search/label/bond+il'],
booneil: ['Boone, Illinois', 'https://greaterfinds.blogspot.com/search/label/boone+il'],
brownil: ['Brown, Illinois', 'https://greaterfinds.blogspot.com/search/label/brown+il'],
bureauil: ['Bureau, Illinois', 'https://greaterfinds.blogspot.com/search/label/bureau+il'],
calhounil: ['Calhoun, Illinois', 'https://greaterfinds.blogspot.com/search/label/calhoun+il'],
carrollil: ['Carroll, Illinois', 'https://greaterfinds.blogspot.com/search/label/carroll+il'],
cassil: ['Cass, Illinois', 'https://greaterfinds.blogspot.com/search/label/cass+il'],
champaignil: ['Champaign, Illinois', 'https://greaterfinds.blogspot.com/search/label/champaign+il'],
christianil: ['Christian, Illinois', 'https://greaterfinds.blogspot.com/search/label/christian+il'],
clarkil: ['Clark, Illinois', 'https://greaterfinds.blogspot.com/search/label/clark+il'],
clayil: ['Clay, Illinois', 'https://greaterfinds.blogspot.com/search/label/clay+il'],
clintonil: ['Clinton, Illinois', 'https://greaterfinds.blogspot.com/search/label/clinton+il'],
colesil: ['Coles, Illinois', 'https://greaterfinds.blogspot.com/search/label/coles+il'],
cookil: ['Cook, Illinois', 'https://greaterfinds.blogspot.com/search/label/cook+il'],
crawfordil: ['Crawford, Illinois', 'https://greaterfinds.blogspot.com/search/label/crawford+il'],
cumberlandil: ['Cumberland, Illinois', 'https://greaterfinds.blogspot.com/search/label/cumberland+il'],
dekalbil: ['DeKalb, Illinois', 'https://greaterfinds.blogspot.com/search/label/dekalb+il'],
dewittil: ['DeWitt, Illinois', 'https://greaterfinds.blogspot.com/search/label/dewitt+il'],
douglasil: ['Douglas, Illinois', 'https://greaterfinds.blogspot.com/search/label/douglas+il'],
dupageil: ['DuPage, Illinois', 'https://greaterfinds.blogspot.com/search/label/dupage+il'],
edgaril: ['Edgar, Illinois', 'https://greaterfinds.blogspot.com/search/label/edgar+il'],
edwardsil: ['Edwards, Illinois', 'https://greaterfinds.blogspot.com/search/label/edwards+il'],
effinghamil: ['Effingham, Illinois', 'https://greaterfinds.blogspot.com/search/label/effingham+il'],
fayetteil: ['Fayette, Illinois', 'https://greaterfinds.blogspot.com/search/label/fayette+il'],
fordil: ['Ford, Illinois', 'https://greaterfinds.blogspot.com/search/label/ford+il'],
franklinil: ['Franklin, Illinois', 'https://greaterfinds.blogspot.com/search/label/franklin+il'],
fultonil: ['Fulton, Illinois', 'https://greaterfinds.blogspot.com/search/label/fulton+il'],
gallatinil: ['Gallatin, Illinois', 'https://greaterfinds.blogspot.com/search/label/gallatin+il'],
greeneil: ['Greene, Illinois', 'https://greaterfinds.blogspot.com/search/label/greene+il'],
grundyil: ['Grundy, Illinois', 'https://greaterfinds.blogspot.com/search/label/grundy+il'],
hamiltonil: ['Hamilton, Illinois', 'https://greaterfinds.blogspot.com/search/label/hamilton+il'],
hancockil: ['Hancock, Illinois', 'https://greaterfinds.blogspot.com/search/label/hancock+il'],
hardinil: ['Hardin, Illinois', 'https://greaterfinds.blogspot.com/search/label/hardin+il'],
hendersonil: ['Henderson, Illinois', 'https://greaterfinds.blogspot.com/search/label/henderson+il'],
henryil: ['Henry, Illinois', 'https://greaterfinds.blogspot.com/search/label/henry+il'],
iroquoisil: ['Iroquois, Illinois', 'https://greaterfinds.blogspot.com/search/label/iroquois+il'],
jacksonil: ['Jackson, Illinois', 'https://greaterfinds.blogspot.com/search/label/jackson+il'],
jasperil: ['Jasper, Illinois', 'https://greaterfinds.blogspot.com/search/label/jasper+il'],
jeffersonil: ['Jefferson, Illinois', 'https://greaterfinds.blogspot.com/search/label/jefferson+il'],
jerseyil: ['Jersey, Illinois', 'https://greaterfinds.blogspot.com/search/label/jersey+il'],
jodaviessil: ['Jo Daviess, Illinois', 'https://greaterfinds.blogspot.com/search/label/jodaviess+il'],
johnsonil: ['Johnson, Illinois', 'https://greaterfinds.blogspot.com/search/label/johnson+il'],
kaneil: ['Kane, Illinois', 'https://greaterfinds.blogspot.com/search/label/kane+il'],
kankakeeil: ['Kankakee, Illinois', 'https://greaterfinds.blogspot.com/search/label/kankakee+il'],
kendallil: ['Kendall, Illinois', 'https://greaterfinds.blogspot.com/search/label/kendall+il'],
knoxil: ['Knox, Illinois', 'https://greaterfinds.blogspot.com/search/label/knox+il'],
lakeil: ['Lake, Illinois', 'https://greaterfinds.blogspot.com/search/label/lake+il'],
lasalleil: ['LaSalle, Illinois', 'https://greaterfinds.blogspot.com/search/label/lasalle+il'],
lawrenceil: ['Lawrence, Illinois', 'https://greaterfinds.blogspot.com/search/label/lawrence+il'],
leeil: ['Lee, Illinois', 'https://greaterfinds.blogspot.com/search/label/lee+il'],
livingstonil: ['Livingston, Illinois', 'https://greaterfinds.blogspot.com/search/label/livingston+il'],
loganil: ['Logan, Illinois', 'https://greaterfinds.blogspot.com/search/label/logan+il'],
maconil: ['Macon, Illinois', 'https://greaterfinds.blogspot.com/search/label/macon+il'],
macoupinil: ['Macoupin, Illinois', 'https://greaterfinds.blogspot.com/search/label/macoupin+il'],
madisonil: ['Madison, Illinois', 'https://greaterfinds.blogspot.com/search/label/madison+il'],
marionil: ['Marion, Illinois', 'https://greaterfinds.blogspot.com/search/label/marion+il'],
marshallil: ['Marshall, Illinois', 'https://greaterfinds.blogspot.com/search/label/marshall+il'],
masonil: ['Mason, Illinois', 'https://greaterfinds.blogspot.com/search/label/mason+il'],
massacil: ['Massac, Illinois', 'https://greaterfinds.blogspot.com/search/label/massac+il'],
mcdonoughil: ['McDonough, Illinois', 'https://greaterfinds.blogspot.com/search/label/mcdonough+il'],
mchenryil: ['McHenry, Illinois', 'https://greaterfinds.blogspot.com/search/label/mchenry+il'],
mcleanil: ['McLean, Illinois', 'https://greaterfinds.blogspot.com/search/label/mclean+il'],
menardil: ['Menard, Illinois', 'https://greaterfinds.blogspot.com/search/label/menard+il'],
merceril: ['Mercer, Illinois', 'https://greaterfinds.blogspot.com/search/label/mercer+il'],
monroeil: ['Monroe, Illinois', 'https://greaterfinds.blogspot.com/search/label/monroe+il'],
montgomeryil: ['Montgomery, Illinois', 'https://greaterfinds.blogspot.com/search/label/montgomery+il'],
morganil: ['Morgan, Illinois', 'https://greaterfinds.blogspot.com/search/label/morgan+il'],
moultrieil: ['Moultrie, Illinois', 'https://greaterfinds.blogspot.com/search/label/moultrie+il'],
ogleil: ['Ogle, Illinois', 'https://greaterfinds.blogspot.com/search/label/ogle+il'],
peoriail: ['Peoria, Illinois', 'https://greaterfinds.blogspot.com/search/label/peoria+il'],
perryil: ['Perry, Illinois', 'https://greaterfinds.blogspot.com/search/label/perry+il'],
piattil: ['Piatt, Illinois', 'https://greaterfinds.blogspot.com/search/label/piatt+il'],
pikeil: ['Pike, Illinois', 'https://greaterfinds.blogspot.com/search/label/pike+il'],
popeil: ['Pope, Illinois', 'https://greaterfinds.blogspot.com/search/label/pope+il'],
pulaskiil: ['Pulaski, Illinois', 'https://greaterfinds.blogspot.com/search/label/pulaski+il'],
putnamil: ['Putnam, Illinois', 'https://greaterfinds.blogspot.com/search/label/putnam+il'],
randolphil: ['Randolph, Illinois', 'https://greaterfinds.blogspot.com/search/label/randolph+il'],
richlandil: ['Richland, Illinois', 'https://greaterfinds.blogspot.com/search/label/richland+il'],
rockislandil: ['Rock Island, Illinois', 'https://greaterfinds.blogspot.com/search/label/rockisland+il'],
salineil: ['Saline, Illinois', 'https://greaterfinds.blogspot.com/search/label/saline+il'],
sangamonil: ['Sangamon, Illinois', 'https://greaterfinds.blogspot.com/search/label/sangamon+il'],
schuyleril: ['Schuyler, Illinois', 'https://greaterfinds.blogspot.com/search/label/schuyler+il'],
scottil: ['Scott, Illinois', 'https://greaterfinds.blogspot.com/search/label/scott+il'],
shelbyil: ['Shelby, Illinois', 'https://greaterfinds.blogspot.com/search/label/shelby+il'],
stclairil: ['St. Clair, Illinois', 'https://greaterfinds.blogspot.com/search/label/stclair+il'],
starkil: ['Stark, Illinois', 'https://greaterfinds.blogspot.com/search/label/stark+il'],
stephensonil: ['Stephenson, Illinois', 'https://greaterfinds.blogspot.com/search/label/stephenson+il'],
tazewellil: ['Tazewell, Illinois', 'https://greaterfinds.blogspot.com/search/label/tazewell+il'],
unionil: ['Union, Illinois', 'https://greaterfinds.blogspot.com/search/label/union+il'],
vermilionil: ['Vermilion, Illinois', 'https://greaterfinds.blogspot.com/search/label/vermilion+il'],
wabashil: ['Wabash, Illinois', 'https://greaterfinds.blogspot.com/search/label/wabash+il'],
warrenil: ['Warren, Illinois', 'https://greaterfinds.blogspot.com/search/label/warren+il'],
washingtonil: ['Washington, Illinois', 'https://greaterfinds.blogspot.com/search/label/washington+il'],
wayneil: ['Wayne, Illinois', 'https://greaterfinds.blogspot.com/search/label/wayne+il'],
whiteil: ['White, Illinois', 'https://greaterfinds.blogspot.com/search/label/white+il'],
whitesideil: ['Whiteside, Illinois', 'https://greaterfinds.blogspot.com/search/label/whiteside+il'],
willil: ['Will, Illinois', 'https://greaterfinds.blogspot.com/search/label/will+il'],
williamsonil: ['Williamson, Illinois', 'https://greaterfinds.blogspot.com/search/label/williamson+il'],
winnebagoil: ['Winnebago, Illinois', 'https://greaterfinds.blogspot.com/search/label/winnebago+il'],
woodfordil: ['Woodford, Illinois', 'https://greaterfinds.blogspot.com/search/label/woodford+il'],
adamsin: ['Adams, Indiana', 'https://greaterfinds.blogspot.com/search/label/adams+in'],
allenin: ['Allen, Indiana', 'https://greaterfinds.blogspot.com/search/label/allen+in'],
bartholomewin: ['Bartholomew, Indiana', 'https://greaterfinds.blogspot.com/search/label/bartholomew+in'],
bentonin: ['Benton, Indiana', 'https://greaterfinds.blogspot.com/search/label/benton+in'],
blackfordin: ['Blackford, Indiana', 'https://greaterfinds.blogspot.com/search/label/blackford+in'],
boonein: ['Boone, Indiana', 'https://greaterfinds.blogspot.com/search/label/boone+in'],
brownin: ['Brown, Indiana', 'https://greaterfinds.blogspot.com/search/label/brown+in'],
carrollin: ['Carroll, Indiana', 'https://greaterfinds.blogspot.com/search/label/carroll+in'],
cassin: ['Cass, Indiana', 'https://greaterfinds.blogspot.com/search/label/cass+in'],
clarkin: ['Clark, Indiana', 'https://greaterfinds.blogspot.com/search/label/clark+in'],
clayin: ['Clay, Indiana', 'https://greaterfinds.blogspot.com/search/label/clay+in'],
clintonin: ['Clinton, Indiana', 'https://greaterfinds.blogspot.com/search/label/clinton+in'],
crawfordin: ['Crawford, Indiana', 'https://greaterfinds.blogspot.com/search/label/crawford+in'],
daviessin: ['Daviess, Indiana', 'https://greaterfinds.blogspot.com/search/label/daviess+in'],
dearbornin: ['Dearborn, Indiana', 'https://greaterfinds.blogspot.com/search/label/dearborn+in'],
decaturin: ['Decatur, Indiana', 'https://greaterfinds.blogspot.com/search/label/decatur+in'],
dekalbin: ['DeKalb, Indiana', 'https://greaterfinds.blogspot.com/search/label/dekalb+in'],
delawarein: ['Delaware , Indiana', 'https://greaterfinds.blogspot.com/search/label/delaware+in'],
duboisin: ['Dubois, Indiana', 'https://greaterfinds.blogspot.com/search/label/dubois+in'],
elkhartin: ['Elkhart, Indiana', 'https://greaterfinds.blogspot.com/search/label/elkhart+in'],
fayettein: ['Fayette, Indiana', 'https://greaterfinds.blogspot.com/search/label/fayette+in'],
floydin: ['Floyd, Indiana', 'https://greaterfinds.blogspot.com/search/label/floyd+in'],
fountainin: ['Fountain, Indiana', 'https://greaterfinds.blogspot.com/search/label/fountain+in'],
franklinin: ['Franklin, Indiana', 'https://greaterfinds.blogspot.com/search/label/franklin+in'],
fultonin: ['Fulton, Indiana', 'https://greaterfinds.blogspot.com/search/label/fulton+in'],
gibsonin: ['Gibson, Indiana', 'https://greaterfinds.blogspot.com/search/label/gibson+in'],
grantin: ['Grant, Indiana', 'https://greaterfinds.blogspot.com/search/label/grant+in'],
greenein: ['Greene, Indiana', 'https://greaterfinds.blogspot.com/search/label/greene+in'],
hamiltonin: ['Hamilton, Indiana', 'https://greaterfinds.blogspot.com/search/label/hamilton+in'],
hancockin: ['Hancock, Indiana', 'https://greaterfinds.blogspot.com/search/label/hancock+in'],
harrisonin: ['Harrison, Indiana', 'https://greaterfinds.blogspot.com/search/label/harrison+in'],
hendricksin: ['Hendricks, Indiana', 'https://greaterfinds.blogspot.com/search/label/hendricks+in'],
henryin: ['Henry, Indiana', 'https://greaterfinds.blogspot.com/search/label/henry+in'],
howardin: ['Howard, Indiana', 'https://greaterfinds.blogspot.com/search/label/howard+in'],
huntingtonin: ['Huntington, Indiana', 'https://greaterfinds.blogspot.com/search/label/huntington+in'],
jacksonin: ['Jackson, Indiana', 'https://greaterfinds.blogspot.com/search/label/jackson+in'],
jasperin: ['Jasper, Indiana', 'https://greaterfinds.blogspot.com/search/label/jasper+in'],
jayin: ['Jay, Indiana', 'https://greaterfinds.blogspot.com/search/label/jay+in'],
jeffersonin: ['Jefferson, Indiana', 'https://greaterfinds.blogspot.com/search/label/jefferson+in'],
jenningsin: ['Jennings, Indiana', 'https://greaterfinds.blogspot.com/search/label/jennings+in'],
johnsonin: ['Johnson, Indiana', 'https://greaterfinds.blogspot.com/search/label/johnson+in'],
knoxin: ['Knox, Indiana', 'https://greaterfinds.blogspot.com/search/label/knox+in'],
kosciuskoin: ['Kosciusko, Indiana', 'https://greaterfinds.blogspot.com/search/label/kosciusko+in'],
lagrangein: ['LaGrange, Indiana', 'https://greaterfinds.blogspot.com/search/label/lagrange+in'],
lakein: ['Lake, Indiana', 'https://greaterfinds.blogspot.com/search/label/lake+in'],
laportein: ['LaPorte, Indiana', 'https://greaterfinds.blogspot.com/search/label/laporte+in'],
lawrencein: ['Lawrence, Indiana', 'https://greaterfinds.blogspot.com/search/label/lawrence+in'],
madisonin: ['Madison, Indiana', 'https://greaterfinds.blogspot.com/search/label/madison+in'],
marionin: ['Marion, Indiana', 'https://greaterfinds.blogspot.com/search/label/marion+in'],
marshallin: ['Marshall, Indiana', 'https://greaterfinds.blogspot.com/search/label/marshall+in'],
martinin: ['Martin, Indiana', 'https://greaterfinds.blogspot.com/search/label/martin+in'],
miamiin: ['Miami, Indiana', 'https://greaterfinds.blogspot.com/search/label/miami+in'],
monroein: ['Monroe, Indiana', 'https://greaterfinds.blogspot.com/search/label/monroe+in'],
montgomeryin: ['Montgomery, Indiana', 'https://greaterfinds.blogspot.com/search/label/montgomery+in'],
morganin: ['Morgan, Indiana', 'https://greaterfinds.blogspot.com/search/label/morgan+in'],
newtonin: ['Newton, Indiana', 'https://greaterfinds.blogspot.com/search/label/newton+in'],
noblein: ['Noble, Indiana', 'https://greaterfinds.blogspot.com/search/label/noble+in'],
ohioin: ['Ohio , Indiana', 'https://greaterfinds.blogspot.com/search/label/ohio+in'],
orangein: ['Orange, Indiana', 'https://greaterfinds.blogspot.com/search/label/orange+in'],
owenin: ['Owen, Indiana', 'https://greaterfinds.blogspot.com/search/label/owen+in'],
parkein: ['Parke, Indiana', 'https://greaterfinds.blogspot.com/search/label/parke+in'],
perryin: ['Perry, Indiana', 'https://greaterfinds.blogspot.com/search/label/perry+in'],
pikein: ['Pike, Indiana', 'https://greaterfinds.blogspot.com/search/label/pike+in'],
porterin: ['Porter, Indiana', 'https://greaterfinds.blogspot.com/search/label/porter+in'],
poseyin: ['Posey, Indiana', 'https://greaterfinds.blogspot.com/search/label/posey+in'],
pulaskiin: ['Pulaski, Indiana', 'https://greaterfinds.blogspot.com/search/label/pulaski+in'],
putnamin: ['Putnam, Indiana', 'https://greaterfinds.blogspot.com/search/label/putnam+in'],
randolphin: ['Randolph, Indiana', 'https://greaterfinds.blogspot.com/search/label/randolph+in'],
ripleyin: ['Ripley, Indiana', 'https://greaterfinds.blogspot.com/search/label/ripley+in'],
rushin: ['Rush, Indiana', 'https://greaterfinds.blogspot.com/search/label/rush+in'],
scottin: ['Scott, Indiana', 'https://greaterfinds.blogspot.com/search/label/scott+in'],
shelbyin: ['Shelby, Indiana', 'https://greaterfinds.blogspot.com/search/label/shelby+in'],
spencerin: ['Spencer, Indiana', 'https://greaterfinds.blogspot.com/search/label/spencer+in'],
stjosephin: ['St. Joseph, Indiana', 'https://greaterfinds.blogspot.com/search/label/stjoseph+in'],
starkein: ['Starke, Indiana', 'https://greaterfinds.blogspot.com/search/label/starke+in'],
steubenin: ['Steuben, Indiana', 'https://greaterfinds.blogspot.com/search/label/steuben+in'],
sullivanin: ['Sullivan, Indiana', 'https://greaterfinds.blogspot.com/search/label/sullivan+in'],
switzerlandin: ['Switzerland, Indiana', 'https://greaterfinds.blogspot.com/search/label/switzerland+in'],
tippecanoein: ['Tippecanoe, Indiana', 'https://greaterfinds.blogspot.com/search/label/tippecanoe+in'],
tiptonin: ['Tipton, Indiana', 'https://greaterfinds.blogspot.com/search/label/tipton+in'],
unionin: ['Union, Indiana', 'https://greaterfinds.blogspot.com/search/label/union+in'],
vanderburghin: ['Vanderburgh, Indiana', 'https://greaterfinds.blogspot.com/search/label/vanderburgh+in'],
vermillionin: ['Vermillion, Indiana', 'https://greaterfinds.blogspot.com/search/label/vermillion+in'],
vigoin: ['Vigo, Indiana', 'https://greaterfinds.blogspot.com/search/label/vigo+in'],
wabashin: ['Wabash, Indiana', 'https://greaterfinds.blogspot.com/search/label/wabash+in'],
warrenin: ['Warren, Indiana', 'https://greaterfinds.blogspot.com/search/label/warren+in'],
warrickin: ['Warrick, Indiana', 'https://greaterfinds.blogspot.com/search/label/warrick+in'],
washingtonin: ['Washington, Indiana', 'https://greaterfinds.blogspot.com/search/label/washington+in'],
waynein: ['Wayne, Indiana', 'https://greaterfinds.blogspot.com/search/label/wayne+in'],
wellsin: ['Wells, Indiana', 'https://greaterfinds.blogspot.com/search/label/wells+in'],
whitein: ['White, Indiana', 'https://greaterfinds.blogspot.com/search/label/white+in'],
whitleyin: ['Whitley, Indiana', 'https://greaterfinds.blogspot.com/search/label/whitley+in'],
adairia: ['Adair, Iowa', 'https://greaterfinds.blogspot.com/search/label/adair+ia'],
adamsia: ['Adams, Iowa', 'https://greaterfinds.blogspot.com/search/label/adams+ia'],
allamakeeia: ['Allamakee, Iowa', 'https://greaterfinds.blogspot.com/search/label/allamakee+ia'],
appanooseia: ['Appanoose, Iowa', 'https://greaterfinds.blogspot.com/search/label/appanoose+ia'],
audubonia: ['Audubon, Iowa', 'https://greaterfinds.blogspot.com/search/label/audubon+ia'],
bentonia: ['Benton, Iowa', 'https://greaterfinds.blogspot.com/search/label/benton+ia'],
blackhawkia: ['Black Hawk, Iowa', 'https://greaterfinds.blogspot.com/search/label/blackhawk+ia'],
booneia: ['Boone, Iowa', 'https://greaterfinds.blogspot.com/search/label/boone+ia'],
bremeria: ['Bremer, Iowa', 'https://greaterfinds.blogspot.com/search/label/bremer+ia'],
buchanania: ['Buchanan, Iowa', 'https://greaterfinds.blogspot.com/search/label/buchanan+ia'],
buenavistaia: ['Buena Vista, Iowa', 'https://greaterfinds.blogspot.com/search/label/buenavista+ia'],
butleria: ['Butler, Iowa', 'https://greaterfinds.blogspot.com/search/label/butler+ia'],
calhounia: ['Calhoun, Iowa', 'https://greaterfinds.blogspot.com/search/label/calhoun+ia'],
carrollia: ['Carroll, Iowa', 'https://greaterfinds.blogspot.com/search/label/carroll+ia'],
cassia: ['Cass, Iowa', 'https://greaterfinds.blogspot.com/search/label/cass+ia'],
cedaria: ['Cedar, Iowa', 'https://greaterfinds.blogspot.com/search/label/cedar+ia'],
cerrogordoia: ['Cerro Gordo, Iowa', 'https://greaterfinds.blogspot.com/search/label/cerrogordo+ia'],
cherokeeia: ['Cherokee, Iowa', 'https://greaterfinds.blogspot.com/search/label/cherokee+ia'],
chickasawia: ['Chickasaw, Iowa', 'https://greaterfinds.blogspot.com/search/label/chickasaw+ia'],
clarkeia: ['Clarke, Iowa', 'https://greaterfinds.blogspot.com/search/label/clarke+ia'],
clayia: ['Clay, Iowa', 'https://greaterfinds.blogspot.com/search/label/clay+ia'],
claytonia: ['Clayton, Iowa', 'https://greaterfinds.blogspot.com/search/label/clayton+ia'],
clintonia: ['Clinton, Iowa', 'https://greaterfinds.blogspot.com/search/label/clinton+ia'],
crawfordia: ['Crawford, Iowa', 'https://greaterfinds.blogspot.com/search/label/crawford+ia'],
dallasia: ['Dallas, Iowa', 'https://greaterfinds.blogspot.com/search/label/dallas+ia'],
davisia: ['Davis, Iowa', 'https://greaterfinds.blogspot.com/search/label/davis+ia'],
decaturia: ['Decatur, Iowa', 'https://greaterfinds.blogspot.com/search/label/decatur+ia'],
delawareia: ['Delaware , Iowa', 'https://greaterfinds.blogspot.com/search/label/delaware+ia'],
desmoinesia: ['Des Moines, Iowa', 'https://greaterfinds.blogspot.com/search/label/desmoines+ia'],
dickinsonia: ['Dickinson, Iowa', 'https://greaterfinds.blogspot.com/search/label/dickinson+ia'],
dubuqueia: ['Dubuque, Iowa', 'https://greaterfinds.blogspot.com/search/label/dubuque+ia'],
emmetia: ['Emmet, Iowa', 'https://greaterfinds.blogspot.com/search/label/emmet+ia'],
fayetteia: ['Fayette, Iowa', 'https://greaterfinds.blogspot.com/search/label/fayette+ia'],
floydia: ['Floyd, Iowa', 'https://greaterfinds.blogspot.com/search/label/floyd+ia'],
franklinia: ['Franklin, Iowa', 'https://greaterfinds.blogspot.com/search/label/franklin+ia'],
fremontia: ['Fremont, Iowa', 'https://greaterfinds.blogspot.com/search/label/fremont+ia'],
greeneia: ['Greene, Iowa', 'https://greaterfinds.blogspot.com/search/label/greene+ia'],
grundyia: ['Grundy, Iowa', 'https://greaterfinds.blogspot.com/search/label/grundy+ia'],
guthrieia: ['Guthrie, Iowa', 'https://greaterfinds.blogspot.com/search/label/guthrie+ia'],
hamiltonia: ['Hamilton, Iowa', 'https://greaterfinds.blogspot.com/search/label/hamilton+ia'],
hancockia: ['Hancock, Iowa', 'https://greaterfinds.blogspot.com/search/label/hancock+ia'],
hardinia: ['Hardin, Iowa', 'https://greaterfinds.blogspot.com/search/label/hardin+ia'],
harrisonia: ['Harrison, Iowa', 'https://greaterfinds.blogspot.com/search/label/harrison+ia'],
henryia: ['Henry, Iowa', 'https://greaterfinds.blogspot.com/search/label/henry+ia'],
howardia: ['Howard, Iowa', 'https://greaterfinds.blogspot.com/search/label/howard+ia'],
humboldtia: ['Humboldt, Iowa', 'https://greaterfinds.blogspot.com/search/label/humboldt+ia'],
idaia: ['Ida, Iowa', 'https://greaterfinds.blogspot.com/search/label/ida+ia'],
iowaia: ['Iowa , Iowa', 'https://greaterfinds.blogspot.com/search/label/iowa+ia'],
jacksonia: ['Jackson, Iowa', 'https://greaterfinds.blogspot.com/search/label/jackson+ia'],
jasperia: ['Jasper, Iowa', 'https://greaterfinds.blogspot.com/search/label/jasper+ia'],
jeffersonia: ['Jefferson, Iowa', 'https://greaterfinds.blogspot.com/search/label/jefferson+ia'],
johnsonia: ['Johnson, Iowa', 'https://greaterfinds.blogspot.com/search/label/johnson+ia'],
jonesia: ['Jones, Iowa', 'https://greaterfinds.blogspot.com/search/label/jones+ia'],
keokukia: ['Keokuk, Iowa', 'https://greaterfinds.blogspot.com/search/label/keokuk+ia'],
kossuthia: ['Kossuth, Iowa', 'https://greaterfinds.blogspot.com/search/label/kossuth+ia'],
leeia: ['Lee, Iowa', 'https://greaterfinds.blogspot.com/search/label/lee+ia'],
linnia: ['Linn, Iowa', 'https://greaterfinds.blogspot.com/search/label/linn+ia'],
louisaia: ['Louisa, Iowa', 'https://greaterfinds.blogspot.com/search/label/louisa+ia'],
lucasia: ['Lucas, Iowa', 'https://greaterfinds.blogspot.com/search/label/lucas+ia'],
lyonia: ['Lyon, Iowa', 'https://greaterfinds.blogspot.com/search/label/lyon+ia'],
madisonia: ['Madison, Iowa', 'https://greaterfinds.blogspot.com/search/label/madison+ia'],
mahaskaia: ['Mahaska, Iowa', 'https://greaterfinds.blogspot.com/search/label/mahaska+ia'],
marionia: ['Marion, Iowa', 'https://greaterfinds.blogspot.com/search/label/marion+ia'],
marshallia: ['Marshall, Iowa', 'https://greaterfinds.blogspot.com/search/label/marshall+ia'],
millsia: ['Mills, Iowa', 'https://greaterfinds.blogspot.com/search/label/mills+ia'],
mitchellia: ['Mitchell, Iowa', 'https://greaterfinds.blogspot.com/search/label/mitchell+ia'],
mononaia: ['Monona, Iowa', 'https://greaterfinds.blogspot.com/search/label/monona+ia'],
monroeia: ['Monroe, Iowa', 'https://greaterfinds.blogspot.com/search/label/monroe+ia'],
montgomeryia: ['Montgomery, Iowa', 'https://greaterfinds.blogspot.com/search/label/montgomery+ia'],
muscatineia: ['Muscatine, Iowa', 'https://greaterfinds.blogspot.com/search/label/muscatine+ia'],
obrienia: ['O'Brien, Iowa', 'https://greaterfinds.blogspot.com/search/label/obrien+ia'],
osceolaia: ['Osceola, Iowa', 'https://greaterfinds.blogspot.com/search/label/osceola+ia'],
pageia: ['Page, Iowa', 'https://greaterfinds.blogspot.com/search/label/page+ia'],
paloaltoia: ['Palo Alto, Iowa', 'https://greaterfinds.blogspot.com/search/label/paloalto+ia'],
plymouthia: ['Plymouth, Iowa', 'https://greaterfinds.blogspot.com/search/label/plymouth+ia'],
pocahontasia: ['Pocahontas, Iowa', 'https://greaterfinds.blogspot.com/search/label/pocahontas+ia'],
polkia: ['Polk, Iowa', 'https://greaterfinds.blogspot.com/search/label/polk+ia'],
pottawattamieia: ['Pottawattamie, Iowa', 'https://greaterfinds.blogspot.com/search/label/pottawattamie+ia'],
poweshiekia: ['Poweshiek, Iowa', 'https://greaterfinds.blogspot.com/search/label/poweshiek+ia'],
ringgoldia: ['Ringgold, Iowa', 'https://greaterfinds.blogspot.com/search/label/ringgold+ia'],
sacia: ['Sac, Iowa', 'https://greaterfinds.blogspot.com/search/label/sac+ia'],
scottia: ['Scott, Iowa', 'https://greaterfinds.blogspot.com/search/label/scott+ia'],
shelbyia: ['Shelby, Iowa', 'https://greaterfinds.blogspot.com/search/label/shelby+ia'],
siouxia: ['Sioux, Iowa', 'https://greaterfinds.blogspot.com/search/label/sioux+ia'],
storyia: ['Story, Iowa', 'https://greaterfinds.blogspot.com/search/label/story+ia'],
tamaia: ['Tama, Iowa', 'https://greaterfinds.blogspot.com/search/label/tama+ia'],
tayloria: ['Taylor, Iowa', 'https://greaterfinds.blogspot.com/search/label/taylor+ia'],
unionia: ['Union, Iowa', 'https://greaterfinds.blogspot.com/search/label/union+ia'],
vanburenia: ['Van Buren, Iowa', 'https://greaterfinds.blogspot.com/search/label/vanburen+ia'],
wapelloia: ['Wapello, Iowa', 'https://greaterfinds.blogspot.com/search/label/wapello+ia'],
warrenia: ['Warren, Iowa', 'https://greaterfinds.blogspot.com/search/label/warren+ia'],
washingtonia: ['Washington, Iowa', 'https://greaterfinds.blogspot.com/search/label/washington+ia'],
wayneia: ['Wayne, Iowa', 'https://greaterfinds.blogspot.com/search/label/wayne+ia'],
websteria: ['Webster, Iowa', 'https://greaterfinds.blogspot.com/search/label/webster+ia'],
winnebagoia: ['Winnebago, Iowa', 'https://greaterfinds.blogspot.com/search/label/winnebago+ia'],
winneshiekia: ['Winneshiek, Iowa', 'https://greaterfinds.blogspot.com/search/label/winneshiek+ia'],
woodburyia: ['Woodbury, Iowa', 'https://greaterfinds.blogspot.com/search/label/woodbury+ia'],
worthia: ['Worth, Iowa', 'https://greaterfinds.blogspot.com/search/label/worth+ia'],
wrightia: ['Wright, Iowa', 'https://greaterfinds.blogspot.com/search/label/wright+ia'],




}