var countiesLookup = {
"stclair": function() {return "St. Clair";},
"aleutianseast": function() {return "Aleutians East";},
"aleutianswest": function() {return "Aleutians West ";},
"bristolbay": function() {return "Bristol Bay";},
"fairbanksnorthstar": function() {return "Fairbanks North Star";},
"kenaipeninsula": function() {return "Kenai Peninsula";},
"ketchikangateway": function() {return "Ketchikan Gateway";},
"kodiakisland": function() {return "Kodiak Island";},
"lakeandpeninsula": function() {return "Lake and Peninsula";},
"northslope": function() {return "North Slope";},
"northwestarctic": function() {return "Northwest Arctic";},
"princeofwaleshyder": function() {return "Prince of Wales-Hyder ";},
"southeastfairbanks": function() {return "Southeast Fairbanks ";},
"lapaz": function() {return "La Paz";},
"santacruz": function() {return "Santa Cruz";},
"hotspring": function() {return "Hot Spring";},
"littleriver": function() {return "Little River";},
"stfrancis": function() {return "St. Francis";},
"vanburen": function() {return "Van Buren";},
"contracosta": function() {return "Contra Costa";},
"delnorte": function() {return "Del Norte";},
"eldorado": function() {return "El Dorado";},
"losangeles": function() {return "Los Angeles";},
"sanbenito": function() {return "San Benito";},
"sanbernardino": function() {return "San Bernardino";},
"sandiego": function() {return "San Diego";},
"sanfrancisco": function() {return "San Francisco";},
"sanjoaquin": function() {return "San Joaquin";},
"sanluisobispo": function() {return "San Luis Obispo";},
"sanmateo": function() {return "San Mateo";},
"santabarbara": function() {return "Santa Barbara";},
"santaclara": function() {return "Santa Clara";},
"santacruz": function() {return "Santa Cruz";},
"clearcreek": function() {return "Clear Creek";},
"elpaso": function() {return "El Paso";},
"kitcarson": function() {return "Kit Carson";},
"laplata": function() {return "La Plata";},
"lasanimas": function() {return "Las Animas";},
"rioblanco": function() {return "Rio Blanco";},
"riogrande": function() {return "Rio Grande";},
"sanjuan": function() {return "San Juan";},
"sanmiguel": function() {return "San Miguel";},
"newhaven": function() {return "New Haven";},
"newlondon": function() {return "New London";},
"newcastle": function() {return "New Castle";},
"indianriver": function() {return "Indian River";},
"palmbeach": function() {return "Palm Beach";},
"santarosa": function() {return "Santa Rosa";},
"stjohns": function() {return "St. Johns";},
"stlucie": function() {return "St. Lucie";},
"benhill": function() {return "Ben Hill";},
"jeffdavis": function() {return "Jeff Davis";},
"bearlake": function() {return "Bear Lake";},
"nezperce": function() {return "Nez Perce";},
"twinfalls": function() {return "Twin Falls";},
"jodaviess": function() {return "Jo Daviess";},
"rockisland": function() {return "Rock Island";},
"stjoseph": function() {return "St. Joseph";},
"blackhawk": function() {return "Black Hawk";},
"buenavista": function() {return "Buena Vista";},
"cerrogordo": function() {return "Cerro Gordo";},
"desmoines": function() {return "Des Moines";},
"paloalto": function() {return "Palo Alto";},
"vanburen": function() {return "Van Buren";},
"eastbatonrouge": function() {return "East Baton Rouge";},
"eastcarroll": function() {return "East Carroll";},
"eastfeliciana": function() {return "East Feliciana";},
"jeffersondavis": function() {return "Jefferson Davis";},
"lasalle": function() {return "La Salle";},
"pointecoupee": function() {return "Pointe Coupee";},
"redriver": function() {return "Red River";},
"stbernard": function() {return "St. Bernard";},
"stcharles": function() {return "St. Charles";},
"sthelena": function() {return "St. Helena";},
"stjames": function() {return "St. James";},
"stjohnthebaptist": function() {return "St. John the Baptist";},
"stlandry": function() {return "St. Landry";},
"stmartin": function() {return "St. Martin";},
"stmary": function() {return "St. Mary";},
"sttammany": function() {return "St. Tammany";},
"westbatonrouge": function() {return "West Baton Rouge";},
"westcarroll": function() {return "West Carroll";},
"westfeliciana": function() {return "West Feliciana";},
"annearundel": function() {return "Anne Arundel";},
"baltimorecity": function() {return "Baltimore City";},
"princegeorges": function() {return "Prince George's";},
"queenannes": function() {return "Queen Anne's";},
"stmarys": function() {return "St. Mary's";},
"grandtraverse": function() {return "Grand Traverse";},
"presqueisle": function() {return "Presque Isle";},
"vanburen": function() {return "Van Buren";},
"bigstone": function() {return "Big Stone";},
"blueearth": function() {return "Blue Earth";},
"crowwing": function() {return "Crow Wing";},
"lacquiparle": function() {return "Lac qui Parle";},
"lakeofthewoods": function() {return "Lake of the Woods";},
"lesueur": function() {return "Le Sueur";},
"millelacs": function() {return "Mille Lacs";},
"ottertail": function() {return "Otter Tail";},
"redlake": function() {return "Red Lake";},
"stlouis": function() {return "St. Louis ";},
"yellowmedicine": function() {return "Yellow Medicine";},
"jeffersondavis": function() {return "Jefferson Davis";},
"pearlriver": function() {return "Pearl River";},
"capegirardeau": function() {return "Cape Girardeau";},
"newmadrid": function() {return "New Madrid";},
"stfrancois": function() {return "St. Francois";},
"stlouiscity": function() {return "St. Louis City";},
"stegenevieve": function() {return "Ste. Genevieve";},
"bighorn": function() {return "Big Horn";},
"deerlodge": function() {return "Deer Lodge";},
"goldenvalley": function() {return "Golden Valley";},
"judithbasin": function() {return "Judith Basin";},
"lewisandclark": function() {return "Lewis and Clark";},
"powderriver": function() {return "Powder River";},
"silverbow": function() {return "Silver Bow";},
"sweetgrass": function() {return "Sweet Grass";},
"boxbutte": function() {return "Box Butte";},
"keyapaha": function() {return "Keya Paha";},
"redwillow": function() {return "Red Willow";},
"scottsbluff": function() {return "Scotts Bluff";},
"carsoncity": function() {return "Carson City";},
"whitepine": function() {return "White Pine";},
"capemay": function() {return "Cape May";},
"debaca": function() {return "De Baca";},
"doñaana": function() {return "Doña Ana";},
"losalamos": function() {return "Los Alamos";},
"rioarriba": function() {return "Rio Arriba";},
"sanjuan": function() {return "San Juan";},
"sanmiguel": function() {return "San Miguel";},
"santafe": function() {return "Santa Fe";},
"newyork": function() {return "New York ";},
"stlawrence": function() {return "St. Lawrence";},
"newhanover": function() {return "New Hanover";},
"goldenvalley": function() {return "Golden Valley";},
"grandforks": function() {return "Grand Forks";},
"vanwert": function() {return "Van Wert";},
"leflore": function() {return "Le Flore";},
"rogermills": function() {return "Roger Mills";},
"hoodriver": function() {return "Hood River";},
"bonhomme": function() {return "Bon Homme";},
"charlesmix": function() {return "Charles Mix";},
"fallriver": function() {return "Fall River";},
"oglalalakota": function() {return "Oglala Lakota";},
"vanburen": function() {return "Van Buren";},
"deafsmith": function() {return "Deaf Smith";},
"elpaso": function() {return "El Paso";},
"fortbend": function() {return "Fort Bend";},
"jeffdavis": function() {return "Jeff Davis";},
"jimhogg": function() {return "Jim Hogg";},
"jimwells": function() {return "Jim Wells";},
"lasalle": function() {return "La Salle";},
"liveoak": function() {return "Live Oak";},
"palopinto": function() {return "Palo Pinto";},
"redriver": function() {return "Red River";},
"sanaugustine": function() {return "San Augustine";},
"sanjacinto": function() {return "San Jacinto";},
"sanpatricio": function() {return "San Patricio";},
"sansaba": function() {return "San Saba";},
"tomgreen": function() {return "Tom Green";},
"valverde": function() {return "Val Verde";},
"vanzandt": function() {return "Van Zandt";},
"boxelder": function() {return "Box Elder";},
"saltlake": function() {return "Salt Lake";},
"sanjuan": function() {return "San Juan";},
"grandisle": function() {return "Grand Isle";},
"alexandriacity": function() {return "Alexandria City";},
"bedfordcity": function() {return "Bedford City";},
"bristolcity": function() {return "Bristol City";},
"buenavistacity": function() {return "Buena Vista City";},
"charlescity": function() {return "Charles City ";},
"charlottesvillecity": function() {return "Charlottesville City";},
"chesapeakecity": function() {return "Chesapeake City";},
"colonialheightscity": function() {return "Colonial Heights City";},
"covingtoncity": function() {return "Covington City";},
"danvillecity": function() {return "Danville City";},
"emporiacity": function() {return "Emporia City";},
"fairfaxcity": function() {return "Fairfax City";},
"fallschurchcity": function() {return "Falls Church City";},
"franklincity": function() {return "Franklin City";},
"fredericksburgcity": function() {return "Fredericksburg City";},
"galaxcity": function() {return "Galax City";},
"hamptoncity": function() {return "Hampton City";},
"harrisonburgcity": function() {return "Harrisonburg City";},
"hopewellcity": function() {return "Hopewell City";},
"isleofwight": function() {return "Isle of Wight";},
"jamescity": function() {return "James City ";},
"kingandqueen": function() {return "King and Queen";},
"kinggeorge": function() {return "King George";},
"kingwilliam": function() {return "King William";},
"lexingtoncity": function() {return "Lexington City";},
"lynchburgcity": function() {return "Lynchburg City";},
"manassascity": function() {return "Manassas City";},
"manassasparkcity": function() {return "Manassas Park City";},
"martinsvillecity": function() {return "Martinsville City";},
"newkent": function() {return "New Kent";},
"newportnewscity": function() {return "Newport News City";},
"norfolkcity": function() {return "Norfolk City";},
"nortoncity": function() {return "Norton City";},
"petersburgcity": function() {return "Petersburg City";},
"poquosoncity": function() {return "Poquoson City";},
"portsmouthcity": function() {return "Portsmouth City";},
"princeedward": function() {return "Prince Edward";},
"princegeorge": function() {return "Prince George";},
"princewilliam": function() {return "Prince William";},
"radfordcity": function() {return "Radford City";},
"richmondcity": function() {return "Richmond City";},
"roanokecity": function() {return "Roanoke City";},
"salemcity": function() {return "Salem City";},
"stauntoncity": function() {return "Staunton City";},
"suffolkcity": function() {return "Suffolk City";},
"virginiabeachcity": function() {return "Virginia Beach City";},
"waynesborocity": function() {return "Waynesboro City";},
"williamsburgcity": function() {return "Williamsburg City";},
"winchestercity": function() {return "Winchester City";},
"graysharbor": function() {return "Grays Harbor";},
"pendoreille": function() {return "Pend Oreille";},
"sanjuan": function() {return "San Juan";},
"wallawalla": function() {return "Walla Walla";},
"eauclaire": function() {return "Eau Claire";},
"fonddulac": function() {return "Fond du Lac";},
"greenlake": function() {return "Green Lake";},
"lacrosse": function() {return "La Crosse";},
"stcroix": function() {return "St. Croix";},
"bighorn": function() {return "Big Horn";},
"hotsprings": function() {return "Hot Springs";},
};