var shortcuts = {

// ALABAMA
autaugaal: ['Autauga, Alabama', 'https://greaterfinds.blogspot.com/search/label/autauga+al'],
baldwinal: ['Baldwin, Alabama', 'https://greaterfinds.blogspot.com/search/label/baldwin+al'],
barboural: ['Barbour, Alabama', 'https://greaterfinds.blogspot.com/search/label/barbour+al'],
bibbal: ['Bibb, Alabama', 'https://greaterfinds.blogspot.com/search/label/bibb+al'],
blountal: ['Blount, Alabama', 'https://greaterfinds.blogspot.com/search/label/blount+al'],
bullockal: ['Bullock, Alabama', 'https://greaterfinds.blogspot.com/search/label/bullock+al'],
butleral: ['Butler, Alabama', 'https://greaterfinds.blogspot.com/search/label/butler+al'],
calhounal: ['Calhoun, Alabama', 'https://greaterfinds.blogspot.com/search/label/calhoun+al'],
chambersal: ['Chambers, Alabama', 'https://greaterfinds.blogspot.com/search/label/chambers+al'],
cherokeeal: ['Cherokee, Alabama', 'https://greaterfinds.blogspot.com/search/label/cherokee+al'],
chiltonal: ['Chilton, Alabama', 'https://greaterfinds.blogspot.com/search/label/chilton+al'],
choctawal: ['Choctaw, Alabama', 'https://greaterfinds.blogspot.com/search/label/choctaw+al'],
clarkeal: ['Clarke, Alabama', 'https://greaterfinds.blogspot.com/search/label/clarke+al'],
clayal: ['Clay, Alabama', 'https://greaterfinds.blogspot.com/search/label/clay+al'],
cleburneal: ['Cleburne, Alabama', 'https://greaterfinds.blogspot.com/search/label/cleburne+al'],
coffeeal: ['Coffee, Alabama', 'https://greaterfinds.blogspot.com/search/label/coffee+al'],
colbertal: ['Colbert, Alabama', 'https://greaterfinds.blogspot.com/search/label/colbert+al'],
conecuhal: ['Conecuh, Alabama', 'https://greaterfinds.blogspot.com/search/label/conecuh+al'],
coosaal: ['Coosa, Alabama', 'https://greaterfinds.blogspot.com/search/label/coosa+al'],
covingtonal: ['Covington, Alabama', 'https://greaterfinds.blogspot.com/search/label/covington+al'],
crenshawal: ['Crenshaw, Alabama', 'https://greaterfinds.blogspot.com/search/label/crenshaw+al'],
cullmanal: ['Cullman, Alabama', 'https://greaterfinds.blogspot.com/search/label/cullman+al'],
daleal: ['Dale, Alabama', 'https://greaterfinds.blogspot.com/search/label/dale+al'],
dallasal: ['Dallas, Alabama', 'https://greaterfinds.blogspot.com/search/label/dallas+al'],
dekalbal: ['DeKalb, Alabama', 'https://greaterfinds.blogspot.com/search/label/dekalb+al'],
elmoreal: ['Elmore, Alabama', 'https://greaterfinds.blogspot.com/search/label/elmore+al'],
escambiaal: ['Escambia, Alabama', 'https://greaterfinds.blogspot.com/search/label/escambia+al'],
etowahal: ['Etowah, Alabama', 'https://greaterfinds.blogspot.com/search/label/etowah+al'],
fayetteal: ['Fayette, Alabama', 'https://greaterfinds.blogspot.com/search/label/fayette+al'],
franklinal: ['Franklin, Alabama', 'https://greaterfinds.blogspot.com/search/label/franklin+al'],
genevaal: ['Geneva, Alabama', 'https://greaterfinds.blogspot.com/search/label/geneva+al'],
greeneal: ['Greene, Alabama', 'https://greaterfinds.blogspot.com/search/label/greene+al'],
haleal: ['Hale, Alabama', 'https://greaterfinds.blogspot.com/search/label/hale+al'],
henryal: ['Henry, Alabama', 'https://greaterfinds.blogspot.com/search/label/henry+al'],
houstonal: ['Houston, Alabama', 'https://greaterfinds.blogspot.com/search/label/houston+al'],
jacksonal: ['Jackson, Alabama', 'https://greaterfinds.blogspot.com/search/label/jackson+al'],
jeffersonal: ['Jefferson, Alabama', 'https://greaterfinds.blogspot.com/search/label/jefferson+al'],
lamaral: ['Lamar, Alabama', 'https://greaterfinds.blogspot.com/search/label/lamar+al'],
lauderdaleal: ['Lauderdale, Alabama', 'https://greaterfinds.blogspot.com/search/label/lauderdale+al'],
lawrenceal: ['Lawrence, Alabama', 'https://greaterfinds.blogspot.com/search/label/lawrence+al'],
leeal: ['Lee, Alabama', 'https://greaterfinds.blogspot.com/search/label/lee+al'],
limestoneal: ['Limestone, Alabama', 'https://greaterfinds.blogspot.com/search/label/limestone+al'],
lowndesal: ['Lowndes, Alabama', 'https://greaterfinds.blogspot.com/search/label/lowndes+al'],
maconal: ['Macon, Alabama', 'https://greaterfinds.blogspot.com/search/label/macon+al'],
madisonal: ['Madison, Alabama', 'https://greaterfinds.blogspot.com/search/label/madison+al'],
marengoal: ['Marengo, Alabama', 'https://greaterfinds.blogspot.com/search/label/marengo+al'],
marional: ['Marion, Alabama', 'https://greaterfinds.blogspot.com/search/label/marion+al'],
marshallal: ['Marshall, Alabama', 'https://greaterfinds.blogspot.com/search/label/marshall+al'],
mobileal: ['Mobile, Alabama', 'https://greaterfinds.blogspot.com/search/label/mobile+al'],
monroeal: ['Monroe, Alabama', 'https://greaterfinds.blogspot.com/search/label/monroe+al'],
montgomeryal: ['Montgomery, Alabama', 'https://greaterfinds.blogspot.com/search/label/montgomery+al'],
morganal: ['Morgan, Alabama', 'https://greaterfinds.blogspot.com/search/label/morgan+al'],
perryal: ['Perry, Alabama', 'https://greaterfinds.blogspot.com/search/label/perry+al'],
pickensal: ['Pickens, Alabama', 'https://greaterfinds.blogspot.com/search/label/pickens+al'],
pikeal: ['Pike, Alabama', 'https://greaterfinds.blogspot.com/search/label/pike+al'],
randolphal: ['Randolph, Alabama', 'https://greaterfinds.blogspot.com/search/label/randolph+al'],
russellal: ['Russell, Alabama', 'https://greaterfinds.blogspot.com/search/label/russell+al'],
shelbyal: ['Shelby, Alabama', 'https://greaterfinds.blogspot.com/search/label/shelby+al'],
stclairal: ['St. Clair, Alabama', 'https://greaterfinds.blogspot.com/search/label/stclair+al'],
sumteral: ['Sumter, Alabama', 'https://greaterfinds.blogspot.com/search/label/sumter+al'],
talladegaal: ['Talladega, Alabama', 'https://greaterfinds.blogspot.com/search/label/talladega+al'],
tallapoosaal: ['Tallapoosa, Alabama', 'https://greaterfinds.blogspot.com/search/label/tallapoosa+al'],
tuscaloosaal: ['Tuscaloosa, Alabama', 'https://greaterfinds.blogspot.com/search/label/tuscaloosa+al'],
walkeral: ['Walker, Alabama', 'https://greaterfinds.blogspot.com/search/label/walker+al'],
washingtonal: ['Washington , Alabama', 'https://greaterfinds.blogspot.com/search/label/washington+al'],
wilcoxal: ['Wilcox, Alabama', 'https://greaterfinds.blogspot.com/search/label/wilcox+al'],
winstonal: ['Winston, Alabama', 'https://greaterfinds.blogspot.com/search/label/winston+al'],

// ALASKA
aleutianseastak: ['Aleutians East, Alaska', 'https://greaterfinds.blogspot.com/search/label/aleutianseast+ak'],
aleutianswestak: ['Aleutians West , Alaska', 'https://greaterfinds.blogspot.com/search/label/aleutianswest+ak'],
anchorageak: ['Anchorage, Alaska', 'https://greaterfinds.blogspot.com/search/label/anchorage+ak'],
bethelak: ['Bethel , Alaska', 'https://greaterfinds.blogspot.com/search/label/bethel+ak'],
bristolbayak: ['Bristol Bay, Alaska', 'https://greaterfinds.blogspot.com/search/label/bristolbay+ak'],
denaliak: ['Denali, Alaska', 'https://greaterfinds.blogspot.com/search/label/denali+ak'],
dillinghamak: ['Dillingham , Alaska', 'https://greaterfinds.blogspot.com/search/label/dillingham+ak'],
fairbanksnorthstarak: ['Fairbanks North Star, Alaska', 'https://greaterfinds.blogspot.com/search/label/fairbanksnorthstar+ak'],
hainesak: ['Haines, Alaska', 'https://greaterfinds.blogspot.com/search/label/haines+ak'],
hoonahangoonak: ['Hoonah-Angoon , Alaska', 'https://greaterfinds.blogspot.com/search/label/hoonahangoon+ak'],
juneauak: ['Juneau, Alaska', 'https://greaterfinds.blogspot.com/search/label/juneau+ak'],
kenaipeninsulaak: ['Kenai Peninsula, Alaska', 'https://greaterfinds.blogspot.com/search/label/kenaipeninsula+ak'],
ketchikangatewayak: ['Ketchikan Gateway, Alaska', 'https://greaterfinds.blogspot.com/search/label/ketchikangateway+ak'],
kodiakislandak: ['Kodiak Island, Alaska', 'https://greaterfinds.blogspot.com/search/label/kodiakisland+ak'],
kusilvakak: ['Kusilvak , Alaska', 'https://greaterfinds.blogspot.com/search/label/kusilvak+ak'],
lakeandpeninsulaak: ['Lake and Peninsula, Alaska', 'https://greaterfinds.blogspot.com/search/label/lakeandpeninsula+ak'],
matanuskasusitnaak: ['Matanuska-Susitna, Alaska', 'https://greaterfinds.blogspot.com/search/label/matanuskasusitna+ak'],
nomeak: ['Nome , Alaska', 'https://greaterfinds.blogspot.com/search/label/nome+ak'],
northslopeak: ['North Slope, Alaska', 'https://greaterfinds.blogspot.com/search/label/northslope+ak'],
northwestarcticak: ['Northwest Arctic, Alaska', 'https://greaterfinds.blogspot.com/search/label/northwestarctic+ak'],
petersburgak: ['Petersburg, Alaska', 'https://greaterfinds.blogspot.com/search/label/petersburg+ak'],
princeofwaleshyderak: ['Prince of Wales-Hyder, Alaska', 'https://greaterfinds.blogspot.com/search/label/princeofwaleshyder+ak'],
sitkaak: ['Sitka, Alaska', 'https://greaterfinds.blogspot.com/search/label/sitka+ak'],
skagwayak: ['Skagway, Alaska', 'https://greaterfinds.blogspot.com/search/label/skagway+ak'],
southeastfairbanksak: ['Southeast Fairbanks , Alaska', 'https://greaterfinds.blogspot.com/search/label/southeastfairbanks+ak'],
valdezcordovaak: ['Valdez-Cordova , Alaska', 'https://greaterfinds.blogspot.com/search/label/valdezcordova+ak'],
wrangellak: ['Wrangell, Alaska', 'https://greaterfinds.blogspot.com/search/label/wrangell+ak'],
yakutatak: ['Yakutat, Alaska', 'https://greaterfinds.blogspot.com/search/label/yakutat+ak'],
yukonkoyukukak: ['Yukon-Koyukuk , Alaska', 'https://greaterfinds.blogspot.com/search/label/yukonkoyukuk+ak'],

// ARIZONA

apacheaz: ['Apache, Arizona', 'https://greaterfinds.blogspot.com/search/label/apache+az'],
cochiseaz: ['Cochise, Arizona', 'https://greaterfinds.blogspot.com/search/label/cochise+az'],
coconinoaz: ['Coconino, Arizona', 'https://greaterfinds.blogspot.com/search/label/coconino+az'],
gilaaz: ['Gila, Arizona', 'https://greaterfinds.blogspot.com/search/label/gila+az'],
grahamaz: ['Graham, Arizona', 'https://greaterfinds.blogspot.com/search/label/graham+az'],
greenleeaz: ['Greenlee, Arizona', 'https://greaterfinds.blogspot.com/search/label/greenlee+az'],
lapazaz: ['La Paz, Arizona', 'https://greaterfinds.blogspot.com/search/label/lapaz+az'],
maricopaaz: ['Maricopa, Arizona', 'https://greaterfinds.blogspot.com/search/label/maricopa+az'],
mohaveaz: ['Mohave, Arizona', 'https://greaterfinds.blogspot.com/search/label/mohave+az'],
navajoaz: ['Navajo, Arizona', 'https://greaterfinds.blogspot.com/search/label/navajo+az'],
pimaaz: ['Pima, Arizona', 'https://greaterfinds.blogspot.com/search/label/pima+az'],
pinalaz: ['Pinal, Arizona', 'https://greaterfinds.blogspot.com/search/label/pinal+az'],
santacruzaz: ['Santa Cruz, Arizona', 'https://greaterfinds.blogspot.com/search/label/santacruz+az'],
yavapaiaz: ['Yavapai, Arizona', 'https://greaterfinds.blogspot.com/search/label/yavapai+az'],
yumaaz: ['Yuma, Arizona', 'https://greaterfinds.blogspot.com/search/label/yuma+az'],

// ARKANSAS


arkansasar: ['Arkansas , Arkansas', 'https://greaterfinds.blogspot.com/search/label/arkansas+ar'],
ashleyar: ['Ashley, Arkansas', 'https://greaterfinds.blogspot.com/search/label/ashley+ar'],
baxterar: ['Baxter, Arkansas', 'https://greaterfinds.blogspot.com/search/label/baxter+ar'],
bentonar: ['Benton, Arkansas', 'https://greaterfinds.blogspot.com/search/label/benton+ar'],
boonear: ['Boone, Arkansas', 'https://greaterfinds.blogspot.com/search/label/boone+ar'],
bradleyar: ['Bradley, Arkansas', 'https://greaterfinds.blogspot.com/search/label/bradley+ar'],
calhounar: ['Calhoun, Arkansas', 'https://greaterfinds.blogspot.com/search/label/calhoun+ar'],
carrollar: ['Carroll, Arkansas', 'https://greaterfinds.blogspot.com/search/label/carroll+ar'],
chicotar: ['Chicot, Arkansas', 'https://greaterfinds.blogspot.com/search/label/chicot+ar'],
clarkar: ['Clark, Arkansas', 'https://greaterfinds.blogspot.com/search/label/clark+ar'],
clayar: ['Clay, Arkansas', 'https://greaterfinds.blogspot.com/search/label/clay+ar'],
cleburnear: ['Cleburne, Arkansas', 'https://greaterfinds.blogspot.com/search/label/cleburne+ar'],
clevelandar: ['Cleveland, Arkansas', 'https://greaterfinds.blogspot.com/search/label/cleveland+ar'],
columbiaar: ['Columbia, Arkansas', 'https://greaterfinds.blogspot.com/search/label/columbia+ar'],
conwayar: ['Conway, Arkansas', 'https://greaterfinds.blogspot.com/search/label/conway+ar'],
craigheadar: ['Craighead, Arkansas', 'https://greaterfinds.blogspot.com/search/label/craighead+ar'],
crawfordar: ['Crawford, Arkansas', 'https://greaterfinds.blogspot.com/search/label/crawford+ar'],
crittendenar: ['Crittenden, Arkansas', 'https://greaterfinds.blogspot.com/search/label/crittenden+ar'],
crossar: ['Cross, Arkansas', 'https://greaterfinds.blogspot.com/search/label/cross+ar'],
dallasar: ['Dallas, Arkansas', 'https://greaterfinds.blogspot.com/search/label/dallas+ar'],
deshaar: ['Desha, Arkansas', 'https://greaterfinds.blogspot.com/search/label/desha+ar'],
drewar: ['Drew, Arkansas', 'https://greaterfinds.blogspot.com/search/label/drew+ar'],
faulknerar: ['Faulkner, Arkansas', 'https://greaterfinds.blogspot.com/search/label/faulkner+ar'],
franklinar: ['Franklin, Arkansas', 'https://greaterfinds.blogspot.com/search/label/franklin+ar'],
fultonar: ['Fulton, Arkansas', 'https://greaterfinds.blogspot.com/search/label/fulton+ar'],
garlandar: ['Garland, Arkansas', 'https://greaterfinds.blogspot.com/search/label/garland+ar'],
grantar: ['Grant, Arkansas', 'https://greaterfinds.blogspot.com/search/label/grant+ar'],
greenear: ['Greene, Arkansas', 'https://greaterfinds.blogspot.com/search/label/greene+ar'],
hempsteadar: ['Hempstead, Arkansas', 'https://greaterfinds.blogspot.com/search/label/hempstead+ar'],
hotspringar: ['Hot Spring, Arkansas', 'https://greaterfinds.blogspot.com/search/label/hotspring+ar'],
howardar: ['Howard, Arkansas', 'https://greaterfinds.blogspot.com/search/label/howard+ar'],
independencear: ['Independence, Arkansas', 'https://greaterfinds.blogspot.com/search/label/independence+ar'],
izardar: ['Izard, Arkansas', 'https://greaterfinds.blogspot.com/search/label/izard+ar'],
jacksonar: ['Jackson, Arkansas', 'https://greaterfinds.blogspot.com/search/label/jackson+ar'],
jeffersonar: ['Jefferson, Arkansas', 'https://greaterfinds.blogspot.com/search/label/jefferson+ar'],
johnsonar: ['Johnson, Arkansas', 'https://greaterfinds.blogspot.com/search/label/johnson+ar'],
lafayettear: ['Lafayette, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lafayette+ar'],
lawrencear: ['Lawrence, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lawrence+ar'],
leear: ['Lee, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lee+ar'],
lincolnar: ['Lincoln, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lincoln+ar'],
littleriverar: ['Little River, Arkansas', 'https://greaterfinds.blogspot.com/search/label/littleriver+ar'],
loganar: ['Logan, Arkansas', 'https://greaterfinds.blogspot.com/search/label/logan+ar'],
lonokear: ['Lonoke, Arkansas', 'https://greaterfinds.blogspot.com/search/label/lonoke+ar'],
madisonar: ['Madison, Arkansas', 'https://greaterfinds.blogspot.com/search/label/madison+ar'],
marionar: ['Marion, Arkansas', 'https://greaterfinds.blogspot.com/search/label/marion+ar'],
millerar: ['Miller, Arkansas', 'https://greaterfinds.blogspot.com/search/label/miller+ar'],
mississippiar: ['Mississippi , Arkansas', 'https://greaterfinds.blogspot.com/search/label/mississippi+ar'],
monroear: ['Monroe, Arkansas', 'https://greaterfinds.blogspot.com/search/label/monroe+ar'],
montgomeryar: ['Montgomery, Arkansas', 'https://greaterfinds.blogspot.com/search/label/montgomery+ar'],
nevadaar: ['Nevada , Arkansas', 'https://greaterfinds.blogspot.com/search/label/nevada+ar'],
newtonar: ['Newton, Arkansas', 'https://greaterfinds.blogspot.com/search/label/newton+ar'],
ouachitaar: ['Ouachita, Arkansas', 'https://greaterfinds.blogspot.com/search/label/ouachita+ar'],
perryar: ['Perry, Arkansas', 'https://greaterfinds.blogspot.com/search/label/perry+ar'],
phillipsar: ['Phillips, Arkansas', 'https://greaterfinds.blogspot.com/search/label/phillips+ar'],
pikear: ['Pike, Arkansas', 'https://greaterfinds.blogspot.com/search/label/pike+ar'],
poinsettar: ['Poinsett, Arkansas', 'https://greaterfinds.blogspot.com/search/label/poinsett+ar'],
polkar: ['Polk, Arkansas', 'https://greaterfinds.blogspot.com/search/label/polk+ar'],
popear: ['Pope, Arkansas', 'https://greaterfinds.blogspot.com/search/label/pope+ar'],
prairiear: ['Prairie, Arkansas', 'https://greaterfinds.blogspot.com/search/label/prairie+ar'],
pulaskiar: ['Pulaski, Arkansas', 'https://greaterfinds.blogspot.com/search/label/pulaski+ar'],
randolphar: ['Randolph, Arkansas', 'https://greaterfinds.blogspot.com/search/label/randolph+ar'],
salinear: ['Saline, Arkansas', 'https://greaterfinds.blogspot.com/search/label/saline+ar'],
scottar: ['Scott, Arkansas', 'https://greaterfinds.blogspot.com/search/label/scott+ar'],
searcyar: ['Searcy, Arkansas', 'https://greaterfinds.blogspot.com/search/label/searcy+ar'],
sebastianar: ['Sebastian, Arkansas', 'https://greaterfinds.blogspot.com/search/label/sebastian+ar'],
sevierar: ['Sevier, Arkansas', 'https://greaterfinds.blogspot.com/search/label/sevier+ar'],
sharpar: ['Sharp, Arkansas', 'https://greaterfinds.blogspot.com/search/label/sharp+ar'],
stfrancisar: ['St. Francis, Arkansas', 'https://greaterfinds.blogspot.com/search/label/stfrancis+ar'],
stonear: ['Stone, Arkansas', 'https://greaterfinds.blogspot.com/search/label/stone+ar'],
unionar: ['Union, Arkansas', 'https://greaterfinds.blogspot.com/search/label/union+ar'],
vanburenar: ['Van Buren, Arkansas', 'https://greaterfinds.blogspot.com/search/label/vanburen+ar'],
washingtonar: ['Washington , Arkansas', 'https://greaterfinds.blogspot.com/search/label/washington+ar'],
whitear: ['White, Arkansas', 'https://greaterfinds.blogspot.com/search/label/white+ar'],
woodruffar: ['Woodruff, Arkansas', 'https://greaterfinds.blogspot.com/search/label/woodruff+ar'],
yellar: ['Yell, Arkansas', 'https://greaterfinds.blogspot.com/search/label/yell+ar'],

// CALIFORNIA

alamedaca: ['Alameda, California', 
'https://greaterfinds.blogspot.com/search/label/alameda+ca'],
alpineca: ['Alpine, California', 'https://greaterfinds.blogspot.com/search/label/alpine+ca'],
amadorca: ['Amador, California', 'https://greaterfinds.blogspot.com/search/label/amador+ca'],
butteca: ['Butte, California', 'https://greaterfinds.blogspot.com/search/label/butte+ca'],
calaverasca: ['Calaveras, California', 'https://greaterfinds.blogspot.com/search/label/calaveras+ca'],
colusaca: ['Colusa, California', 'https://greaterfinds.blogspot.com/search/label/colusa+ca'],
contracostaca: ['Contra Costa, California', 'https://greaterfinds.blogspot.com/search/label/contracosta+ca'],
delnorteca: ['Del Norte, California', 'https://greaterfinds.blogspot.com/search/label/delnorte+ca'],
eldoradoca: ['El Dorado, California', 'https://greaterfinds.blogspot.com/search/label/eldorado+ca'],
fresnoca: ['Fresno, California', 'https://greaterfinds.blogspot.com/search/label/fresno+ca'],
glennca: ['Glenn, California', 'https://greaterfinds.blogspot.com/search/label/glenn+ca'],
humboldtca: ['Humboldt, California', 'https://greaterfinds.blogspot.com/search/label/humboldt+ca'],
imperialca: ['Imperial, California', 'https://greaterfinds.blogspot.com/search/label/imperial+ca'],
inyoca: ['Inyo, California', 'https://greaterfinds.blogspot.com/search/label/inyo+ca'],
kernca: ['Kern, California', 'https://greaterfinds.blogspot.com/search/label/kern+ca'],
kingsca: ['Kings, California', 'https://greaterfinds.blogspot.com/search/label/kings+ca'],
lakeca: ['Lake, California', 'https://greaterfinds.blogspot.com/search/label/lake+ca'],
lassenca: ['Lassen, California', 'https://greaterfinds.blogspot.com/search/label/lassen+ca'],
losangelesca: ['Los Angeles, California', 'https://greaterfinds.blogspot.com/search/label/losangeles+ca'],
maderaca: ['Madera, California', 'https://greaterfinds.blogspot.com/search/label/madera+ca'],
marinca: ['Marin, California', 'https://greaterfinds.blogspot.com/search/label/marin+ca'],
mariposaca: ['Mariposa, California', 'https://greaterfinds.blogspot.com/search/label/mariposa+ca'],
mendocinoca: ['Mendocino, California', 'https://greaterfinds.blogspot.com/search/label/mendocino+ca'],
mercedca: ['Merced, California', 'https://greaterfinds.blogspot.com/search/label/merced+ca'],
modocca: ['Modoc, California', 'https://greaterfinds.blogspot.com/search/label/modoc+ca'],
monoca: ['Mono, California', 'https://greaterfinds.blogspot.com/search/label/mono+ca'],
montereyca: ['Monterey, California', 'https://greaterfinds.blogspot.com/search/label/monterey+ca'],
napaca: ['Napa, California', 'https://greaterfinds.blogspot.com/search/label/napa+ca'],
nevadaca: ['Nevada , California', 'https://greaterfinds.blogspot.com/search/label/nevada+ca'],
orangeca: ['Orange, California', 'https://greaterfinds.blogspot.com/search/label/orange+ca'],
placerca: ['Placer, California', 'https://greaterfinds.blogspot.com/search/label/placer+ca'],
plumasca: ['Plumas, California', 'https://greaterfinds.blogspot.com/search/label/plumas+ca'],
riversideca: ['Riverside, California', 'https://greaterfinds.blogspot.com/search/label/riverside+ca'],
sacramentoca: ['Sacramento, California', 'https://greaterfinds.blogspot.com/search/label/sacramento+ca'],
sanbenitoca: ['San Benito, California', 'https://greaterfinds.blogspot.com/search/label/sanbenito+ca'],
sanbernardinoca: ['San Bernardino, California', 'https://greaterfinds.blogspot.com/search/label/sanbernardino+ca'],
sandiegoca: ['San Diego, California', 'https://greaterfinds.blogspot.com/search/label/sandiego+ca'],
sanfranciscoca: ['San Francisco, California', 'https://greaterfinds.blogspot.com/search/label/sanfrancisco+ca'],
sanjoaquinca: ['San Joaquin, California', 'https://greaterfinds.blogspot.com/search/label/sanjoaquin+ca'],
sanluisobispoca: ['San Luis Obispo, California', 'https://greaterfinds.blogspot.com/search/label/sanluisobispo+ca'],
sanmateoca: ['San Mateo, California', 'https://greaterfinds.blogspot.com/search/label/sanmateo+ca'],
santabarbaraca: ['Santa Barbara, California', 'https://greaterfinds.blogspot.com/search/label/santabarbara+ca'],
santaclaraca: ['Santa Clara, California', 'https://greaterfinds.blogspot.com/search/label/santaclara+ca'],
santacruzca: ['Santa Cruz, California', 'https://greaterfinds.blogspot.com/search/label/santacruz+ca'],
shastaca: ['Shasta, California', 'https://greaterfinds.blogspot.com/search/label/shasta+ca'],
sierraca: ['Sierra, California', 'https://greaterfinds.blogspot.com/search/label/sierra+ca'],
siskiyouca: ['Siskiyou, California', 'https://greaterfinds.blogspot.com/search/label/siskiyou+ca'],
solanoca: ['Solano, California', 'https://greaterfinds.blogspot.com/search/label/solano+ca'],
sonomaca: ['Sonoma, California', 'https://greaterfinds.blogspot.com/search/label/sonoma+ca'],
stanislausca: ['Stanislaus, California', 'https://greaterfinds.blogspot.com/search/label/stanislaus+ca'],
sutterca: ['Sutter, California', 'https://greaterfinds.blogspot.com/search/label/sutter+ca'],
tehamaca: ['Tehama, California', 'https://greaterfinds.blogspot.com/search/label/tehama+ca'],
trinityca: ['Trinity, California', 'https://greaterfinds.blogspot.com/search/label/trinity+ca'],
tulareca: ['Tulare, California', 'https://greaterfinds.blogspot.com/search/label/tulare+ca'],
tuolumneca: ['Tuolumne, California', 'https://greaterfinds.blogspot.com/search/label/tuolumne+ca'],
venturaca: ['Ventura, California', 'https://greaterfinds.blogspot.com/search/label/ventura+ca'],
yoloca: ['Yolo, California', 'https://greaterfinds.blogspot.com/search/label/yolo+ca'],
yubaca: ['Yuba, California', 'https://greaterfinds.blogspot.com/search/label/yuba+ca'],

// COLORADO

adamsco: ['Adams, Colorado', 'https://greaterfinds.blogspot.com/search/label/adams+co'],
alamosaco: ['Alamosa, Colorado', 'https://greaterfinds.blogspot.com/search/label/alamosa+co'],
arapahoeco: ['Arapahoe, Colorado', 'https://greaterfinds.blogspot.com/search/label/arapahoe+co'],
archuletaco: ['Archuleta, Colorado', 'https://greaterfinds.blogspot.com/search/label/archuleta+co'],
bacaco: ['Baca, Colorado', 'https://greaterfinds.blogspot.com/search/label/baca+co'],
bentco: ['Bent, Colorado', 'https://greaterfinds.blogspot.com/search/label/bent+co'],
boulderco: ['Boulder, Colorado', 'https://greaterfinds.blogspot.com/search/label/boulder+co'],
broomfieldco: ['Broomfield, Colorado', 'https://greaterfinds.blogspot.com/search/label/broomfield+co'],
chaffeeco: ['Chaffee, Colorado', 'https://greaterfinds.blogspot.com/search/label/chaffee+co'],
cheyenneco: ['Cheyenne, Colorado', 'https://greaterfinds.blogspot.com/search/label/cheyenne+co'],
clearcreekco: ['Clear Creek, Colorado', 'https://greaterfinds.blogspot.com/search/label/clearcreek+co'],
conejosco: ['Conejos, Colorado', 'https://greaterfinds.blogspot.com/search/label/conejos+co'],
costillaco: ['Costilla, Colorado', 'https://greaterfinds.blogspot.com/search/label/costilla+co'],
crowleyco: ['Crowley, Colorado', 'https://greaterfinds.blogspot.com/search/label/crowley+co'],
custerco: ['Custer, Colorado', 'https://greaterfinds.blogspot.com/search/label/custer+co'],
deltaco: ['Delta, Colorado', 'https://greaterfinds.blogspot.com/search/label/delta+co'],
denverco: ['Denver, Colorado', 'https://greaterfinds.blogspot.com/search/label/denver+co'],
doloresco: ['Dolores, Colorado', 'https://greaterfinds.blogspot.com/search/label/dolores+co'],
douglasco: ['Douglas, Colorado', 'https://greaterfinds.blogspot.com/search/label/douglas+co'],
eagleco: ['Eagle, Colorado', 'https://greaterfinds.blogspot.com/search/label/eagle+co'],
elpasoco: ['El Paso, Colorado', 'https://greaterfinds.blogspot.com/search/label/elpaso+co'],
elbertco: ['Elbert, Colorado', 'https://greaterfinds.blogspot.com/search/label/elbert+co'],
fremontco: ['Fremont, Colorado', 'https://greaterfinds.blogspot.com/search/label/fremont+co'],
garfieldco: ['Garfield, Colorado', 'https://greaterfinds.blogspot.com/search/label/garfield+co'],
gilpinco: ['Gilpin, Colorado', 'https://greaterfinds.blogspot.com/search/label/gilpin+co'],
grandco: ['Grand, Colorado', 'https://greaterfinds.blogspot.com/search/label/grand+co'],
gunnisonco: ['Gunnison, Colorado', 'https://greaterfinds.blogspot.com/search/label/gunnison+co'],
hinsdaleco: ['Hinsdale, Colorado', 'https://greaterfinds.blogspot.com/search/label/hinsdale+co'],
huerfanoco: ['Huerfano, Colorado', 'https://greaterfinds.blogspot.com/search/label/huerfano+co'],
jacksonco: ['Jackson, Colorado', 'https://greaterfinds.blogspot.com/search/label/jackson+co'],
jeffersonco: ['Jefferson, Colorado', 'https://greaterfinds.blogspot.com/search/label/jefferson+co'],
kiowaco: ['Kiowa, Colorado', 'https://greaterfinds.blogspot.com/search/label/kiowa+co'],
kitcarsonco: ['Kit Carson, Colorado', 'https://greaterfinds.blogspot.com/search/label/kitcarson+co'],
laplataco: ['La Plata, Colorado', 'https://greaterfinds.blogspot.com/search/label/laplata+co'],
lakeco: ['Lake, Colorado', 'https://greaterfinds.blogspot.com/search/label/lake+co'],
larimerco: ['Larimer, Colorado', 'https://greaterfinds.blogspot.com/search/label/larimer+co'],
lasanimasco: ['Las Animas, Colorado', 'https://greaterfinds.blogspot.com/search/label/lasanimas+co'],
lincolnco: ['Lincoln, Colorado', 'https://greaterfinds.blogspot.com/search/label/lincoln+co'],
loganco: ['Logan, Colorado', 'https://greaterfinds.blogspot.com/search/label/logan+co'],
mesaco: ['Mesa, Colorado', 'https://greaterfinds.blogspot.com/search/label/mesa+co'],
mineralco: ['Mineral, Colorado', 'https://greaterfinds.blogspot.com/search/label/mineral+co'],
moffatco: ['Moffat, Colorado', 'https://greaterfinds.blogspot.com/search/label/moffat+co'],
montezumaco: ['Montezuma, Colorado', 'https://greaterfinds.blogspot.com/search/label/montezuma+co'],
montroseco: ['Montrose, Colorado', 'https://greaterfinds.blogspot.com/search/label/montrose+co'],
morganco: ['Morgan, Colorado', 'https://greaterfinds.blogspot.com/search/label/morgan+co'],
oteroco: ['Otero, Colorado', 'https://greaterfinds.blogspot.com/search/label/otero+co'],
ourayco: ['Ouray, Colorado', 'https://greaterfinds.blogspot.com/search/label/ouray+co'],
parkco: ['Park, Colorado', 'https://greaterfinds.blogspot.com/search/label/park+co'],
phillipsco: ['Phillips, Colorado', 'https://greaterfinds.blogspot.com/search/label/phillips+co'],
pitkinco: ['Pitkin, Colorado', 'https://greaterfinds.blogspot.com/search/label/pitkin+co'],
prowersco: ['Prowers, Colorado', 'https://greaterfinds.blogspot.com/search/label/prowers+co'],
puebloco: ['Pueblo, Colorado', 'https://greaterfinds.blogspot.com/search/label/pueblo+co'],
rioblancoco: ['Rio Blanco, Colorado', 'https://greaterfinds.blogspot.com/search/label/rioblanco+co'],
riograndeco: ['Rio Grande, Colorado', 'https://greaterfinds.blogspot.com/search/label/riogrande+co'],
routtco: ['Routt, Colorado', 'https://greaterfinds.blogspot.com/search/label/routt+co'],
saguacheco: ['Saguache, Colorado', 'https://greaterfinds.blogspot.com/search/label/saguache+co'],
sanjuanco: ['San Juan, Colorado', 'https://greaterfinds.blogspot.com/search/label/sanjuan+co'],
sanmiguelco: ['San Miguel, Colorado', 'https://greaterfinds.blogspot.com/search/label/sanmiguel+co'],
sedgwickco: ['Sedgwick, Colorado', 'https://greaterfinds.blogspot.com/search/label/sedgwick+co'],
summitco: ['Summit, Colorado', 'https://greaterfinds.blogspot.com/search/label/summit+co'],
tellerco: ['Teller, Colorado', 'https://greaterfinds.blogspot.com/search/label/teller+co'],
washingtonco: ['Washington , Colorado', 'https://greaterfinds.blogspot.com/search/label/washington+co'],
weldco: ['Weld, Colorado', 'https://greaterfinds.blogspot.com/search/label/weld+co'],
yumaco: ['Yuma, Colorado', 'https://greaterfinds.blogspot.com/search/label/yuma+co'],
fairfieldct: ['Fairfield, Connecticut', 'https://greaterfinds.blogspot.com/search/label/fairfield+ct'],
hartfordct: ['Hartford, Connecticut', 'https://greaterfinds.blogspot.com/search/label/hartford+ct'],
litchfieldct: ['Litchfield, Connecticut', 'https://greaterfinds.blogspot.com/search/label/litchfield+ct'],
middlesexct: ['Middlesex, Connecticut', 'https://greaterfinds.blogspot.com/search/label/middlesex+ct'],
newhavenct: ['New Haven, Connecticut', 'https://greaterfinds.blogspot.com/search/label/newhaven+ct'],
newlondonct: ['New London, Connecticut', 'https://greaterfinds.blogspot.com/search/label/newlondon+ct'],
tollandct: ['Tolland, Connecticut', 'https://greaterfinds.blogspot.com/search/label/tolland+ct'],
windhamct: ['Windham, Connecticut', 'https://greaterfinds.blogspot.com/search/label/windham+ct'],

// DELAWARE

kentde: ['Kent, Delaware', 'https://greaterfinds.blogspot.com/search/label/kent+de'],
newcastlede: ['New Castle, Delaware', 'https://greaterfinds.blogspot.com/search/label/newcastle+de'],
sussexde: ['Sussex, Delaware', 'https://greaterfinds.blogspot.com/search/label/sussex+de'],

// DC

washingtondc: ['Washington, District of Columbia', 'https://greaterfinds.blogspot.com/search/label/washington+dc'],

// FLORIDA

alachuafl: ['Alachua, Florida', 'https://greaterfinds.blogspot.com/search/label/alachua+fl'],
bakerfl: ['Baker, Florida', 'https://greaterfinds.blogspot.com/search/label/baker+fl'],
bayfl: ['Bay, Florida', 'https://greaterfinds.blogspot.com/search/label/bay+fl'],
bradfordfl: ['Bradford, Florida', 'https://greaterfinds.blogspot.com/search/label/bradford+fl'],
brevardfl: ['Brevard, Florida',  'https://greaterfinds.blogspot.com/search/label/brevard+fl'],
browardfl: ['Broward, Florida',  'https://greaterfinds.blogspot.com/search/label/broward+fl'],
calhounfl: ['Calhoun, Florida',  'https://greaterfinds.blogspot.com/search/label/calhoun+fl'],
charlottefl: ['Charlotte, Florida',  'https://greaterfinds.blogspot.com/search/label/charlotte+fl'],
citrusfl: ['Citrus, Florida', 'https://greaterfinds.blogspot.com/search/label/citrus+fl'],
clayfl: ['Clay, Florida', 'https://greaterfinds.blogspot.com/search/label/clay+fl'],
collierfl: ['Collier, Florida',  'https://greaterfinds.blogspot.com/search/label/collier+fl'],
columbiafl: ['Columbia, Florida',  'https://greaterfinds.blogspot.com/search/label/columbia+fl'],
desotofl: ['DeSoto, Florida',  'https://greaterfinds.blogspot.com/search/label/desoto+fl'],
dixiefl: ['Dixie, Florida', 'https://greaterfinds.blogspot.com/search/label/dixie+fl'],
duvalfl: ['Duval, Florida', 'https://greaterfinds.blogspot.com/search/label/duval+fl'],
escambiafl: ['Escambia, Florida',  'https://greaterfinds.blogspot.com/search/label/escambia+fl'],
flaglerfl: ['Flagler, Florida',  'https://greaterfinds.blogspot.com/search/label/flagler+fl'],
franklinfl: ['Franklin, Florida',  'https://greaterfinds.blogspot.com/search/label/franklin+fl'],
gadsdenfl: ['Gadsden, Florida',  'https://greaterfinds.blogspot.com/search/label/gadsden+fl'],
gilchristfl: ['Gilchrist, Florida',  'https://greaterfinds.blogspot.com/search/label/gilchrist+fl'],
gladesfl: ['Glades, Florida',  'https://greaterfinds.blogspot.com/search/label/glades+fl'],
gulffl: ['Gulf, Florida', 'https://greaterfinds.blogspot.com/search/label/gulf+fl'],
hamiltonfl: ['Hamilton, Florida',  'https://greaterfinds.blogspot.com/search/label/hamilton+fl'],
hardeefl: ['Hardee, Florida',  'https://greaterfinds.blogspot.com/search/label/hardee+fl'],
hendryfl: ['Hendry, Florida',  'https://greaterfinds.blogspot.com/search/label/hendry+fl'],
hernandofl: ['Hernando, Florida',  'https://greaterfinds.blogspot.com/search/label/hernando+fl'],
highlandsfl: ['Highlands, Florida',  'https://greaterfinds.blogspot.com/search/label/highlands+fl'],
hillsboroughfl: ['Hillsborough, Florida',  'https://greaterfinds.blogspot.com/search/label/hillsborough+fl'],
holmesfl: ['Holmes, Florida',  'https://greaterfinds.blogspot.com/search/label/holmes+fl'],
indianriverfl: ['Indian River, Florida',  'https://greaterfinds.blogspot.com/search/label/indianriver+fl'],
jacksonfl: ['Jackson, Florida',  'https://greaterfinds.blogspot.com/search/label/jackson+fl'],
jeffersonfl: ['Jefferson, Florida',  'https://greaterfinds.blogspot.com/search/label/jefferson+fl'],
lafayettefl: ['Lafayette, Florida',  'https://greaterfinds.blogspot.com/search/label/lafayette+fl'],
lakefl: ['Lake, Florida', 'https://greaterfinds.blogspot.com/search/label/lake+fl'],
leefl: ['Lee, Florida',  'https://greaterfinds.blogspot.com/search/label/lee+fl'],
leonfl: ['Leon, Florida', 'https://greaterfinds.blogspot.com/search/label/leon+fl'],
levyfl: ['Levy, Florida',  'https://greaterfinds.blogspot.com/search/label/levy+fl'],
libertyfl: ['Liberty, Florida',  'https://greaterfinds.blogspot.com/search/label/liberty+fl'],
madisonfl: ['Madison, Florida',  'https://greaterfinds.blogspot.com/search/label/madison+fl'],
manateefl: ['Manatee, Florida',  'https://greaterfinds.blogspot.com/search/label/manatee+fl'],
marionfl: ['Marion, Florida',  'https://greaterfinds.blogspot.com/search/label/marion+fl'],
martinfl: ['Martin, Florida',  'https://'''greaterfinds.blogspot.com/search/label/martin+fl'],
miamidadefl: ['Miami-Dade, Florida', 'https://greaterfinds.blogspot.com/search/label/miamidade+fl'],
monroefl: ['Monroe, Florida', 'https://greaterfinds.blogspot.com/search/label/monroe+fl'],
nassaufl: ['Nassau, Florida', 'https://greaterfinds.blogspot.com/search/label/nassau+fl'],
okaloosafl: ['Okaloosa, Florida', 'https://greaterfinds.blogspot.com/search/label/okaloosa+fl'],
okeechobeefl: ['Okeechobee, Florida', 'https://greaterfinds.blogspot.com/search/label/okeechobee+fl'],
orangefl: ['Orange, Florida', 'https://greaterfinds.blogspot.com/search/label/orange+fl'],
osceolafl: ['Osceola, Florida', 'https://greaterfinds.blogspot.com/search/label/osceola+fl'],
palmbeachfl: ['Palm Beach, Florida', 'https://greaterfinds.blogspot.com/search/label/palmbeach+fl'],
pascofl: ['Pasco, Florida', 'https://greaterfinds.blogspot.com/search/label/pasco+fl'],
pinellasfl: ['Pinellas, Florida', 'https://greaterfinds.blogspot.com/search/label/pinellas+fl'],
polkfl: ['Polk, Florida', 'https://greaterfinds.blogspot.com/search/label/polk+fl'],
putnamfl: ['Putnam, Florida', 'https://greaterfinds.blogspot.com/search/label/putnam+fl'],
santarosafl: ['Santa Rosa, Florida', 'https://greaterfinds.blogspot.com/search/label/santarosa+fl'],
sarasotafl: ['Sarasota, Florida', 'https://greaterfinds.blogspot.com/search/label/sarasota+fl'],
seminolefl: ['Seminole, Florida', 'https://greaterfinds.blogspot.com/search/label/seminole+fl'],
stjohnsfl: ['St. Johns, Florida', 'https://greaterfinds.blogspot.com/search/label/stjohns+fl'],
stluciefl: ['St. Lucie, Florida', 'https://greaterfinds.blogspot.com/search/label/stlucie+fl'],
sumterfl: ['Sumter, Florida', 'https://greaterfinds.blogspot.com/search/label/sumter+fl'],
suwanneefl: ['Suwannee, Florida', 'https://greaterfinds.blogspot.com/search/label/suwannee+fl'],
taylorfl: ['Taylor, Florida', 'https://greaterfinds.blogspot.com/search/label/taylor+fl'],
unionfl: ['Union, Florida', 'https://greaterfinds.blogspot.com/search/label/union+fl'],
volusiafl: ['Volusia, Florida', 'https://greaterfinds.blogspot.com/search/label/volusia+fl'],
wakullafl: ['Wakulla, Florida', 'https://greaterfinds.blogspot.com/search/label/wakulla+fl'],
waltonfl: ['Walton, Florida', 'https://greaterfinds.blogspot.com/search/label/walton+fl'],
washingtonfl: ['Washington , Florida', 'https://greaterfinds.blogspot.com/search/label/washington+fl'],



}