var namesLookup = {

// Counties

"acadiaparish": function() {return "Acadia Parish";},
"aleutianseastborough": function() {return "Aleutians East Borough";},
"aleutianswestcensusarea": function() {return "Aleutians West Census Area";},
"allenparish": function() {return "Allen Parish";},
"annearundelcounty": function() {return "Anne Arundel County";},
"ascensionparish": function() {return "Ascension Parish";},
"assumptionparish": function() {return "Assumption Parish";},
"avoyellesparish": function() {return "Avoyelles Parish";},
"bearlakecounty": function() {return "Bear Lake County";},
"beauregardparish": function() {return "Beauregard Parish";},
"benhillcounty": function() {return "Ben Hill County";},
"bethelcensusarea": function() {return "Bethel Census Area";},
"bienvilleparish": function() {return "Bienville Parish";},
"bighorncounty": function() {return "Big Horn County";},
"bigstonecounty": function() {return "Big Stone County";},
"blackhawkcounty": function() {return "Black Hawk County";},
"blueearthcounty": function() {return "Blue Earth County";},
"bonhommecounty": function() {return "Bon Homme County";},
"bossierparish": function() {return "Bossier Parish";},
"boxbuttecounty": function() {return "Box Butte County";},
"boxeldercounty": function() {return "Box Elder County";},
"bristolbayborough": function() {return "Bristol Bay Borough";},
"buenavistacounty": function() {return "Buena Vista County";},
"caddoparish": function() {return "Caddo Parish";},
"calcasieuparish": function() {return "Calcasieu Parish";},
"caldwellparish": function() {return "Caldwell Parish";},
"cameronparish": function() {return "Cameron Parish";},
"capegirardeaucounty": function() {return "Cape Girardeau County";},
"capemaycounty": function() {return "Cape May County";},
"catahoulaparish": function() {return "Catahoula Parish";},
"cerrogordocounty": function() {return "Cerro Gordo County";},
"charlescitycounty": function() {return "Charles City County";},
"charlesmixcounty": function() {return "Charles Mix County";},
"claiborneparish": function() {return "Claiborne Parish";},
"clearcreekcounty": function() {return "Clear Creek County";},
"concordiaparish": function() {return "Concordia Parish";},
"contracostacounty": function() {return "Contra Costa County";},
"crowwingcounty": function() {return "Crow Wing County";},
"debacacounty": function() {return "De Baca County";},
"desotoparish": function() {return "De Soto Parish";},
"dewittcounty": function() {return "De Witt County";},
"deafsmithcounty": function() {return "Deaf Smith County";},
"deerlodgecounty": function() {return "Deer Lodge County";},
"delnortecounty": function() {return "Del Norte County";},
"denaliborough": function() {return "Denali Borough";},
"desmoinescounty": function() {return "Des Moines County";},
"dillinghamcensusarea": function() {return "Dillingham Census Area";},
"districtofcolumbia": function() {return "District of Columbia";},
"donaanacounty": function() {return "Doña Ana County";},
"eastbatonrougeparish": function() {return "East Baton Rouge Parish";},
"eastcarrollparish": function() {return "East Carroll Parish";},
"eastfelicianaparish": function() {return "East Feliciana Parish";},
"eauclairecounty": function() {return "Eau Claire County";},
"eldoradocounty": function() {return "El Dorado County";},
"elpasocounty": function() {return "El Paso County";},
"evangelineparish": function() {return "Evangeline Parish";},
"fairbanksnorthstarborough": function() {return "Fairbanks North Star Borough";},
"fallrivercounty": function() {return "Fall River County";},
"fonddulaccounty": function() {return "Fond du Lac County";},
"fortbendcounty": function() {return "Fort Bend County";},
"franklinparish": function() {return "Franklin Parish";},
"goldenvalleycounty": function() {return "Golden Valley County";},
"grandforkscounty": function() {return "Grand Forks County";},
"grandislecounty": function() {return "Grand Isle County";},
"grandtraversecounty": function() {return "Grand Traverse County";},
"grantparish": function() {return "Grant Parish";},
"graysharborcounty": function() {return "Grays Harbor County";},
"greenlakecounty": function() {return "Green Lake County";},
"hainesborough": function() {return "Haines Borough";},
"hoodrivercounty": function() {return "Hood River County";},
"hoonahangooncensusarea": function() {return "Hoonah-Angoon Census Area";},
"hotspringcounty": function() {return "Hot Spring County";},
"hotspringscounty": function() {return "Hot Springs County";},
"iberiaparish": function() {return "Iberia Parish";},
"ibervilleparish": function() {return "Iberville Parish";},
"indianrivercounty": function() {return "Indian River County";},
"isleofwightcounty": function() {return "Isle of Wight County";},
"jacksonparish": function() {return "Jackson Parish";},
"jamescitycounty": function() {return "James City County";},
"jeffdaviscounty": function() {return "Jeff Davis County";},
"jeffersondaviscounty": function() {return "Jefferson Davis County";},
"jeffersondavisparish": function() {return "Jefferson Davis Parish";},
"jeffersonparish": function() {return "Jefferson Parish";},
"jimhoggcounty": function() {return "Jim Hogg County";},
"jimwellscounty": function() {return "Jim Wells County";},
"jodaviesscounty": function() {return "Jo Daviess County";},
"judithbasincounty": function() {return "Judith Basin County";},
"kenaipeninsulaborough": function() {return "Kenai Peninsula Borough";},
"ketchikangatewayborough": function() {return "Ketchikan Gateway Borough";},
"keyapahacounty": function() {return "Keya Paha County";},
"kingandqueencounty": function() {return "King and Queen County";},
"kinggeorgecounty": function() {return "King George County";},
"kingwilliamcounty": function() {return "King William County";},
"kitcarsoncounty": function() {return "Kit Carson County";},
"kodiakislandborough": function() {return "Kodiak Island Borough";},
"kusilvakcensusarea": function() {return "Kusilvak Census Area";},
"lacrossecounty": function() {return "La Crosse County";},
"lapazcounty": function() {return "La Paz County";},
"laplatacounty": function() {return "La Plata County";},
"lasallecounty": function() {return "La Salle County";},
"lacquiparlecounty": function() {return "Lac qui Parle County";},
"lafayetteparish": function() {return "Lafayette Parish";},
"lafourcheparish": function() {return "Lafourche Parish";},
"lakeandpeninsulaborough": function() {return "Lake and Peninsula Borough";},
"lakeofthewoodscounty": function() {return "Lake of the Woods County";},
"lasanimascounty": function() {return "Las Animas County";},
"lasalleparish": function() {return "LaSalle Parish";},
"leflorecounty": function() {return "Le Flore County";},
"lesueurcounty": function() {return "Le Sueur County";},
"lewisandclarkcounty": function() {return "Lewis and Clark County";},
"lincolnparish": function() {return "Lincoln Parish";},
"littlerivercounty": function() {return "Little River County";},
"liveoakcounty": function() {return "Live Oak County";},
"livingstonparish": function() {return "Livingston Parish";},
"losalamoscounty": function() {return "Los Alamos County";},
"losangelescounty": function() {return "Los Angeles County";},
"madisonparish": function() {return "Madison Parish";},
"matanuskasusitnaborough": function() {return "Matanuska-Susitna Borough";},
"millelacscounty": function() {return "Mille Lacs County";},
"morehouseparish": function() {return "Morehouse Parish";},
"natchitochesparish": function() {return "Natchitoches Parish";},
"newcastlecounty": function() {return "New Castle County";},
"newhanovercounty": function() {return "New Hanover County";},
"newhavencounty": function() {return "New Haven County";},
"newkentcounty": function() {return "New Kent County";},
"newlondoncounty": function() {return "New London County";},
"newmadridcounty": function() {return "New Madrid County";},
"newyorkcounty": function() {return "New York County";},
"nezpercecounty": function() {return "Nez Perce County";},
"nomecensusarea": function() {return "Nome Census Area";},
"northslopeborough": function() {return "North Slope Borough";},
"northwestarcticborough": function() {return "Northwest Arctic Borough";},
"oglalalakotacounty": function() {return "Oglala Lakota County";},
"orleansparish": function() {return "Orleans Parish";},
"ottertailcounty": function() {return "Otter Tail County";},
"ouachitaparish": function() {return "Ouachita Parish";},
"palmbeachcounty": function() {return "Palm Beach County";},
"paloaltocounty": function() {return "Palo Alto County";},
"palopintocounty": function() {return "Palo Pinto County";},
"pearlrivercounty": function() {return "Pearl River County";},
"pendoreillecounty": function() {return "Pend Oreille County";},
"petersburgborough": function() {return "Petersburg Borough";},
"plaqueminesparish": function() {return "Plaquemines Parish";},
"pointecoupeeparish": function() {return "Pointe Coupee Parish";},
"powderrivercounty": function() {return "Powder River County";},
"presqueislecounty": function() {return "Presque Isle County";},
"princeedwardcounty": function() {return "Prince Edward County";},
"princegeorgecounty": function() {return "Prince George County";},
"princegeorgescounty": function() {return "Prince George's County";},
"princeofwaleshydercensusarea": function() {return "Prince of Wales-Hyder Census Area";},
"princewilliamcounty": function() {return "Prince William County";},
"queenannescounty": function() {return "Queen Anne's County";},
"rapidesparish": function() {return "Rapides Parish";},
"redlakecounty": function() {return "Red Lake County";},
"redrivercounty": function() {return "Red River County";},
"redriverparish": function() {return "Red River Parish";},
"redwillowcounty": function() {return "Red Willow County";},
"richlandparish": function() {return "Richland Parish";},
"rioarribacounty": function() {return "Rio Arriba County";},
"rioblancocounty": function() {return "Rio Blanco County";},
"riograndecounty": function() {return "Rio Grande County";},
"rockislandcounty": function() {return "Rock Island County";},
"rogermillscounty": function() {return "Roger Mills County";},
"sabineparish": function() {return "Sabine Parish";},
"saltlakecounty": function() {return "Salt Lake County";},
"sanaugustinecounty": function() {return "San Augustine County";},
"sanbenitocounty": function() {return "San Benito County";},
"sanbernardinocounty": function() {return "San Bernardino County";},
"sandiegocounty": function() {return "San Diego County";},
"sanfranciscocounty": function() {return "San Francisco County";},
"sanjacintocounty": function() {return "San Jacinto County";},
"sanjoaquincounty": function() {return "San Joaquin County";},
"sanjuancounty": function() {return "San Juan County";},
"sanluisobispocounty": function() {return "San Luis Obispo County";},
"sanmateocounty": function() {return "San Mateo County";},
"sanmiguelcounty": function() {return "San Miguel County";},
"sanpatriciocounty": function() {return "San Patricio County";},
"sansabacounty": function() {return "San Saba County";},
"santabarbaracounty": function() {return "Santa Barbara County";},
"santaclaracounty": function() {return "Santa Clara County";},
"santacruzcounty": function() {return "Santa Cruz County";},
"santafecounty": function() {return "Santa Fe County";},
"santarosacounty": function() {return "Santa Rosa County";},
"scottsbluffcounty": function() {return "Scotts Bluff County";},
"silverbowcounty": function() {return "Silver Bow County";},
"southeastfairbankscensusarea": function() {return "Southeast Fairbanks Census Area";},
"stbernardparish": function() {return "St. Bernard Parish";},
"stcharlescounty": function() {return "St. Charles County";},
"stcharlesparish": function() {return "St. Charles Parish";},
"stclaircounty": function() {return "St. Clair County";},
"stcroixcounty": function() {return "St. Croix County";},
"stfranciscounty": function() {return "St. Francis County";},
"stfrancoiscounty": function() {return "St. Francois County";},
"sthelenaparish": function() {return "St. Helena Parish";},
"stjamesparish": function() {return "St. James Parish";},
"stjohnthebaptistparish": function() {return "St. John the Baptist Parish";},
"stjohnscounty": function() {return "St. Johns County";},
"stjosephcounty": function() {return "St. Joseph County";},
"stlandryparish": function() {return "St. Landry Parish";},
"stlawrencecounty": function() {return "St. Lawrence County";},
"stlouiscounty": function() {return "St. Louis County";},
"stluciecounty": function() {return "St. Lucie County";},
"stmartinparish": function() {return "St. Martin Parish";},
"stmaryparish": function() {return "St. Mary Parish";},
"stmaryscounty": function() {return "St. Mary's County";},
"sttammanyparish": function() {return "St. Tammany Parish";},
"stegenevievecounty": function() {return "Ste. Genevieve County";},
"sweetgrasscounty": function() {return "Sweet Grass County";},
"tangipahoaparish": function() {return "Tangipahoa Parish";},
"tensasparish": function() {return "Tensas Parish";},
"terrebonneparish": function() {return "Terrebonne Parish";},
"tomgreencounty": function() {return "Tom Green County";},
"twinfallscounty": function() {return "Twin Falls County";},
"unionparish": function() {return "Union Parish";},
"valverdecounty": function() {return "Val Verde County";},
"valdezcordovacensusarea": function() {return "Valdez-Cordova Census Area";},
"vanburencounty": function() {return "Van Buren County";},
"vanwertcounty": function() {return "Van Wert County";},
"vanzandtcounty": function() {return "Van Zandt County";},
"vermilionparish": function() {return "Vermilion Parish";},
"vernonparish": function() {return "Vernon Parish";},
"wallawallacounty": function() {return "Walla Walla County";},
"washingtonparish": function() {return "Washington Parish";},
"websterparish": function() {return "Webster Parish";},
"westbatonrougeparish": function() {return "West Baton Rouge Parish";},
"westcarrollparish": function() {return "West Carroll Parish";},
"westfelicianaparish": function() {return "West Feliciana Parish";},
"whitepinecounty": function() {return "White Pine County";},
"winnparish": function() {return "Winn Parish";},
"yellowmedicinecounty": function() {return "Yellow Medicine County";},
"yukonkoyukukcensusarea": function() {return "Yukon-Koyukuk Census Area";},

// Cities

"agawamtown": function() {return "Agawam Town";},
"agourahills": function() {return "Agoura Hills";},
"airwayheights": function() {return "Airway Heights";},
"alamoheights": function() {return "Alamo Heights";},
"albertlea": function() {return "Albert Lea";},
"alexandercity": function() {return "Alexander City";},
"alisoviejo": function() {return "Aliso Viejo";},
"allenpark": function() {return "Allen Park";},
"altamontesprings": function() {return "Altamonte Springs";},
"americancanyon": function() {return "American Canyon";},
"americanfork": function() {return "American Fork";},
"amesburytown": function() {return "Amesbury Town";},
"annarbor": function() {return "Ann Arbor";},
"apachejunction": function() {return "Apache Junction";},
"applevalley": function() {return "Apple Valley";},
"aransaspass": function() {return "Aransas Pass";},
"ardenhills": function() {return "Arden Hills";},
"arkansascity": function() {return "Arkansas City";},
"arlingtonheights": function() {return "Arlington Heights";},
"arroyogrande": function() {return "Arroyo Grande";},
"asburypark": function() {return "Asbury Park";},
"atlanticbeach": function() {return "Atlantic Beach";},
"atlanticcity": function() {return "Atlantic City";},
"auburnhills": function() {return "Auburn Hills";},
"avonlake": function() {return "Avon Lake";},
"avonpark": function() {return "Avon Park";},
"bainbridgeisland": function() {return "Bainbridge Island";},
"bakercity": function() {return "Baker City";},
"balchsprings": function() {return "Balch Springs";},
"baldwinpark": function() {return "Baldwin Park";},
"ballstonspa": function() {return "Ballston Spa";},
"barnstabletown": function() {return "Barnstable Town";},
"batonrouge": function() {return "Baton Rouge";},
"battlecreek": function() {return "Battle Creek";},
"battleground": function() {return "Battle Ground";},
"baycity": function() {return "Bay City";},
"bayharborislands": function() {return "Bay Harbor Islands";},
"bayminette": function() {return "Bay Minette";},
"baystlouis": function() {return "Bay St. Louis";},
"bayvillage": function() {return "Bay Village";},
"beachpark": function() {return "Beach Park";},
"beaverdam": function() {return "Beaver Dam";},
"beaverfalls": function() {return "Beaver Falls";},
"bedfordheights": function() {return "Bedford Heights";},
"beecave": function() {return "Bee Cave";},
"beechgrove": function() {return "Beech Grove";},
"belair": function() {return "Bel Air";},
"belaire": function() {return "Bel Aire";},
"bellgardens": function() {return "Bell Gardens";},
"bellavista": function() {return "Bella Vista";},
"bellefourche": function() {return "Belle Fourche";},
"belleglade": function() {return "Belle Glade";},
"belleisle": function() {return "Belle Isle";},
"belleplaine": function() {return "Belle Plaine";},
"bellefontaineneighbors": function() {return "Bellefontaine Neighbors";},
"bentonharbor": function() {return "Benton Harbor";},
"bessemercity": function() {return "Bessemer City";},
"bethelpark": function() {return "Bethel Park";},
"beverlyhills": function() {return "Beverly Hills";},
"bigbearlake": function() {return "Big Bear Lake";},
"biglake": function() {return "Big Lake";},
"bigrapids": function() {return "Big Rapids";},
"bigspring": function() {return "Big Spring";},
"bigstonegap": function() {return "Big Stone Gap";},
"blackjack": function() {return "Black Jack";},
"blackmountain": function() {return "Black Mountain";},
"blueash": function() {return "Blue Ash";},
"blueisland": function() {return "Blue Island";},
"bluesprings": function() {return "Blue Springs";},
"bocaraton": function() {return "Boca Raton";},
"boilingspringlakes": function() {return "Boiling Spring Lakes";},
"boisecity": function() {return "Boise City";},
"bonitasprings": function() {return "Bonita Springs";},
"bonneterre": function() {return "Bonne Terre";},
"bonnersprings": function() {return "Bonner Springs";},
"bonneylake": function() {return "Bonney Lake";},
"bossiercity": function() {return "Bossier City";},
"bouldercity": function() {return "Boulder City";},
"boundbrook": function() {return "Bound Brook";},
"bowlinggreen": function() {return "Bowling Green";},
"boxelder": function() {return "Box Elder";},
"boyntonbeach": function() {return "Boynton Beach";},
"braintreetown": function() {return "Braintree Town";},
"breauxbridge": function() {return "Breaux Bridge";},
"briarcliffmanor": function() {return "Briarcliff Manor";},
"bridgecity": function() {return "Bridge City";},
"brighamcity": function() {return "Brigham City";},
"broadviewheights": function() {return "Broadview Heights";},
"brokenarrow": function() {return "Broken Arrow";},
"brookpark": function() {return "Brook Park";},
"brooklyncenter": function() {return "Brooklyn Center";},
"brooklynpark": function() {return "Brooklyn Park";},
"browndeer": function() {return "Brown Deer";},
"buenapark": function() {return "Buena Park";},
"buenavista": function() {return "Buena Vista";},
"buffalogrove": function() {return "Buffalo Grove";},
"bullheadcity": function() {return "Bullhead City";},
"burrridge": function() {return "Burr Ridge";},
"buttesilverbow": function() {return "Butte-Silver Bow";},
"californiacity": function() {return "California City";},
"calumetcity": function() {return "Calumet City";},
"calumetpark": function() {return "Calumet Park";},
"camphill": function() {return "Camp Hill";},
"campverde": function() {return "Camp Verde";},
"camptonhills": function() {return "Campton Hills";},
"canalfulton": function() {return "Canal Fulton";},
"canalwinchester": function() {return "Canal Winchester";},
"canyonlake": function() {return "Canyon Lake";},
"capecanaveral": function() {return "Cape Canaveral";},
"capecoral": function() {return "Cape Coral";},
"capegirardeau": function() {return "Cape Girardeau";},
"carljunction": function() {return "Carl Junction";},
"carolstream": function() {return "Carol Stream";},
"carolinabeach": function() {return "Carolina Beach";},
"carrizosprings": function() {return "Carrizo Springs";},
"carsoncity": function() {return "Carson City";},
"casagrande": function() {return "Casa Grande";},
"castlepines": function() {return "Castle Pines";},
"castlerock": function() {return "Castle Rock";},
"castleshannon": function() {return "Castle Shannon";},
"cathedralcity": function() {return "Cathedral City";},
"cavecreek": function() {return "Cave Creek";},
"cedarcity": function() {return "Cedar City";},
"cedarfalls": function() {return "Cedar Falls";},
"cedarhill": function() {return "Cedar Hill";},
"cedarhills": function() {return "Cedar Hills";},
"cedarlake": function() {return "Cedar Lake";},
"cedarpark": function() {return "Cedar Park";},
"cedarrapids": function() {return "Cedar Rapids";},
"centerline": function() {return "Center Line";},
"centerpoint": function() {return "Center Point";},
"centralcity": function() {return "Central City";},
"centralfalls": function() {return "Central Falls";},
"centralpoint": function() {return "Central Point";},
"chapelhill": function() {return "Chapel Hill";},
"charlescity": function() {return "Charles City";},
"charlestown": function() {return "Charles Town";},
"cherryhillsvillage": function() {return "Cherry Hills Village";},
"chesapeakebeach": function() {return "Chesapeake Beach";},
"chestnutridge": function() {return "Chestnut Ridge";},
"chicagoheights": function() {return "Chicago Heights";},
"chicagoridge": function() {return "Chicago Ridge";},
"chinohills": function() {return "Chino Hills";},
"chinovalley": function() {return "Chino Valley";},
"chippewafalls": function() {return "Chippewa Falls";},
"chisagocity": function() {return "Chisago City";},
"chulavista": function() {return "Chula Vista";},
"churchhill": function() {return "Church Hill";},
"citrusheights": function() {return "Citrus Heights";},
"clarendonhills": function() {return "Clarendon Hills";},
"clearlake": function() {return "Clear Lake";},
"clevelandheights": function() {return "Cleveland Heights";},
"cliffsidepark": function() {return "Cliffside Park";},
"cliftonheights": function() {return "Clifton Heights";},
"coalcity": function() {return "Coal City";},
"cocoabeach": function() {return "Cocoa Beach";},
"coconutcreek": function() {return "Coconut Creek";},
"coeurd\alene": function() {return "Coeur d\'Alene";},
"coldspring": function() {return "Cold Spring";},
"collegepark": function() {return "College Park";},
"collegeplace": function() {return "College Place";},
"collegestation": function() {return "College Station";},
"colonialheights": function() {return "Colonial Heights";},
"coloradosprings": function() {return "Colorado Springs";},
"columbiacity": function() {return "Columbia City";},
"columbiafalls": function() {return "Columbia Falls";},
"columbiaheights": function() {return "Columbia Heights";},
"commercecity": function() {return "Commerce City";},
"coonrapids": function() {return "Coon Rapids";},
"coopercity": function() {return "Cooper City";},
"coosbay": function() {return "Coos Bay";},
"copperascove": function() {return "Copperas Cove";},
"coralgables": function() {return "Coral Gables";},
"coralsprings": function() {return "Coral Springs";},
"corpuschristi": function() {return "Corpus Christi";},
"cortemadera": function() {return "Corte Madera";},
"costamesa": function() {return "Costa Mesa";},
"cottagegrove": function() {return "Cottage Grove";},
"cottonwoodheights": function() {return "Cottonwood Heights";},
"councilbluffs": function() {return "Council Bluffs";},
"countryclubhills": function() {return "Country Club Hills";},
"crescentcity": function() {return "Crescent City";},
"cresthill": function() {return "Crest Hill";},
"crevecoeur": function() {return "Creve Coeur";},
"crownpoint": function() {return "Crown Point";},
"crystalcity": function() {return "Crystal City";},
"crystallake": function() {return "Crystal Lake";},
"culvercity": function() {return "Culver City";},
"cutlerbay": function() {return "Cutler Bay";},
"cuyahogafalls": function() {return "Cuyahoga Falls";},
"dadecity": function() {return "Dade City";},
"dalycity": function() {return "Daly City";},
"danapoint": function() {return "Dana Point";},
"daniabeach": function() {return "Dania Beach";},
"dardenneprairie": function() {return "Dardenne Prairie";},
"daytonabeach": function() {return "Daytona Beach";},
"depere": function() {return "De Pere";},
"dequeen": function() {return "De Queen";},
"desoto": function() {return "De Soto";},
"dewitt": function() {return "De Witt";},
"dearbornheights": function() {return "Dearborn Heights";},
"deerpark": function() {return "Deer Park";},
"deerfieldbeach": function() {return "Deerfield Beach";},
"defuniaksprings": function() {return "DeFuniak Springs";},
"delcity": function() {return "Del City";},
"delrio": function() {return "Del Rio";},
"delraybeach": function() {return "Delray Beach";},
"denhamsprings": function() {return "Denham Springs";},
"desmoines": function() {return "Des Moines";},
"desperes": function() {return "Des Peres";},
"desplaines": function() {return "Des Plaines";},
"deserthotsprings": function() {return "Desert Hot Springs";},
"detroitlakes": function() {return "Detroit Lakes";},
"devilslake": function() {return "Devils Lake";},
"diamondbar": function() {return "Diamond Bar";},
"dicksoncity": function() {return "Dickson City";},
"districtheights": function() {return "District Heights";},
"dobbsferry": function() {return "Dobbs Ferry";},
"dodgecity": function() {return "Dodge City";},
"dospalos": function() {return "Dos Palos";},
"douglasshills": function() {return "Douglass Hills";},
"downersgrove": function() {return "Downers Grove";},
"duquoin": function() {return "Du Quoin";},
"eaglemountain": function() {return "Eagle Mountain";},
"eaglepass": function() {return "Eagle Pass";},
"eaglepoint": function() {return "Eagle Point";},
"eastalton": function() {return "East Alton";},
"eastaurora": function() {return "East Aurora";},
"eastbethel": function() {return "East Bethel";},
"eastchicago": function() {return "East Chicago";},
"eastcleveland": function() {return "East Cleveland";},
"eastgrandforks": function() {return "East Grand Forks";},
"eastgrandrapids": function() {return "East Grand Rapids";},
"easthills": function() {return "East Hills";},
"eastlansing": function() {return "East Lansing";},
"eastliverpool": function() {return "East Liverpool";},
"eastmoline": function() {return "East Moline";},
"eastorange": function() {return "East Orange";},
"eastpaloalto": function() {return "East Palo Alto";},
"eastpeoria": function() {return "East Peoria";},
"eastpoint": function() {return "East Point";},
"eastprovidence": function() {return "East Providence";},
"eastridge": function() {return "East Ridge";},
"eastrochester": function() {return "East Rochester";},
"eastrockaway": function() {return "East Rockaway";},
"eastrutherford": function() {return "East Rutherford";},
"eaststlouis": function() {return "East St. Louis";},
"eaststroudsburg": function() {return "East Stroudsburg";},
"eastwenatchee": function() {return "East Wenatchee";},
"easthamptontown": function() {return "Easthampton Town";},
"eatonrapids": function() {return "Eaton Rapids";},
"eauclaire": function() {return "Eau Claire";},
"edenprairie": function() {return "Eden Prairie";},
"elcajon": function() {return "El Cajon";},
"elcampo": function() {return "El Campo";},
"elcentro": function() {return "El Centro";},
"elcerrito": function() {return "El Cerrito";},
"eldorado": function() {return "El Dorado";},
"elmirage": function() {return "El Mirage";},
"elmonte": function() {return "El Monte";},
"elpaso": function() {return "El Paso";},
"elreno": function() {return "El Reno";},
"elsegundo": function() {return "El Segundo";},
"elizabethcity": function() {return "Elizabeth City";},
"elkcity": function() {return "Elk City";},
"elkgrove": function() {return "Elk Grove";},
"elkgrovevillage": function() {return "Elk Grove Village";},
"elkriver": function() {return "Elk River";},
"ellwoodcity": function() {return "Ellwood City";},
"elmgrove": function() {return "Elm Grove";},
"elmwoodpark": function() {return "Elmwood Park";},
"englewoodcliffs": function() {return "Englewood Cliffs";},
"essexjunction": function() {return "Essex Junction";},
"estespark": function() {return "Estes Park";},
"evergreenpark": function() {return "Evergreen Park";},
"excelsiorsprings": function() {return "Excelsior Springs";},
"fairhaven": function() {return "Fair Haven";},
"fairlawn": function() {return "Fair Lawn";},
"fairoaksranch": function() {return "Fair Oaks Ranch";},
"fairviewheights": function() {return "Fairview Heights";},
"fairviewpark": function() {return "Fairview Park";},
"falconheights": function() {return "Falcon Heights";},
"fallriver": function() {return "Fall River";},
"fallschurch": function() {return "Falls Church";},
"farmersbranch": function() {return "Farmers Branch";},
"farmingtonhills": function() {return "Farmington Hills";},
"farrwest": function() {return "Farr West";},
"federalheights": function() {return "Federal Heights";},
"federalway": function() {return "Federal Way";},
"fergusfalls": function() {return "Fergus Falls";},
"fernandinabeach": function() {return "Fernandina Beach";},
"flatrock": function() {return "Flat Rock";},
"floralpark": function() {return "Floral Park";},
"florhampark": function() {return "Florham Park";},
"floridacity": function() {return "Florida City";},
"flowermound": function() {return "Flower Mound";},
"flowerybranch": function() {return "Flowery Branch";},
"fonddulac": function() {return "Fond du Lac";},
"forestacres": function() {return "Forest Acres";},
"forestcity": function() {return "Forest City";},
"forestgrove": function() {return "Forest Grove";},
"foresthill": function() {return "Forest Hill";},
"foresthills": function() {return "Forest Hills";},
"forestlake": function() {return "Forest Lake";},
"forestpark": function() {return "Forest Park";},
"forrestcity": function() {return "Forrest City";},
"fortatkinson": function() {return "Fort Atkinson";},
"fortbragg": function() {return "Fort Bragg";},
"fortcollins": function() {return "Fort Collins";},
"fortdodge": function() {return "Fort Dodge";},
"fortlauderdale": function() {return "Fort Lauderdale";},
"fortlee": function() {return "Fort Lee";},
"fortlupton": function() {return "Fort Lupton";},
"fortmadison": function() {return "Fort Madison";},
"fortmeade": function() {return "Fort Meade";},
"fortmill": function() {return "Fort Mill";},
"fortmitchell": function() {return "Fort Mitchell";},
"fortmorgan": function() {return "Fort Morgan";},
"fortmyers": function() {return "Fort Myers";},
"fortmyersbeach": function() {return "Fort Myers Beach";},
"fortoglethorpe": function() {return "Fort Oglethorpe";},
"fortpayne": function() {return "Fort Payne";},
"fortpierce": function() {return "Fort Pierce";},
"fortscott": function() {return "Fort Scott";},
"fortsmith": function() {return "Fort Smith";},
"fortstockton": function() {return "Fort Stockton";},
"fortthomas": function() {return "Fort Thomas";},
"fortvalley": function() {return "Fort Valley";},
"fortwaltonbeach": function() {return "Fort Walton Beach";},
"fortwayne": function() {return "Fort Wayne";},
"fortworth": function() {return "Fort Worth";},
"fortwright": function() {return "Fort Wright";},
"fostercity": function() {return "Foster City";},
"fountainhills": function() {return "Fountain Hills";},
"fountaininn": function() {return "Fountain Inn";},
"fountainvalley": function() {return "Fountain Valley";},
"foxchapel": function() {return "Fox Chapel";},
"foxlake": function() {return "Fox Lake";},
"foxpoint": function() {return "Fox Point";},
"franklinlakes": function() {return "Franklin Lakes";},
"franklinpark": function() {return "Franklin Park";},
"franklintown": function() {return "Franklin Town";},
"frontroyal": function() {return "Front Royal";},
"fruitheights": function() {return "Fruit Heights";},
"fruitlandpark": function() {return "Fruitland Park";},
"galenapark": function() {return "Galena Park";},
"gardencity": function() {return "Garden City";},
"gardengrove": function() {return "Garden Grove";},
"garfieldheights": function() {return "Garfield Heights";},
"gascity": function() {return "Gas City";},
"gigharbor": function() {return "Gig Harbor";},
"glencarbon": function() {return "Glen Carbon";},
"glencove": function() {return "Glen Cove";},
"glenellyn": function() {return "Glen Ellyn";},
"glenridge": function() {return "Glen Ridge";},
"glenrock": function() {return "Glen Rock";},
"glendaleheights": function() {return "Glendale Heights";},
"glennheights": function() {return "Glenn Heights";},
"glensfalls": function() {return "Glens Falls";},
"glenwoodsprings": function() {return "Glenwood Springs";},
"gloucestercity": function() {return "Gloucester City";},
"goldenvalley": function() {return "Golden Valley";},
"goosecreek": function() {return "Goose Creek";},
"grainvalley": function() {return "Grain Valley";},
"grandblanc": function() {return "Grand Blanc";},
"grandforks": function() {return "Grand Forks";},
"grandhaven": function() {return "Grand Haven";},
"grandisland": function() {return "Grand Island";},
"grandjunction": function() {return "Grand Junction";},
"grandledge": function() {return "Grand Ledge";},
"grandprairie": function() {return "Grand Prairie";},
"grandrapids": function() {return "Grand Rapids";},
"grandterrace": function() {return "Grand Terrace";},
"grandviewheights": function() {return "Grandview Heights";},
"granitecity": function() {return "Granite City";},
"graniteshoals": function() {return "Granite Shoals";},
"grantspass": function() {return "Grants Pass";},
"grassvalley": function() {return "Grass Valley";},
"greatbend": function() {return "Great Bend";},
"greatfalls": function() {return "Great Falls";},
"greatneck": function() {return "Great Neck";},
"greatneckplaza": function() {return "Great Neck Plaza";},
"greenbay": function() {return "Green Bay";},
"greencovesprings": function() {return "Green Cove Springs";},
"greenriver": function() {return "Green River";},
"greenfieldtown": function() {return "Greenfield Town";},
"greenwoodvillage": function() {return "Greenwood Village";},
"grossepointe": function() {return "Grosse Pointe";},
"grossepointefarms": function() {return "Grosse Pointe Farms";},
"grossepointepark": function() {return "Grosse Pointe Park";},
"grossepointewoods": function() {return "Grosse Pointe Woods";},
"grovecity": function() {return "Grove City";},
"groverbeach": function() {return "Grover Beach";},
"gulfbreeze": function() {return "Gulf Breeze";},
"gulfshores": function() {return "Gulf Shores";},
"gunbarrelcity": function() {return "Gun Barrel City";},
"haddonheights": function() {return "Haddon Heights";},
"hainescity": function() {return "Haines City";},
"halescorners": function() {return "Hales Corners";},
"halfmoonbay": function() {return "Half Moon Bay";},
"hallandalebeach": function() {return "Hallandale Beach";},
"haltomcity": function() {return "Haltom City";},
"hamlake": function() {return "Ham Lake";},
"hanoverpark": function() {return "Hanover Park";},
"happyvalley": function() {return "Happy Valley";},
"harkerheights": function() {return "Harker Heights";},
"harperwoods": function() {return "Harper Woods";},
"hartfordcity": function() {return "Hartford City";},
"harwoodheights": function() {return "Harwood Heights";},
"hasbrouckheights": function() {return "Hasbrouck Heights";},
"havredegrace": function() {return "Havre de Grace";},
"hawaiiangardens": function() {return "Hawaiian Gardens";},
"hawthornwoods": function() {return "Hawthorn Woods";},
"hazelcrest": function() {return "Hazel Crest";},
"hazelpark": function() {return "Hazel Park";},
"hebersprings": function() {return "Heber Springs";},
"helenawesthelena": function() {return "Helena-West Helena";},
"hermosabeach": function() {return "Hermosa Beach";},
"hialeahgardens": function() {return "Hialeah Gardens";},
"hickoryhills": function() {return "Hickory Hills";},
"highpoint": function() {return "High Point";},
"highsprings": function() {return "High Springs";},
"highlandheights": function() {return "Highland Heights";},
"highlandpark": function() {return "Highland Park";},
"highlandvillage": function() {return "Highland Village";},
"hiltonheadisland": function() {return "Hilton Head Island";},
"hoffmanestates": function() {return "Hoffman Estates";},
"hollyhill": function() {return "Holly Hill";},
"hollysprings": function() {return "Holly Springs";},
"homerglen": function() {return "Homer Glen";},
"hoodriver": function() {return "Hood River";},
"hopemills": function() {return "Hope Mills";},
"horizoncity": function() {return "Horizon City";},
"hornlake": function() {return "Horn Lake";},
"hotsprings": function() {return "Hot Springs";},
"huberheights": function() {return "Huber Heights";},
"hudsonfalls": function() {return "Hudson Falls";},
"huntingtonbeach": function() {return "Huntington Beach";},
"huntingtonpark": function() {return "Huntington Park";},
"huntingtonwoods": function() {return "Huntington Woods";},
"idahofalls": function() {return "Idaho Falls";},
"imperialbeach": function() {return "Imperial Beach";},
"indianharbourbeach": function() {return "Indian Harbour Beach";},
"indiantrail": function() {return "Indian Trail";},
"indianwells": function() {return "Indian Wells";},
"internationalfalls": function() {return "International Falls";},
"invergroveheights": function() {return "Inver Grove Heights";},
"iowacity": function() {return "Iowa City";},
"iowafalls": function() {return "Iowa Falls";},
"iowapark": function() {return "Iowa Park";},
"ironmountain": function() {return "Iron Mountain";},
"islandlake": function() {return "Island Lake";},
"jacintocity": function() {return "Jacinto City";},
"jacksonvillebeach": function() {return "Jacksonville Beach";},
"jamesisland": function() {return "James Island";},
"jeffersoncity": function() {return "Jefferson City";},
"jeffersonhills": function() {return "Jefferson Hills";},
"jerseycity": function() {return "Jersey City";},
"jerseyvillage": function() {return "Jersey Village";},
"johnscreek": function() {return "Johns Creek";},
"johnsoncity": function() {return "Johnson City";},
"junctioncity": function() {return "Junction City";},
"jurupavalley": function() {return "Jurupa Valley";},
"kansascity": function() {return "Kansas City";},
"kennethcity": function() {return "Kenneth City";},
"kennettsquare": function() {return "Kennett Square";},
"keybiscayne": function() {return "Key Biscayne";},
"keywest": function() {return "Key West";},
"killdevilhills": function() {return "Kill Devil Hills";},
"kingcity": function() {return "King City";},
"kingsmountain": function() {return "Kings Mountain";},
"kingspoint": function() {return "Kings Point";},
"kiryasjoel": function() {return "Kiryas Joel";},
"klamathfalls": function() {return "Klamath Falls";},
"lacanadaflintridge": function() {return "La Canada Flintridge";},
"lacrosse": function() {return "La Crosse";},
"laferia": function() {return "La Feria";},
"lafollette": function() {return "La Follette";},
"lagrande": function() {return "La Grande";},
"lagrange": function() {return "La Grange";},
"lagrangepark": function() {return "La Grange Park";},
"lahabra": function() {return "La Habra";},
"lahabraheights": function() {return "La Habra Heights";},
"lajunta": function() {return "La Junta";},
"lamarque": function() {return "La Marque";},
"lamesa": function() {return "La Mesa";},
"lamirada": function() {return "La Mirada";},
"lapalma": function() {return "La Palma";},
"laplata": function() {return "La Plata";},
"laporte": function() {return "La Porte";},
"lapuente": function() {return "La Puente";},
"laquinta": function() {return "La Quinta";},
"lavergne": function() {return "La Vergne";},
"laverne": function() {return "La Verne";},
"lavista": function() {return "La Vista";},
"ladylake": function() {return "Lady Lake";},
"lagovista": function() {return "Lago Vista";},
"lagunabeach": function() {return "Laguna Beach";},
"lagunahills": function() {return "Laguna Hills";},
"lagunaniguel": function() {return "Laguna Niguel";},
"lagunawoods": function() {return "Laguna Woods";},
"lakealfred": function() {return "Lake Alfred";},
"lakebluff": function() {return "Lake Bluff";},
"lakecharles": function() {return "Lake Charles";},
"lakecity": function() {return "Lake City";},
"lakedallas": function() {return "Lake Dallas";},
"lakeelmo": function() {return "Lake Elmo";},
"lakeelsinore": function() {return "Lake Elsinore";},
"lakeforest": function() {return "Lake Forest";},
"lakeforestpark": function() {return "Lake Forest Park";},
"lakegeneva": function() {return "Lake Geneva";},
"lakegrove": function() {return "Lake Grove";},
"lakehallie": function() {return "Lake Hallie";},
"lakehavasucity": function() {return "Lake Havasu City";},
"lakeinthehills": function() {return "Lake in the Hills";},
"lakejackson": function() {return "Lake Jackson";},
"lakemary": function() {return "Lake Mary";},
"lakemills": function() {return "Lake Mills";},
"lakeoswego": function() {return "Lake Oswego";},
"lakepark": function() {return "Lake Park";},
"lakestlouis": function() {return "Lake St. Louis";},
"lakestation": function() {return "Lake Station";},
"lakestevens": function() {return "Lake Stevens";},
"lakevilla": function() {return "Lake Villa";},
"lakewales": function() {return "Lake Wales";},
"lakeworth": function() {return "Lake Worth";},
"lakezurich": function() {return "Lake Zurich";},
"lascruces": function() {return "Las Cruces";},
"lasvegas": function() {return "Las Vegas";},
"lauderdalelakes": function() {return "Lauderdale Lakes";},
"lemars": function() {return "Le Mars";},
"leaguecity": function() {return "League City";},
"lemongrove": function() {return "Lemon Grove";},
"lenoircity": function() {return "Lenoir City";},
"leonvalley": function() {return "Leon Valley";},
"libertylake": function() {return "Liberty Lake";},
"lighthousepoint": function() {return "Lighthouse Point";},
"lincolncity": function() {return "Lincoln City";},
"lincolnpark": function() {return "Lincoln Park";},
"linolakes": function() {return "Lino Lakes";},
"litchfieldpark": function() {return "Litchfield Park";},
"littlecanada": function() {return "Little Canada";},
"littlechute": function() {return "Little Chute";},
"littleelm": function() {return "Little Elm";},
"littlefalls": function() {return "Little Falls";},
"littleferry": function() {return "Little Ferry";},
"littlerock": function() {return "Little Rock";},
"littlesilver": function() {return "Little Silver";},
"liveoak": function() {return "Live Oak";},
"lockhaven": function() {return "Lock Haven";},
"locustgrove": function() {return "Locust Grove";},
"lomalinda": function() {return "Loma Linda";},
"lonegrove": function() {return "Lone Grove";},
"lonetree": function() {return "Lone Tree";},
"longbeach": function() {return "Long Beach";},
"longbranch": function() {return "Long Branch";},
"longgrove": function() {return "Long Grove";},
"longboatkey": function() {return "Longboat Key";},
"losalamitos": function() {return "Los Alamitos";},
"losaltos": function() {return "Los Altos";},
"losaltoshills": function() {return "Los Altos Hills";},
"losangeles": function() {return "Los Angeles";},
"losbanos": function() {return "Los Banos";},
"losfresnos": function() {return "Los Fresnos";},
"losgatos": function() {return "Los Gatos";},
"loslunas": function() {return "Los Lunas";},
"losranchosdealbuquerque": function() {return "Los Ranchos de Albuquerque";},
"lovespark": function() {return "Loves Park";},
"lowerburrell": function() {return "Lower Burrell";},
"lynnhaven": function() {return "Lynn Haven";},
"machesneypark": function() {return "Machesney Park";},
"madisonheights": function() {return "Madison Heights";},
"mammothlakes": function() {return "Mammoth Lakes";},
"manassaspark": function() {return "Manassas Park";},
"manhattanbeach": function() {return "Manhattan Beach";},
"manitousprings": function() {return "Manitou Springs";},
"maplegrove": function() {return "Maple Grove";},
"mapleheights": function() {return "Maple Heights";},
"maplevalley": function() {return "Maple Valley";},
"marblefalls": function() {return "Marble Falls";},
"marcoisland": function() {return "Marco Island";},
"margatecity": function() {return "Margate City";},
"martinsferry": function() {return "Martins Ferry";},
"marylandheights": function() {return "Maryland Heights";},
"masoncity": function() {return "Mason City";},
"massapequapark": function() {return "Massapequa Park";},
"masticbeach": function() {return "Mastic Beach";},
"mayfieldheights": function() {return "Mayfield Heights";},
"mckeesrocks": function() {return "McKees Rocks";},
"melrosepark": function() {return "Melrose Park";},
"mendotaheights": function() {return "Mendota Heights";},
"menlopark": function() {return "Menlo Park";},
"menomoneefalls": function() {return "Menomonee Falls";},
"mercerisland": function() {return "Mercer Island";},
"methuentown": function() {return "Methuen Town";},
"miamibeach": function() {return "Miami Beach";},
"miamigardens": function() {return "Miami Gardens";},
"miamilakes": function() {return "Miami Lakes";},
"miamishores": function() {return "Miami Shores";},
"miamisprings": function() {return "Miami Springs";},
"michigancity": function() {return "Michigan City";},
"middleburgheights": function() {return "Middleburg Heights";},
"midlandpark": function() {return "Midland Park";},
"midwestcity": function() {return "Midwest City";},
"milescity": function() {return "Miles City";},
"millcreek": function() {return "Mill Creek";},
"millvalley": function() {return "Mill Valley";},
"millsriver": function() {return "Mills River";},
"mineralwells": function() {return "Mineral Wells";},
"minthill": function() {return "Mint Hill";},
"missionviejo": function() {return "Mission Viejo";},
"missouricity": function() {return "Missouri City";},
"monckscorner": function() {return "Moncks Corner";},
"montbelvieu": function() {return "Mont Belvieu";},
"montereypark": function() {return "Monterey Park";},
"moreheadcity": function() {return "Morehead City";},
"morenovalley": function() {return "Moreno Valley";},
"morgancity": function() {return "Morgan City";},
"morganhill": function() {return "Morgan Hill";},
"morrisplains": function() {return "Morris Plains";},
"morrobay": function() {return "Morro Bay";},
"mortongrove": function() {return "Morton Grove";},
"moseslake": function() {return "Moses Lake";},
"mosspoint": function() {return "Moss Point";},
"moundsview": function() {return "Mounds View";},
"mountairy": function() {return "Mount Airy";},
"mountarlington": function() {return "Mount Arlington";},
"mountcarmel": function() {return "Mount Carmel";},
"mountclemens": function() {return "Mount Clemens";},
"mountdora": function() {return "Mount Dora";},
"mounthealthy": function() {return "Mount Healthy";},
"mountholly": function() {return "Mount Holly";},
"mounthoreb": function() {return "Mount Horeb";},
"mountjoy": function() {return "Mount Joy";},
"mountjuliet": function() {return "Mount Juliet";},
"mountkisco": function() {return "Mount Kisco";},
"mountpleasant": function() {return "Mount Pleasant";},
"mountprospect": function() {return "Mount Prospect";},
"mountrainier": function() {return "Mount Rainier";},
"mountsterling": function() {return "Mount Sterling";},
"mountvernon": function() {return "Mount Vernon";},
"mountwashington": function() {return "Mount Washington";},
"mountzion": function() {return "Mount Zion";},
"mountainbrook": function() {return "Mountain Brook";},
"mountainhome": function() {return "Mountain Home";},
"mountainview": function() {return "Mountain View";},
"mountlaketerrace": function() {return "Mountlake Terrace";},
"munroefalls": function() {return "Munroe Falls";},
"muscleshoals": function() {return "Muscle Shoals";},
"muskegonheights": function() {return "Muskegon Heights";},
"myrtlebeach": function() {return "Myrtle Beach";},
"nationalcity": function() {return "National City";},
"nebraskacity": function() {return "Nebraska City";},
"neptunebeach": function() {return "Neptune Beach";},
"newalbany": function() {return "New Albany";},
"newbaltimore": function() {return "New Baltimore";},
"newbedford": function() {return "New Bedford";},
"newberlin": function() {return "New Berlin";},
"newbern": function() {return "New Bern";},
"newbraunfels": function() {return "New Braunfels";},
"newbrighton": function() {return "New Brighton";},
"newbritain": function() {return "New Britain";},
"newbrunswick": function() {return "New Brunswick";},
"newcarlisle": function() {return "New Carlisle";},
"newcarrollton": function() {return "New Carrollton";},
"newcastle": function() {return "New Castle";},
"newcumberland": function() {return "New Cumberland";},
"newfranklin": function() {return "New Franklin";},
"newhaven": function() {return "New Haven";},
"newhempstead": function() {return "New Hempstead";},
"newholland": function() {return "New Holland";},
"newhope": function() {return "New Hope";},
"newhydepark": function() {return "New Hyde Park";},
"newiberia": function() {return "New Iberia";},
"newkensington": function() {return "New Kensington";},
"newlenox": function() {return "New Lenox";},
"newlondon": function() {return "New London";},
"newmartinsville": function() {return "New Martinsville";},
"newmilford": function() {return "New Milford";},
"neworleans": function() {return "New Orleans";},
"newpaltz": function() {return "New Paltz";},
"newphiladelphia": function() {return "New Philadelphia";},
"newportrichey": function() {return "New Port Richey";},
"newprague": function() {return "New Prague";},
"newprovidence": function() {return "New Providence";},
"newrichmond": function() {return "New Richmond";},
"newrochelle": function() {return "New Rochelle";},
"newsmyrnabeach": function() {return "New Smyrna Beach";},
"newsquare": function() {return "New Square";},
"newulm": function() {return "New Ulm";},
"newwhiteland": function() {return "New Whiteland";},
"newyork": function() {return "New York";},
"newportbeach": function() {return "Newport Beach";},
"newportnews": function() {return "Newport News";},
"niagarafalls": function() {return "Niagara Falls";},
"normandypark": function() {return "Normandy Park";},
"northadams": function() {return "North Adams";},
"northarlington": function() {return "North Arlington";},
"northaugusta": function() {return "North Augusta";},
"northaurora": function() {return "North Aurora";},
"northbayvillage": function() {return "North Bay Village";},
"northbend": function() {return "North Bend";},
"northbranch": function() {return "North Branch";},
"northcaldwell": function() {return "North Caldwell";},
"northcanton": function() {return "North Canton";},
"northcharleston": function() {return "North Charleston";},
"northchicago": function() {return "North Chicago";},
"northcollegehill": function() {return "North College Hill";},
"northfonddulac": function() {return "North Fond du Lac";},
"northhaledon": function() {return "North Haledon";},
"northhills": function() {return "North Hills";},
"northlasvegas": function() {return "North Las Vegas";},
"northlauderdale": function() {return "North Lauderdale";},
"northliberty": function() {return "North Liberty";},
"northlittlerock": function() {return "North Little Rock";},
"northlogan": function() {return "North Logan";},
"northmanchester": function() {return "North Manchester";},
"northmankato": function() {return "North Mankato";},
"northmiami": function() {return "North Miami";},
"northmiamibeach": function() {return "North Miami Beach";},
"northmyrtlebeach": function() {return "North Myrtle Beach";},
"northoaks": function() {return "North Oaks";},
"northogden": function() {return "North Ogden";},
"northolmsted": function() {return "North Olmsted";},
"northpalmbeach": function() {return "North Palm Beach";},
"northplainfield": function() {return "North Plainfield";},
"northplatte": function() {return "North Platte";},
"northport": function() {return "North Port";},
"northrichlandhills": function() {return "North Richland Hills";},
"northridgeville": function() {return "North Ridgeville";},
"northriverside": function() {return "North Riverside";},
"northroyalton": function() {return "North Royalton";},
"northsaltlake": function() {return "North Salt Lake";},
"northstpaul": function() {return "North St. Paul";},
"northsyracuse": function() {return "North Syracuse";},
"northtonawanda": function() {return "North Tonawanda";},
"northvernon": function() {return "North Vernon";},
"nortonshores": function() {return "Norton Shores";},
"oakbrook": function() {return "Oak Brook";},
"oakcreek": function() {return "Oak Creek";},
"oakforest": function() {return "Oak Forest";},
"oakgrove": function() {return "Oak Grove";},
"oakharbor": function() {return "Oak Harbor";},
"oakhill": function() {return "Oak Hill";},
"oakisland": function() {return "Oak Island";},
"oaklawn": function() {return "Oak Lawn";},
"oakpark": function() {return "Oak Park";},
"oakridge": function() {return "Oak Ridge";},
"oaklandpark": function() {return "Oakland Park";},
"oceancity": function() {return "Ocean City";},
"oceanshores": function() {return "Ocean Shores";},
"oceansprings": function() {return "Ocean Springs";},
"oilcity": function() {return "Oil City";},
"oklahomacity": function() {return "Oklahoma City";},
"oldforge": function() {return "Old Forge";},
"oldtappan": function() {return "Old Tappan";},
"oldtown": function() {return "Old Town";},
"olivebranch": function() {return "Olive Branch";},
"olmstedfalls": function() {return "Olmsted Falls";},
"orangebeach": function() {return "Orange Beach";},
"orangecity": function() {return "Orange City";},
"orangecove": function() {return "Orange Cove";},
"orangepark": function() {return "Orange Park";},
"oregoncity": function() {return "Oregon City";},
"orlandhills": function() {return "Orland Hills";},
"orlandpark": function() {return "Orland Park";},
"ormondbeach": function() {return "Ormond Beach";},
"orovalley": function() {return "Oro Valley";},
"overlandpark": function() {return "Overland Park";},
"pacificgrove": function() {return "Pacific Grove";},
"palisadespark": function() {return "Palisades Park";},
"palmbay": function() {return "Palm Bay";},
"palmbeach": function() {return "Palm Beach";},
"palmbeachgardens": function() {return "Palm Beach Gardens";},
"palmcoast": function() {return "Palm Coast";},
"palmdesert": function() {return "Palm Desert";},
"palmsprings": function() {return "Palm Springs";},
"palmertown": function() {return "Palmer Town";},
"palmettobay": function() {return "Palmetto Bay";},
"paloalto": function() {return "Palo Alto";},
"palosheights": function() {return "Palos Heights";},
"paloshills": function() {return "Palos Hills";},
"palosverdesestates": function() {return "Palos Verdes Estates";},
"panamacity": function() {return "Panama City";},
"panamacitybeach": function() {return "Panama City Beach";},
"paradisevalley": function() {return "Paradise Valley";},
"parkcity": function() {return "Park City";},
"parkforest": function() {return "Park Forest";},
"parkhills": function() {return "Park Hills";},
"parkridge": function() {return "Park Ridge";},
"parmaheights": function() {return "Parma Heights";},
"pasorobles": function() {return "Paso Robles";},
"passchristian": function() {return "Pass Christian";},
"paulsvalley": function() {return "Pauls Valley";},
"pearidge": function() {return "Pea Ridge";},
"peachtreecity": function() {return "Peachtree City";},
"peachtreecorners": function() {return "Peachtree Corners";},
"pelhammanor": function() {return "Pelham Manor";},
"pellcity": function() {return "Pell City";},
"pembrokepark": function() {return "Pembroke Park";},
"pembrokepines": function() {return "Pembroke Pines";},
"peoriaheights": function() {return "Peoria Heights";},
"pepperpike": function() {return "Pepper Pike";},
"perthamboy": function() {return "Perth Amboy";},
"phenixcity": function() {return "Phenix City";},
"picorivera": function() {return "Pico Rivera";},
"pigeonforge": function() {return "Pigeon Forge";},
"pikeroad": function() {return "Pike Road";},
"pinebluff": function() {return "Pine Bluff";},
"pinehill": function() {return "Pine Hill";},
"pinellaspark": function() {return "Pinellas Park";},
"pingreegrove": function() {return "Pingree Grove";},
"pismobeach": function() {return "Pismo Beach";},
"plaincity": function() {return "Plain City";},
"plantcity": function() {return "Plant City";},
"pleasantgrove": function() {return "Pleasant Grove";},
"pleasanthill": function() {return "Pleasant Hill";},
"pleasanthills": function() {return "Pleasant Hills";},
"pleasantprairie": function() {return "Pleasant Prairie";},
"pleasantview": function() {return "Pleasant View";},
"pointpleasant": function() {return "Point Pleasant";},
"pompanobeach": function() {return "Pompano Beach";},
"pomptonlakes": function() {return "Pompton Lakes";},
"poncacity": function() {return "Ponca City";},
"pontoonbeach": function() {return "Pontoon Beach";},
"poplarbluff": function() {return "Poplar Bluff";},
"poplargrove": function() {return "Poplar Grove";},
"portallen": function() {return "Port Allen";},
"portangeles": function() {return "Port Angeles";},
"portarthur": function() {return "Port Arthur";},
"portchester": function() {return "Port Chester";},
"portclinton": function() {return "Port Clinton";},
"porthueneme": function() {return "Port Hueneme";},
"porthuron": function() {return "Port Huron";},
"portisabel": function() {return "Port Isabel";},
"portjefferson": function() {return "Port Jefferson";},
"portjervis": function() {return "Port Jervis";},
"portlavaca": function() {return "Port Lavaca";},
"portneches": function() {return "Port Neches";},
"portorange": function() {return "Port Orange";},
"portorchard": function() {return "Port Orchard";},
"portroyal": function() {return "Port Royal";},
"portstlucie": function() {return "Port St. Lucie";},
"porttownsend": function() {return "Port Townsend";},
"portwashington": function() {return "Port Washington";},
"portwentworth": function() {return "Port Wentworth";},
"postfalls": function() {return "Post Falls";},
"powdersprings": function() {return "Powder Springs";},
"prairieduchien": function() {return "Prairie du Chien";},
"prairiegrove": function() {return "Prairie Grove";},
"prairieview": function() {return "Prairie View";},
"prairievillage": function() {return "Prairie Village";},
"prescottvalley": function() {return "Prescott Valley";},
"presqueisle": function() {return "Presque Isle";},
"priorlake": function() {return "Prior Lake";},
"prospectheights": function() {return "Prospect Heights";},
"prospectpark": function() {return "Prospect Park";},
"providencevillage": function() {return "Providence Village";},
"pryorcreek": function() {return "Pryor Creek";},
"puntagorda": function() {return "Punta Gorda";},
"queencreek": function() {return "Queen Creek";},
"rainbowcity": function() {return "Rainbow City";},
"ranchocordova": function() {return "Rancho Cordova";},
"ranchocucamonga": function() {return "Rancho Cucamonga";},
"ranchomirage": function() {return "Rancho Mirage";},
"ranchopalosverdes": function() {return "Rancho Palos Verdes";},
"ranchosantamargarita": function() {return "Rancho Santa Margarita";},
"rapidcity": function() {return "Rapid City";},
"redbank": function() {return "Red Bank";},
"redbluff": function() {return "Red Bluff";},
"redlion": function() {return "Red Lion";},
"redoak": function() {return "Red Oak";},
"redwing": function() {return "Red Wing";},
"redondobeach": function() {return "Redondo Beach";},
"redwoodcity": function() {return "Redwood City";},
"redwoodfalls": function() {return "Redwood Falls";},
"ricelake": function() {return "Rice Lake";},
"richlandcenter": function() {return "Richland Center";},
"richlandhills": function() {return "Richland Hills";},
"richmondheights": function() {return "Richmond Heights";},
"richmondhill": function() {return "Richmond Hill";},
"richtonpark": function() {return "Richton Park";},
"ridgefieldpark": function() {return "Ridgefield Park";},
"ridleypark": function() {return "Ridley Park";},
"riograndecity": function() {return "Rio Grande City";},
"riorancho": function() {return "Rio Rancho";},
"riovista": function() {return "Rio Vista";},
"riveredge": function() {return "River Edge";},
"riverfalls": function() {return "River Falls";},
"riverforest": function() {return "River Forest";},
"rivergrove": function() {return "River Grove";},
"riveroaks": function() {return "River Oaks";},
"riverrouge": function() {return "River Rouge";},
"riverdalepark": function() {return "Riverdale Park";},
"rivierabeach": function() {return "Riviera Beach";},
"roanokerapids": function() {return "Roanoke Rapids";},
"rochesterhills": function() {return "Rochester Hills";},
"rockfalls": function() {return "Rock Falls";},
"rockhill": function() {return "Rock Hill";},
"rockisland": function() {return "Rock Island";},
"rocksprings": function() {return "Rock Springs";},
"rockvillecentre": function() {return "Rockville Centre";},
"rockymount": function() {return "Rocky Mount";},
"rockyriver": function() {return "Rocky River";},
"roelandpark": function() {return "Roeland Park";},
"rohnertpark": function() {return "Rohnert Park";},
"rollinghillsestates": function() {return "Rolling Hills Estates";},
"rollingmeadows": function() {return "Rolling Meadows";},
"rosellepark": function() {return "Roselle Park";},
"roundlake": function() {return "Round Lake";},
"roundlakebeach": function() {return "Round Lake Beach";},
"roundlakepark": function() {return "Round Lake Park";},
"roundrock": function() {return "Round Rock";},
"royaloak": function() {return "Royal Oak";},
"royalpalmbeach": function() {return "Royal Palm Beach";},
"roysecity": function() {return "Royse City";},
"ryebrook": function() {return "Rye Brook";},
"safetyharbor": function() {return "Safety Harbor";},
"saltlakecity": function() {return "Salt Lake City";},
"sanangelo": function() {return "San Angelo";},
"sananselmo": function() {return "San Anselmo";},
"sanantonio": function() {return "San Antonio";},
"sanbenito": function() {return "San Benito";},
"sanbernardino": function() {return "San Bernardino";},
"sanbruno": function() {return "San Bruno";},
"sancarlos": function() {return "San Carlos";},
"sanclemente": function() {return "San Clemente";},
"sandiego": function() {return "San Diego";},
"sandimas": function() {return "San Dimas";},
"sanelizario": function() {return "San Elizario";},
"sanfernando": function() {return "San Fernando";},
"sanfrancisco": function() {return "San Francisco";},
"sangabriel": function() {return "San Gabriel";},
"sanjacinto": function() {return "San Jacinto";},
"sanjose": function() {return "San Jose";},
"sanjuan": function() {return "San Juan";},
"sanjuancapistrano": function() {return "San Juan Capistrano";},
"sanleandro": function() {return "San Leandro";},
"sanluis": function() {return "San Luis";},
"sanluisobispo": function() {return "San Luis Obispo";},
"sanmarcos": function() {return "San Marcos";},
"sanmarino": function() {return "San Marino";},
"sanmateo": function() {return "San Mateo";},
"sanpablo": function() {return "San Pablo";},
"sanrafael": function() {return "San Rafael";},
"sanramon": function() {return "San Ramon";},
"sandsprings": function() {return "Sand Springs";},
"sandysprings": function() {return "Sandy Springs";},
"santaana": function() {return "Santa Ana";},
"santabarbara": function() {return "Santa Barbara";},
"santaclara": function() {return "Santa Clara";},
"santaclarita": function() {return "Santa Clarita";},
"santacruz": function() {return "Santa Cruz";},
"santafe": function() {return "Santa Fe";},
"santafesprings": function() {return "Santa Fe Springs";},
"santamaria": function() {return "Santa Maria";},
"santamonica": function() {return "Santa Monica";},
"santapaula": function() {return "Santa Paula";},
"santarosa": function() {return "Santa Rosa";},
"saranaclake": function() {return "Saranac Lake";},
"saratogasprings": function() {return "Saratoga Springs";},
"satellitebeach": function() {return "Satellite Beach";},
"saukrapids": function() {return "Sauk Rapids";},
"saukvillage": function() {return "Sauk Village";},
"saultstemarie": function() {return "Sault Ste. Marie";},
"schillerpark": function() {return "Schiller Park";},
"schuylkillhaven": function() {return "Schuylkill Haven";},
"scottsvalley": function() {return "Scotts Valley";},
"seacliff": function() {return "Sea Cliff";},
"sealbeach": function() {return "Seal Beach";},
"sevenhills": function() {return "Seven Hills";},
"shakerheights": function() {return "Shaker Heights";},
"sharonhill": function() {return "Sharon Hill";},
"shastalake": function() {return "Shasta Lake";},
"sheboyganfalls": function() {return "Sheboygan Falls";},
"sheffieldlake": function() {return "Sheffield Lake";},
"showlow": function() {return "Show Low";},
"sierramadre": function() {return "Sierra Madre";},
"sierravista": function() {return "Sierra Vista";},
"signalhill": function() {return "Signal Hill";},
"signalmountain": function() {return "Signal Mountain";},
"silercity": function() {return "Siler City";},
"siloamsprings": function() {return "Siloam Springs";},
"silvercity": function() {return "Silver City";},
"simivalley": function() {return "Simi Valley";},
"siouxcenter": function() {return "Sioux Center";},
"siouxcity": function() {return "Sioux City";},
"siouxfalls": function() {return "Sioux Falls";},
"sleepyhollow": function() {return "Sleepy Hollow";},
"smithsstation": function() {return "Smiths Station";},
"solanabeach": function() {return "Solana Beach";},
"somerspoint": function() {return "Somers Point";},
"southamboy": function() {return "South Amboy";},
"southbay": function() {return "South Bay";},
"southbeloit": function() {return "South Beloit";},
"southbend": function() {return "South Bend";},
"southboston": function() {return "South Boston";},
"southburlington": function() {return "South Burlington";},
"southcharleston": function() {return "South Charleston";},
"southdaytona": function() {return "South Daytona";},
"southelmonte": function() {return "South El Monte";},
"southelgin": function() {return "South Elgin";},
"southeuclid": function() {return "South Euclid";},
"southgate": function() {return "South Gate";},
"southholland": function() {return "South Holland";},
"southhouston": function() {return "South Houston";},
"southjordan": function() {return "South Jordan";},
"southlaketahoe": function() {return "South Lake Tahoe";},
"southlyon": function() {return "South Lyon";},
"southmiami": function() {return "South Miami";},
"southmilwaukee": function() {return "South Milwaukee";},
"southogden": function() {return "South Ogden";},
"southpasadena": function() {return "South Pasadena";},
"southplainfield": function() {return "South Plainfield";},
"southportland": function() {return "South Portland";},
"southriver": function() {return "South River";},
"southsaltlake": function() {return "South Salt Lake";},
"southsanfrancisco": function() {return "South San Francisco";},
"southsiouxcity": function() {return "South Sioux City";},
"southstpaul": function() {return "South St. Paul";},
"southtucson": function() {return "South Tucson";},
"southweber": function() {return "South Weber";},
"southwilliamsport": function() {return "South Williamsport";},
"southbridgetown": function() {return "Southbridge Town";},
"southernpines": function() {return "Southern Pines";},
"southwestranches": function() {return "Southwest Ranches";},
"spanishfork": function() {return "Spanish Fork";},
"spanishfort": function() {return "Spanish Fort";},
"spiritlake": function() {return "Spirit Lake";},
"spokanevalley": function() {return "Spokane Valley";},
"springgrove": function() {return "Spring Grove";},
"springhill": function() {return "Spring Hill";},
"springlake": function() {return "Spring Lake";},
"springlakepark": function() {return "Spring Lake Park";},
"springvalley": function() {return "Spring Valley";},
"stalbans": function() {return "St. Albans";},
"stann": function() {return "St. Ann";},
"stanthony": function() {return "St. Anthony";},
"staugustine": function() {return "St. Augustine";},
"staugustinebeach": function() {return "St. Augustine Beach";},
"stcharles": function() {return "St. Charles";},
"stclair": function() {return "St. Clair";},
"stclairshores": function() {return "St. Clair Shores";},
"stclairsville": function() {return "St. Clairsville";},
"stcloud": function() {return "St. Cloud";},
"stfrancis": function() {return "St. Francis";},
"stgabriel": function() {return "St. Gabriel";},
"stgeorge": function() {return "St. George";},
"sthelena": function() {return "St. Helena";},
"sthelens": function() {return "St. Helens";},
"stjames": function() {return "St. James";},
"stjohn": function() {return "St. John";},
"stjohns": function() {return "St. Johns";},
"stjoseph": function() {return "St. Joseph";},
"stlouis": function() {return "St. Louis";},
"stlouispark": function() {return "St. Louis Park";},
"stmartinville": function() {return "St. Martinville";},
"stmarys": function() {return "St. Marys";},
"stmatthews": function() {return "St. Matthews";},
"stmichael": function() {return "St. Michael";},
"stpaul": function() {return "St. Paul";},
"stpaulpark": function() {return "St. Paul Park";},
"stpetebeach": function() {return "St. Pete Beach";},
"stpeter": function() {return "St. Peter";},
"stpeters": function() {return "St. Peters";},
"stpetersburg": function() {return "St. Petersburg";},
"strobert": function() {return "St. Robert";},
"statecollege": function() {return "State College";},
"steamboatsprings": function() {return "Steamboat Springs";},
"sterlingheights": function() {return "Sterling Heights";},
"stevenspoint": function() {return "Stevens Point";},
"stonemountain": function() {return "Stone Mountain";},
"stormlake": function() {return "Storm Lake";},
"sturgeonbay": function() {return "Sturgeon Bay";},
"sugargrove": function() {return "Sugar Grove";},
"sugarhill": function() {return "Sugar Hill";},
"sugarland": function() {return "Sugar Land";},
"suisuncity": function() {return "Suisun City";},
"sulphursprings": function() {return "Sulphur Springs";},
"sunprairie": function() {return "Sun Prairie";},
"sunlandpark": function() {return "Sunland Park";},
"sunnyislesbeach": function() {return "Sunny Isles Beach";},
"sunsethills": function() {return "Sunset Hills";},
"swartzcreek": function() {return "Swartz Creek";},
"sweethome": function() {return "Sweet Home";},
"takomapark": function() {return "Takoma Park";},
"tarponsprings": function() {return "Tarpon Springs";},
"taylormill": function() {return "Taylor Mill";},
"tegacay": function() {return "Tega Cay";},
"tellcity": function() {return "Tell City";},
"templecity": function() {return "Temple City";},
"templeterrace": function() {return "Temple Terrace";},
"terrehaute": function() {return "Terre Haute";},
"terrellhills": function() {return "Terrell Hills";},
"texascity": function() {return "Texas City";},
"thecolony": function() {return "The Colony";},
"thedalles": function() {return "The Dalles";},
"thevillage": function() {return "The Village";},
"thevillageofindianhill": function() {return "The Village of Indian Hill";},
"thiefriverfalls": function() {return "Thief River Falls";},
"thousandoaks": function() {return "Thousand Oaks";},
"threerivers": function() {return "Three Rivers";},
"tinleypark": function() {return "Tinley Park";},
"tintonfalls": function() {return "Tinton Falls";},
"tippcity": function() {return "Tipp City";},
"townandcountry": function() {return "Town and Country";},
"travelersrest": function() {return "Travelers Rest";},
"traversecity": function() {return "Traverse City";},
"treasureisland": function() {return "Treasure Island";},
"trophyclub": function() {return "Trophy Club";},
"truthorconsequences": function() {return "Truth or Consequences";},
"turtlecreek": function() {return "Turtle Creek";},
"twentyninepalms": function() {return "Twentynine Palms";},
"twinfalls": function() {return "Twin Falls";},
"twinlakes": function() {return "Twin Lakes";},
"tworivers": function() {return "Two Rivers";},
"unionbeach": function() {return "Union Beach";},
"unioncity": function() {return "Union City";},
"uniongap": function() {return "Union Gap";},
"universalcity": function() {return "Universal City";},
"universitycity": function() {return "University City";},
"universityheights": function() {return "University Heights";},
"universitypark": function() {return "University Park";},
"universityplace": function() {return "University Place";},
"upperarlington": function() {return "Upper Arlington";},
"uppersaddleriver": function() {return "Upper Saddle River";},
"uppersandusky": function() {return "Upper Sandusky";},
"vadnaisheights": function() {return "Vadnais Heights";},
"valleycenter": function() {return "Valley Center";},
"valleycity": function() {return "Valley City";},
"valleypark": function() {return "Valley Park";},
"valleystream": function() {return "Valley Stream";},
"vanburen": function() {return "Van Buren";},
"vanwert": function() {return "Van Wert";},
"ventnorcity": function() {return "Ventnor City";},
"vernonhills": function() {return "Vernon Hills";},
"verobeach": function() {return "Vero Beach";},
"vestaviahills": function() {return "Vestavia Hills";},
"villahills": function() {return "Villa Hills";},
"villapark": function() {return "Villa Park";},
"villarica": function() {return "Villa Rica";},
"villageofislands": function() {return "Village of Islands";},
"villeplatte": function() {return "Ville Platte";},
"vinegrove": function() {return "Vine Grove";},
"virginiabeach": function() {return "Virginia Beach";},
"waitepark": function() {return "Waite Park";},
"wakeforest": function() {return "Wake Forest";},
"wakevillage": function() {return "Wake Village";},
"wallawalla": function() {return "Walla Walla";},
"walledlake": function() {return "Walled Lake";},
"walnutcreek": function() {return "Walnut Creek";},
"wappingersfalls": function() {return "Wappingers Falls";},
"warnerrobins": function() {return "Warner Robins";},
"warracres": function() {return "Warr Acres";},
"warrensvilleheights": function() {return "Warrensville Heights";},
"washingtoncourthouse": function() {return "Washington Court House";},
"washingtonterrace": function() {return "Washington Terrace";},
"watfordcity": function() {return "Watford City";},
"webbcity": function() {return "Webb City";},
"webstercity": function() {return "Webster City";},
"webstergroves": function() {return "Webster Groves";},
"weldonspring": function() {return "Weldon Spring";},
"wesleychapel": function() {return "Wesley Chapel";},
"wesleyhills": function() {return "Wesley Hills";},
"westallis": function() {return "West Allis";},
"westbend": function() {return "West Bend";},
"westbountiful": function() {return "West Bountiful";},
"westcarrollton": function() {return "West Carrollton";},
"westchester": function() {return "West Chester";},
"westchicago": function() {return "West Chicago";},
"westcolumbia": function() {return "West Columbia";},
"westcovina": function() {return "West Covina";},
"westdesmoines": function() {return "West Des Moines";},
"westdundee": function() {return "West Dundee";},
"westfargo": function() {return "West Fargo";},
"westfrankfort": function() {return "West Frankfort";},
"westhaven": function() {return "West Haven";},
"westhaverstraw": function() {return "West Haverstraw";},
"westhollywood": function() {return "West Hollywood";},
"westjordan": function() {return "West Jordan";},
"westlafayette": function() {return "West Lafayette";},
"westlinn": function() {return "West Linn";},
"westlongbranch": function() {return "West Long Branch";},
"westmelbourne": function() {return "West Melbourne";},
"westmemphis": function() {return "West Memphis";},
"westmiami": function() {return "West Miami";},
"westmifflin": function() {return "West Mifflin";},
"westmonroe": function() {return "West Monroe";},
"westnewyork": function() {return "West New York";},
"westpalmbeach": function() {return "West Palm Beach";},
"westpark": function() {return "West Park";},
"westplains": function() {return "West Plains";},
"westpoint": function() {return "West Point";},
"westrichland": function() {return "West Richland";},
"westsacramento": function() {return "West Sacramento";},
"westspringfieldtown": function() {return "West Springfield Town";},
"weststpaul": function() {return "West St. Paul";},
"westuniversityplace": function() {return "West University Place";},
"westvalleycity": function() {return "West Valley City";},
"westview": function() {return "West View";},
"westernsprings": function() {return "Western Springs";},
"westlakevillage": function() {return "Westlake Village";},
"weymouthtown": function() {return "Weymouth Town";},
"wheatridge": function() {return "Wheat Ridge";},
"whitebearlake": function() {return "White Bear Lake";},
"whitehall": function() {return "White Hall";},
"whitehouse": function() {return "White House";},
"whiteoak": function() {return "White Oak";},
"whiteplains": function() {return "White Plains";},
"whitesettlement": function() {return "White Settlement";},
"whitefishbay": function() {return "Whitefish Bay";},
"wichitafalls": function() {return "Wichita Falls";},
"willistonpark": function() {return "Williston Park";},
"willoughbyhills": function() {return "Willoughby Hills";},
"willowpark": function() {return "Willow Park";},
"willowsprings": function() {return "Willow Springs";},
"wiltonmanors": function() {return "Wilton Manors";},
"winonalake": function() {return "Winona Lake";},
"wintergarden": function() {return "Winter Garden";},
"winterhaven": function() {return "Winter Haven";},
"winterpark": function() {return "Winter Park";},
"wintersprings": function() {return "Winter Springs";},
"winthropharbor": function() {return "Winthrop Harbor";},
"winthroptown": function() {return "Winthrop Town";},
"wisconsinrapids": function() {return "Wisconsin Rapids";},
"wooddale": function() {return "Wood Dale";},
"woodriver": function() {return "Wood River";},
"woodclifflake": function() {return "Woodcliff Lake";},
"woodlandpark": function() {return "Woodland Park";},
"woodscross": function() {return "Woods Cross";},
"yazoocity": function() {return "Yazoo City";},
"yorbalinda": function() {return "Yorba Linda";},
"yubacity": function() {return "Yuba City";},
"yuccavalley": function() {return "Yucca Valley";},

// CANADIAN CITIES

"richmondhill": function() {return "Richmond Hill";},
"greatersudbury": function() {return "Greater Sudbury";},
"troisrivieres": function() {return "Trois-Rivieres";},
"stcatharines": function() {return "St. Catharines";},
"stjohns": function() {return "St. John's";},
"thunderbay": function() {return "Thunder Bay";},
"chathamkent": function() {return "Chatham-Kent";},
"reddeer": function() {return "Red Deer";},
"strathconacounty": function() {return "Strathcona County";},
"saintjeansurrichelieu": function() {return "Saint-Jean-sur-Richelieu";},
"capebreton": function() {return "Cape Breton";},
"niagarafalls": function() {return "Niagara Falls";},
"northvancouver": function() {return "North Vancouver";},
"mapleridge": function() {return "Maple Ridge";},
"kawarthalakes": function() {return "Kawartha Lakes";},
"saintjerome": function() {return "Saint-Jerome";},
"princegeorge": function() {return "Prince George";},
"saultstemarie": function() {return "Sault Ste. Marie";},
"woodbuffalo": function() {return "Wood Buffalo";},
"newwestminster": function() {return "New Westminster";},
"saintjohn": function() {return "Saint John";},
"stalbert": function() {return "St. Albert";},
"norfolkcounty": function() {return "Norfolk County";},
"medicinehat": function() {return "Medicine Hat";},
"grandeprairie": function() {return "Grande Prairie";},
"haltonhills": function() {return "Halton Hills";},
"portcoquitlam": function() {return "Port Coquitlam";},
"sainthyacinthe": function() {return "Saint-Hyacinthe";},
"northbay": function() {return "North Bay";},
"dollarddesormeaux": function() {return "Dollard-Des Ormeaux";},
"whitchurchstouffville": function() {return "Whitchurch-Stouffville";},
"haldimandcounty": function() {return "Haldimand County";},
"sainteustache": function() {return "Saint-Eustache";},
"quintewest": function() {return "Quinte West";},
"westvancouver": function() {return "West Vancouver";},
"rouynnoranda": function() {return "Rouyn-Noranda";},
"salaberrydevalleyfield": function() {return "Salaberry-de-Valleyfield";},
"rockyviewcounty": function() {return "Rocky View County";},
"stthomas": function() {return "St. Thomas";},
"vaudreuildorion": function() {return "Vaudreuil-Dorion";},
"princealbert": function() {return "Prince Albert";},
"bradfordwestgwillimbury": function() {return "Bradford West Gwillimbury";},
"soreltracy": function() {return "Sorel-Tracy";},
"newtecumseth": function() {return "New Tecumseth";},
"sprucegrove": function() {return "Spruce Grove";},
"moosejaw": function() {return "Moose Jaw";},
"portmoody": function() {return "Port Moody";},
"westkelowna": function() {return "West Kelowna";},
"campbellriver": function() {return "Campbell River";},
"saintgeorges": function() {return "Saint-Georges";},
"valdor": function() {return "Val-d'Or";},
"parklandcounty": function() {return "Parkland County";},
"pointeclaire": function() {return "Pointe-Claire";},
"forterie": function() {return "Fort Erie";},
"saintejulie": function() {return "Sainte-Julie";},
"northcowichan": function() {return "North Cowichan";},
"centrewellington": function() {return "Centre Wellington";},
"saintconstant": function() {return "Saint-Constant";},
"saintbrunodemontarville": function() {return "Saint-Bruno-de-Montarville";},
"conceptionbaysouth": function() {return "Conception Bay South";},
"saintetherese": function() {return "Sainte-Therese";},
"thetfordmines": function() {return "Thetford Mines";},
"princeedwardcounty": function() {return "Prince Edward County";},
"clarencerockland": function() {return "Clarence-Rockland";},
"fortsaskatchewan": function() {return "Fort Saskatchewan";},
"laprairie": function() {return "La Prairie";},
"eastgwillimbury": function() {return "East Gwillimbury";},
"mountpearl": function() {return "Mount Pearl";},
"foothillsno31": function() {return "Foothills No. 31";},
"easthants": function() {return "East Hants";},
"grandeprairiecountyno1": function() {return "Grande Prairie County No. 1";},
"saintlambert": function() {return "Saint-Lambert";},
"baiecomeau": function() {return "Baie-Comeau";},
"owensound": function() {return "Owen Sound";},
"oromedonte": function() {return "Oro-Medonte";},
"strathroycaradoc": function() {return "Strathroy-Caradoc";},
"saintlinlaurentides": function() {return "Saint-Lin-Laurentides";},
"wasagabeach": function() {return "Wasaga Beach";},
"sturgeoncounty": function() {return "Sturgeon County";},
"montroyal": function() {return "Mont-Royal";},
"fortstjohn": function() {return "Fort St. John";},
"whiterock": function() {return "White Rock";},
"saintlazare": function() {return "Saint-Lazare";},
"cornerbrook": function() {return "Corner Brook";},
"reddeercounty": function() {return "Red Deer County";},
"saintaugustindedesmaures": function() {return "Saint-Augustin-de-Desmaures";},
"southfrontenac": function() {return "South Frontenac";},
"montsainthilaire": function() {return "Mont-Saint-Hilaire";},
"pittmeadows": function() {return "Pitt Meadows";},
"portcolborne": function() {return "Port Colborne";},
"oakbay": function() {return "Oak Bay";},
"saintemarthesurlelac": function() {return "Sainte-Marthe-sur-le-Lac";},
"salmonarm": function() {return "Salmon Arm";},
"portalberni": function() {return "Port Alberni";},
"niagaraonthelake": function() {return "Niagara-on-the-Lake";},
"deuxmontagnes": function() {return "Deux-Montagnes";},
"middlesexcentre": function() {return "Middlesex Centre";},
"stonyplain": function() {return "Stony Plain";},
"saintbasilelegrand": function() {return "Saint-Basile-le-Grand";},
"saintecatherine": function() {return "Sainte-Catherine";},
"centralsaanich": function() {return "Central Saanich";},
"porthope": function() {return "Port Hope";},
"swiftcurrent": function() {return "Swift Current";},
"northgrenville": function() {return "North Grenville";},
"greatervancouvera": function() {return "Greater Vancouver A";},
"saintcolomban": function() {return "Saint-Colomban";},
"greaternapanee": function() {return "Greater Napanee";},
"saintesophie": function() {return "Sainte-Sophie";},
"westhants": function() {return "West Hants";},
"coldlake": function() {return "Cold Lake";},
"sylvanlake": function() {return "Sylvan Lake";},
"westlincoln": function() {return "West Lincoln";},
"sainteannedesplaines": function() {return "Sainte-Anne-des-Plaines";},
"westnipissing": function() {return "West Nipissing";},
"northbattleford": function() {return "North Battleford";},
"dolbeaumistassini": function() {return "Dolbeau-Mistassini";},
"grandfallswindsor": function() {return "Grand Falls-Windsor";},
"montlaurier": function() {return "Mont-Laurier";},
"stclair": function() {return "St. Clair";},
"saintcharlesborromee": function() {return "Saint-Charles-Borromee";},
"leduccounty": function() {return "Leduc County";},
"saugeenshores": function() {return "Saugeen Shores";},
"highriver": function() {return "High River";},
"bonnyvilleno87": function() {return "Bonnyville No. 87";},
"saintemarie": function() {return "Sainte-Marie";},
"portagelaprairie": function() {return "Portage la Prairie";},
"thamescentre": function() {return "Thames Centre";},
"mississippimills": function() {return "Mississippi Mills";},
"powellriver": function() {return "Powell River";},
"southglengarry": function() {return "South Glengarry";},
"northperth": function() {return "North Perth";},
"southstormont": function() {return "South Stormont";},
"mountainviewcounty": function() {return "Mountain View County";},
"lakecountry": function() {return "Lake Country";},
"sainteadele": function() {return "Sainte-Adele";},
"trenthills": function() {return "Trent Hills";},
"thenation": function() {return "The Nation";},
"centralelgin": function() {return "Central Elgin";},
"westgrey": function() {return "West Grey";},
"pertheast": function() {return "Perth East";},
"princerupert": function() {return "Prince Rupert";},
"dawsoncreek": function() {return "Dawson Creek";},
"saintamable": function() {return "Saint-Amable";},
"clearwatercounty": function() {return "Clearwater County";},
"wellingtonnorth": function() {return "Wellington North";},
"standrews": function() {return "St. Andrews";},
"valdesmonts": function() {return "Val-des-Monts";},
"northdundas": function() {return "North Dundas";},
"northsaanich": function() {return "North Saanich";},
"wetaskiwincountyno10": function() {return "Wetaskiwin County No. 10";},
"mackenziecounty": function() {return "Mackenzie County";},
"latuque": function() {return "La Tuque";},
"yellowheadcounty": function() {return "Yellowhead County";},
"adjalatosorontio": function() {return "Adjala-Tosorontio";},
"lacsteannecounty": function() {return "Lac Ste. Anne County";},
"stclements": function() {return "St. Clements";},
"southdundas": function() {return "South Dundas";},
"williamslake": function() {return "Williams Lake";},
"elliotlake": function() {return "Elliot Lake";},
"notredamedelileperrot": function() {return "Notre-Dame-de-l'Ile-Perrot";},
"carletonplace": function() {return "Carleton Place";},
"lambtonshores": function() {return "Lambton Shores";},
"saltspringisland": function() {return "Saltspring Island";},
"georgianbluffs": function() {return "Georgian Bluffs";},
"viewroyal": function() {return "View Royal";},
"lethbridgecounty": function() {return "Lethbridge County";},
"lacombecounty": function() {return "Lacombe County";},
"rideaulakes": function() {return "Rideau Lakes";},
"saintfelicien": function() {return "Saint-Felicien";},
"saintsauveur": function() {return "Saint-Sauveur";},
"sainteagathedesmonts": function() {return "Sainte-Agathe-des-Monts";},
"saintraymond": function() {return "Saint-Raymond";},
"northdumfries": function() {return "North Dumfries";},
"northglengarry": function() {return "North Glengarry";},
"southhuron": function() {return "South Huron";},
"saintejulienne": function() {return "Sainte-Julienne";},
"temiskamingshores": function() {return "Temiskaming Shores";},
"elizabethtownkitley": function() {return "Elizabethtown-Kitley";},
"ponokacounty": function() {return "Ponoka County";},
"greyhighlands": function() {return "Grey Highlands";},
"alfredandplantagenet": function() {return "Alfred and Plantagenet";},
"monttremblant": function() {return "Mont-Tremblant";},
"boisdesfilion": function() {return "Bois-des-Filion";},
"leedsandthethousandislands": function() {return "Leeds and the Thousand Islands";},
"laurentianvalley": function() {return "Laurentian Valley";},
"eaststpaul": function() {return "East St. Paul";},
"notredamedesprairies": function() {return "Notre-Dame-des-Prairies";},
"pontrouge": function() {return "Pont-Rouge";},
"huroneast": function() {return "Huron East";},
"sainthippolyte": function() {return "Saint-Hippolyte";},
"newglasgow": function() {return "New Glasgow";},
"qualicumbeach": function() {return "Qualicum Beach";},
"westperth": function() {return "West Perth";},
"cavanmonaghan": function() {return "Cavan Monaghan";},
"wheatlandcounty": function() {return "Wheatland County";},
"smithsfalls": function() {return "Smiths Falls";},
"comoxvalleycpuntledgeblackcreek": function() {return "Comox Valley C (Puntledge - Black Creek)";},
"cormanparkno344": function() {return "Corman Park No. 344";},
"cowichanvalleyb": function() {return "Cowichan Valley B";},
"camrosecounty": function() {return "Camrose County";},
"otterburnpark": function() {return "Otterburn Park";},
"southbrucepeninsula": function() {return "South Bruce Peninsula";},
"stonehamettewkesbury": function() {return "Stoneham-et-Tewkesbury";},
"laclabichecounty": function() {return "Lac la Biche County";},
"lamalbaie": function() {return "La Malbaie";},
"vermilionrivercounty": function() {return "Vermilion River County";},
"portugalcovestphilips": function() {return "Portugal Cove-St. Philip's";},
"happyvalleygoosebay": function() {return "Happy Valley-Goose Bay";},
"saintremi": function() {return "Saint-Remi";},
"kirklandlake": function() {return "Kirkland Lake";},
"saintzotique": function() {return "Saint-Zotique";},
"columbiashuswapc": function() {return "Columbia-Shuswap C";},
"athabascacounty": function() {return "Athabasca County";},
"lapeche": function() {return "La Peche";},
"lacbeauport": function() {return "Lac-Beauport";},
"plymptonwyoming": function() {return "Plympton-Wyoming";},
"brazeaucounty": function() {return "Brazeau County";},
"fortfrances": function() {return "Fort Frances";},
"nanaimof": function() {return "Nanaimo F";},
"saintecatherinedelajacquescartier": function() {return "Sainte-Catherine-de-la-Jacques-Cartier";},
"stonemills": function() {return "Stone Mills";},
"southwestoxford": function() {return "South-West Oxford";},
"cypresscounty": function() {return "Cypress County";},
"actonvale": function() {return "Acton Vale";},
"tsinstikeptum9": function() {return "Tsinstikeptum  9";},
"centralhuron": function() {return "Central Huron";},
"newellcounty": function() {return "Newell County";},
"nanaimog": function() {return "Nanaimo G";},
"blandfordblenheim": function() {return "Blandford-Blenheim";},
"saintebrigittedelaval": function() {return "Sainte-Brigitte-de-Laval";},
"lasarre": function() {return "La Sarre";},
"stmarys": function() {return "St. Marys";},
"draytonvalley": function() {return "Drayton Valley";},
"labradorcity": function() {return "Labrador City";},
"westlockcounty": function() {return "Westlock County";},
"comoxvalleya": function() {return "Comox Valley A";},
"baiesaintpaul": function() {return "Baie-Saint-Paul";},
"eastzorratavistock": function() {return "East Zorra-Tavistock";},
"brownsburgchatham": function() {return "Brownsburg-Chatham";},
"comoxvalleyblazonorth": function() {return "Comox Valley B (Lazo North)";},
"huronkinloss": function() {return "Huron-Kinloss";},
"nanaimoa": function() {return "Nanaimo A";},
"coteaudulac": function() {return "Coteau-du-Lac";},
"thebluemountains": function() {return "The Blue Mountains";},
"whitewaterregion": function() {return "Whitewater Region";},
"northstormont": function() {return "North Stormont";},
"peaceriver": function() {return "Peace River";},
"arranelderslie": function() {return "Arran-Elderslie";},
"portcartier": function() {return "Port-Cartier";},
"lescedres": function() {return "Les Cedres";},
"peaceriverc": function() {return "Peace River C";},
"dourodummer": function() {return "Douro-Dummer";},
"saintjosephdulac": function() {return "Saint-Joseph-du-Lac";},
"otonabeesouthmonaghan": function() {return "Otonabee-South Monaghan";},
"slavelake": function() {return "Slave Lake";},
"saintlambertdelauzon": function() {return "Saint-Lambert-de-Lauzon";},
"rockymountainhouse": function() {return "Rocky Mountain House";},
"muskokalakes": function() {return "Muskoka Lakes";},
"sainteannedesmonts": function() {return "Sainte-Anne-des-Monts";},
"pointecalumet": function() {return "Pointe-Calumet";},
"parrysound": function() {return "Parry Sound";},
"beaubassineast": function() {return "Beaubassin East";},
"northmiddlesex": function() {return "North Middlesex";},
"saintphilippe": function() {return "Saint-Philippe";},
"saintfelixdevalois": function() {return "Saint-Felix-de-Valois";},
"barrheadcountyno11": function() {return "Barrhead County No. 11";},
"montjoli": function() {return "Mont-Joli";},
"dysartetal": function() {return "Dysart et al";},
"caribooa": function() {return "Cariboo A";},
"nanaimoe": function() {return "Nanaimo E";},
"saintapollinaire": function() {return "Saint-Apollinaire";},
"mindenhills": function() {return "Minden Hills";},
"labroquerie": function() {return "La Broquerie";},
"saintcalixte": function() {return "Saint-Calixte";},
"eastkootenayc": function() {return "East Kootenay C";},
"stpaulcountyno19": function() {return "St. Paul County No. 19";},
"bayroberts": function() {return "Bay Roberts";},
"oliverpaipoonge": function() {return "Oliver Paipoonge";},
"peaceriverd": function() {return "Peace River D";},
"beavercounty": function() {return "Beaver County";},
"saintpaul": function() {return "Saint-Paul";},
"saintcesaire": function() {return "Saint-Cesaire";},
"okanagansimilkameend": function() {return "Okanagan-Similkameen D";},
"thunderbayunorganized": function() {return "Thunder Bay, Unorganized";},
"stpaul": function() {return "St. Paul";},
"sainthonore": function() {return "Saint-Honore";},
"notredamedumontcarmel": function() {return "Notre-Dame-du-Mont-Carmel";},
"southwestmiddlesex": function() {return "Southwest Middlesex";},
"biglakescounty": function() {return "Big Lakes County";},
"tayvalley": function() {return "Tay Valley";},
"lacmegantic": function() {return "Lac-Megantic";},
"southbruce": function() {return "South Bruce";},
"peaceriverb": function() {return "Peace River B";},
"sainthenri": function() {return "Saint-Henri";},
"saintpie": function() {return "Saint-Pie";},
"crowsnestpass": function() {return "Crowsnest Pass";},
"greenviewno16": function() {return "Greenview No. 16";},
"lacbrome": function() {return "Lac-Brome";},
"saintemartine": function() {return "Sainte-Martine";},
"ashfieldcolbornewawanosh": function() {return "Ashfield-Colborne-Wawanosh";},
"trentlakes": function() {return "Trent Lakes";},
"cookshireeaton": function() {return "Cookshire-Eaton";},
"thepas": function() {return "The Pas";},
"lescoteaux": function() {return "Les Coteaux";},
"weststpaul": function() {return "West St. Paul";},
"meadowlake": function() {return "Meadow Lake";},
"lanarkhighlands": function() {return "Lanark Highlands";},
"grandfalls": function() {return "Grand Falls";},
"stettlercountyno6": function() {return "Stettler County No. 6";},
"siouxlookout": function() {return "Sioux Lookout";},
"bulkleynechakoa": function() {return "Bulkley-Nechako A";},
"deerlake": function() {return "Deer Lake";},
"willowcreekno26": function() {return "Willow Creek No. 26";},
"cariboog": function() {return "Cariboo G";},
"saintrochdelachigan": function() {return "Saint-Roch-de-l'Achigan";},
"cowichanvalleyc": function() {return "Cowichan Valley C";},
"steanne": function() {return "Ste. Anne";},
"kneehillcounty": function() {return "Kneehill County";},

};