var lookupTable = {

// USA

"al": function() {return "Alabama";},
"ak": function() {return "Alaska";},
"az": function() {return "Arizona";},
"ar": function() {return "Arkansas";},
"ca": function() {return "California";},
"co": function() {return "Colorado";},
"ct": function() {return "Connecticut";},
"de": function() {return "Delaware";},
"dc": function() {return "District of Columbia";},
"fl": function() {return "Florida";},
"ga": function() {return "Georgia";},
"hi": function() {return "Hawaii";},
"id": function() {return "Idaho";},
"il": function() {return "Illinois";},
"in": function() {return "Indiana";},
"ia": function() {return "Iowa";},
"ks": function() {return "Kansas";},
"ky": function() {return "Kentucky";},
"la": function() {return "Louisiana";},
"me": function() {return "Maine";},
"md": function() {return "Maryland";},
"ma": function() {return "Massachusetts";},
"mi": function() {return "Michigan";},
"mn": function() {return "Minnesota";},
"ms": function() {return "Mississippi";},
"mo": function() {return "Missouri";},
"mt": function() {return "Montana";},
"ne": function() {return "Nebraska";},
"nv": function() {return "Nevada";},
"nh": function() {return "New Hampshire";},
"nj": function() {return "New Jersey";},
"nm": function() {return "New Mexico";},
"ny": function() {return "New York";},
"nc": function() {return "North Carolina";},
"nd": function() {return "North Dakota";},
"oh": function() {return "Ohio";},
"ok": function() {return "Oklahoma";},
"or": function() {return "Oregon";},
"pa": function() {return "Pennsylvania";},
"ri": function() {return "Rhode Island";},
"sc": function() {return "South Carolina";},
"sd": function() {return "South Dakota";},
"tn": function() {return "Tennessee";},
"tx": function() {return "Texas";},
"ut": function() {return "Utah";},
"vt": function() {return "Vermont";},
"va": function() {return "Virginia";},
"wa": function() {return "Washington";},
"wv": function() {return "West Virginia";},
"wi": function() {return "Wisconsin";},
"wy": function() {return "Wyoming";},

// CANADA

"ab": function() {return "Alberta";},
"bc": function() {return "British Columbia";},
"mb": function() {return "Manitoba";},
"nb": function() {return "New Brunswick";},
"nl": function() {return "Newfoundland and Labrador";},
"ns": function() {return "Nova Scotia";},
"nt": function() {return "Northwest Territories";},
"nu": function() {return "Nunavut";},
"on": function() {return "Ontario";},
"pe": function() {return "Prince Edward Island";},
"qc": function() {return "Quebec";},
"sk": function() {return "Saskatchewan";},
"yt": function() {return "Yukon";},

};