var suggestions = [

{ 'value': 'autaugaal', 'label': 'Autauga, Alabama' },
{ 'value': 'baldwinal', 'label': 'Baldwin, Alabama' },
{ 'value': 'barboural', 'label': 'Barbour, Alabama' },
{ 'value': 'bibbal', 'label': 'Bibb, Alabama' },
{ 'value': 'blountal', 'label': 'Blount, Alabama' },
{ 'value': 'bullockal', 'label': 'Bullock, Alabama' },
{ 'value': 'butleral', 'label': 'Butler, Alabama' },
{ 'value': 'calhounal', 'label': 'Calhoun, Alabama' },
{ 'value': 'chambersal', 'label': 'Chambers, Alabama' },
{ 'value': 'cherokeeal', 'label': 'Cherokee, Alabama' },
{ 'value': 'chiltonal', 'label': 'Chilton, Alabama' },
{ 'value': 'choctawal', 'label': 'Choctaw, Alabama' },
{ 'value': 'clarkeal', 'label': 'Clarke, Alabama' },
{ 'value': 'clayal', 'label': 'Clay, Alabama' },
{ 'value': 'cleburneal', 'label': 'Cleburne, Alabama' },
{ 'value': 'coffeeal', 'label': 'Coffee, Alabama' },
{ 'value': 'colbertal', 'label': 'Colbert, Alabama' },
{ 'value': 'conecuhal', 'label': 'Conecuh, Alabama' },
{ 'value': 'coosaal', 'label': 'Coosa, Alabama' },
{ 'value': 'covingtonal', 'label': 'Covington, Alabama' },
{ 'value': 'crenshawal', 'label': 'Crenshaw, Alabama' },
{ 'value': 'cullmanal', 'label': 'Cullman, Alabama' },
{ 'value': 'daleal', 'label': 'Dale, Alabama' },
{ 'value': 'dallasal', 'label': 'Dallas, Alabama' },
{ 'value': 'dekalbal', 'label': 'DeKalb, Alabama' },
{ 'value': 'elmoreal', 'label': 'Elmore, Alabama' },
{ 'value': 'escambiaal', 'label': 'Escambia, Alabama' },
{ 'value': 'etowahal', 'label': 'Etowah, Alabama' },
{ 'value': 'fayetteal', 'label': 'Fayette, Alabama' },
{ 'value': 'franklinal', 'label': 'Franklin, Alabama' },
{ 'value': 'genevaal', 'label': 'Geneva, Alabama' },
{ 'value': 'greeneal', 'label': 'Greene, Alabama' },
{ 'value': 'haleal', 'label': 'Hale, Alabama' },
{ 'value': 'henryal', 'label': 'Henry, Alabama' },
{ 'value': 'houstonal', 'label': 'Houston, Alabama' },
{ 'value': 'jacksonal', 'label': 'Jackson, Alabama' },
{ 'value': 'jeffersonal', 'label': 'Jefferson, Alabama' },
{ 'value': 'lamaral', 'label': 'Lamar, Alabama' },
{ 'value': 'lauderdaleal', 'label': 'Lauderdale, Alabama' },
{ 'value': 'lawrenceal', 'label': 'Lawrence, Alabama' },
{ 'value': 'leeal', 'label': 'Lee, Alabama' },
{ 'value': 'limestoneal', 'label': 'Limestone, Alabama' },
{ 'value': 'lowndesal', 'label': 'Lowndes, Alabama' },
{ 'value': 'maconal', 'label': 'Macon, Alabama' },
{ 'value': 'madisonal', 'label': 'Madison, Alabama' },
{ 'value': 'marengoal', 'label': 'Marengo, Alabama' },
{ 'value': 'marional', 'label': 'Marion, Alabama' },
{ 'value': 'marshallal', 'label': 'Marshall, Alabama' },
{ 'value': 'mobileal', 'label': 'Mobile, Alabama' },
{ 'value': 'monroeal', 'label': 'Monroe, Alabama' },
{ 'value': 'montgomeryal', 'label': 'Montgomery, Alabama' },
{ 'value': 'morganal', 'label': 'Morgan, Alabama' },
{ 'value': 'perryal', 'label': 'Perry, Alabama' },
{ 'value': 'pickensal', 'label': 'Pickens, Alabama' },
{ 'value': 'pikeal', 'label': 'Pike, Alabama' },
{ 'value': 'randolphal', 'label': 'Randolph, Alabama' },
{ 'value': 'russellal', 'label': 'Russell, Alabama' },
{ 'value': 'shelbyal', 'label': 'Shelby, Alabama' },
{ 'value': 'stclairal', 'label': 'St. Clair, Alabama' },
{ 'value': 'sumteral', 'label': 'Sumter, Alabama' },
{ 'value': 'talladegaal', 'label': 'Talladega, Alabama' },
{ 'value': 'tallapoosaal', 'label': 'Tallapoosa, Alabama' },
{ 'value': 'tuscaloosaal', 'label': 'Tuscaloosa, Alabama' },
{ 'value': 'walkeral', 'label': 'Walker, Alabama' },
{ 'value': 'washingtonal', 'label': 'Washington , Alabama' },
{ 'value': 'wilcoxal', 'label': 'Wilcox, Alabama' },
{ 'value': 'winstonal', 'label': 'Winston, Alabama' },

{ 'value': 'aleutianseastak', 'label': 'Aleutians East, Alaska' },
{ 'value': 'aleutianswestak', 'label': 'Aleutians West , Alaska' },
{ 'value': 'anchorageak', 'label': 'Anchorage, Alaska' },
{ 'value': 'bethelak', 'label': 'Bethel , Alaska' },
{ 'value': 'bristolbayak', 'label': 'Bristol Bay, Alaska' },
{ 'value': 'denaliak', 'label': 'Denali, Alaska' },
{ 'value': 'dillinghamak', 'label': 'Dillingham , Alaska' },
{ 'value': 'fairbanksnorthstarak', 'label': 'Fairbanks North Star, Alaska' },
{ 'value': 'hainesak', 'label': 'Haines, Alaska' },
{ 'value': 'hoonahangoonak', 'label': 'Hoonah-Angoon , Alaska' },
{ 'value': 'juneauak', 'label': 'Juneau, Alaska' },
{ 'value': 'kenaipeninsulaak', 'label': 'Kenai Peninsula, Alaska' },
{ 'value': 'ketchikangatewayak', 'label': 'Ketchikan Gateway, Alaska' },
{ 'value': 'kodiakislandak', 'label': 'Kodiak Island, Alaska' },
{ 'value': 'kusilvakak', 'label': 'Kusilvak , Alaska' },
{ 'value': 'lakeandpeninsulaak', 'label': 'Lake and Peninsula, Alaska' },
{ 'value': 'matanuskasusitnaak', 'label': 'Matanuska-Susitna, Alaska' },
{ 'value': 'nomeak', 'label': 'Nome , Alaska' },
{ 'value': 'northslopeak', 'label': 'North Slope, Alaska' },
{ 'value': 'northwestarcticak', 'label': 'Northwest Arctic, Alaska' },
{ 'value': 'petersburgak', 'label': 'Petersburg , Alaska' },
{ 'value': 'princeofwaleshyderak', 'label': 'Prince of Wales-Hyder , Alaska' },
{ 'value': 'sitkaak', 'label': 'Sitka, Alaska' },
{ 'value': 'skagwayak', 'label': 'Skagway, Alaska' },
{ 'value': 'southeastfairbanksak', 'label': 'Southeast Fairbanks , Alaska' },
{ 'value': 'valdezcordovaak', 'label': 'Valdez-Cordova , Alaska' },
{ 'value': 'wrangellak', 'label': 'Wrangell, Alaska' },
{ 'value': 'yakutatak', 'label': 'Yakutat, Alaska' },
{ 'value': 'yukonkoyukukak', 'label': 'Yukon-Koyukuk , Alaska' },
{ 'value': 'apacheaz', 'label': 'Apache, Arizona' },
{ 'value': 'cochiseaz', 'label': 'Cochise, Arizona' },
{ 'value': 'coconinoaz', 'label': 'Coconino, Arizona' },
{ 'value': 'gilaaz', 'label': 'Gila, Arizona' },
{ 'value': 'grahamaz', 'label': 'Graham, Arizona' },
{ 'value': 'greenleeaz', 'label': 'Greenlee, Arizona' },
{ 'value': 'lapazaz', 'label': 'La Paz, Arizona' },
{ 'value': 'maricopaaz', 'label': 'Maricopa, Arizona' },
{ 'value': 'mohaveaz', 'label': 'Mohave, Arizona' },
{ 'value': 'navajoaz', 'label': 'Navajo, Arizona' },
{ 'value': 'pimaaz', 'label': 'Pima, Arizona' },
{ 'value': 'pinalaz', 'label': 'Pinal, Arizona' },
{ 'value': 'santacruzaz', 'label': 'Santa Cruz, Arizona' },
{ 'value': 'yavapaiaz', 'label': 'Yavapai, Arizona' },
{ 'value': 'yumaaz', 'label': 'Yuma, Arizona' },
{ 'value': 'arkansasar', 'label': 'Arkansas , Arkansas' },
{ 'value': 'ashleyar', 'label': 'Ashley, Arkansas' },
{ 'value': 'baxterar', 'label': 'Baxter, Arkansas' },
{ 'value': 'bentonar', 'label': 'Benton, Arkansas' },
{ 'value': 'boonear', 'label': 'Boone, Arkansas' },
{ 'value': 'bradleyar', 'label': 'Bradley, Arkansas' },
{ 'value': 'calhounar', 'label': 'Calhoun, Arkansas' },
{ 'value': 'carrollar', 'label': 'Carroll, Arkansas' },
{ 'value': 'chicotar', 'label': 'Chicot, Arkansas' },
{ 'value': 'clarkar', 'label': 'Clark, Arkansas' },
{ 'value': 'clayar', 'label': 'Clay, Arkansas' },
{ 'value': 'cleburnear', 'label': 'Cleburne, Arkansas' },
{ 'value': 'clevelandar', 'label': 'Cleveland, Arkansas' },
{ 'value': 'columbiaar', 'label': 'Columbia, Arkansas' },
{ 'value': 'conwayar', 'label': 'Conway, Arkansas' },
{ 'value': 'craigheadar', 'label': 'Craighead, Arkansas' },
{ 'value': 'crawfordar', 'label': 'Crawford, Arkansas' },
{ 'value': 'crittendenar', 'label': 'Crittenden, Arkansas' },
{ 'value': 'crossar', 'label': 'Cross, Arkansas' },
{ 'value': 'dallasar', 'label': 'Dallas, Arkansas' },
{ 'value': 'deshaar', 'label': 'Desha, Arkansas' },
{ 'value': 'drewar', 'label': 'Drew, Arkansas' },
{ 'value': 'faulknerar', 'label': 'Faulkner, Arkansas' },
{ 'value': 'franklinar', 'label': 'Franklin, Arkansas' },
{ 'value': 'fultonar', 'label': 'Fulton, Arkansas' },
{ 'value': 'garlandar', 'label': 'Garland, Arkansas' },
{ 'value': 'grantar', 'label': 'Grant, Arkansas' },
{ 'value': 'greenear', 'label': 'Greene, Arkansas' },
{ 'value': 'hempsteadar', 'label': 'Hempstead, Arkansas' },
{ 'value': 'hotspringar', 'label': 'Hot Spring, Arkansas' },
{ 'value': 'howardar', 'label': 'Howard, Arkansas' },
{ 'value': 'independencear', 'label': 'Independence, Arkansas' },
{ 'value': 'izardar', 'label': 'Izard, Arkansas' },
{ 'value': 'jacksonar', 'label': 'Jackson, Arkansas' },
{ 'value': 'jeffersonar', 'label': 'Jefferson, Arkansas' },
{ 'value': 'johnsonar', 'label': 'Johnson, Arkansas' },
{ 'value': 'lafayettear', 'label': 'Lafayette, Arkansas' },
{ 'value': 'lawrencear', 'label': 'Lawrence, Arkansas' },
{ 'value': 'leear', 'label': 'Lee, Arkansas' },
{ 'value': 'lincolnar', 'label': 'Lincoln, Arkansas' },
{ 'value': 'littleriverar', 'label': 'Little River, Arkansas' },
{ 'value': 'loganar', 'label': 'Logan, Arkansas' },
{ 'value': 'lonokear', 'label': 'Lonoke, Arkansas' },
{ 'value': 'madisonar', 'label': 'Madison, Arkansas' },
{ 'value': 'marionar', 'label': 'Marion, Arkansas' },
{ 'value': 'millerar', 'label': 'Miller, Arkansas' },
{ 'value': 'mississippiar', 'label': 'Mississippi , Arkansas' },
{ 'value': 'monroear', 'label': 'Monroe, Arkansas' },
{ 'value': 'montgomeryar', 'label': 'Montgomery, Arkansas' },
{ 'value': 'nevadaar', 'label': 'Nevada , Arkansas' },
{ 'value': 'newtonar', 'label': 'Newton, Arkansas' },
{ 'value': 'ouachitaar', 'label': 'Ouachita, Arkansas' },
{ 'value': 'perryar', 'label': 'Perry, Arkansas' },
{ 'value': 'phillipsar', 'label': 'Phillips, Arkansas' },
{ 'value': 'pikear', 'label': 'Pike, Arkansas' },
{ 'value': 'poinsettar', 'label': 'Poinsett, Arkansas' },
{ 'value': 'polkar', 'label': 'Polk, Arkansas' },
{ 'value': 'popear', 'label': 'Pope, Arkansas' },
{ 'value': 'prairiear', 'label': 'Prairie, Arkansas' },
{ 'value': 'pulaskiar', 'label': 'Pulaski, Arkansas' },
{ 'value': 'randolphar', 'label': 'Randolph, Arkansas' },
{ 'value': 'salinear', 'label': 'Saline, Arkansas' },
{ 'value': 'scottar', 'label': 'Scott, Arkansas' },
{ 'value': 'searcyar', 'label': 'Searcy, Arkansas' },
{ 'value': 'sebastianar', 'label': 'Sebastian, Arkansas' },
{ 'value': 'sevierar', 'label': 'Sevier, Arkansas' },
{ 'value': 'sharpar', 'label': 'Sharp, Arkansas' },
{ 'value': 'stfrancisar', 'label': 'St. Francis, Arkansas' },
{ 'value': 'stonear', 'label': 'Stone, Arkansas' },
{ 'value': 'unionar', 'label': 'Union, Arkansas' },
{ 'value': 'vanburenar', 'label': 'Van Buren, Arkansas' },
{ 'value': 'washingtonar', 'label': 'Washington , Arkansas' },
{ 'value': 'whitear', 'label': 'White, Arkansas' },
{ 'value': 'woodruffar', 'label': 'Woodruff, Arkansas' },
{ 'value': 'yellar', 'label': 'Yell, Arkansas' },





];