var suggestions = [

{ 'value': 'autaugaal', 'label': 'Autauga, Alabama' },
{ 'value': 'baldwinal', 'label': 'Baldwin, Alabama' },
{ 'value': 'barboural', 'label': 'Barbour, Alabama' },
{ 'value': 'bibbal', 'label': 'Bibb, Alabama' },
{ 'value': 'blountal', 'label': 'Blount, Alabama' },
{ 'value': 'bullockal', 'label': 'Bullock, Alabama' },
{ 'value': 'butleral', 'label': 'Butler, Alabama' },
{ 'value': 'calhounal', 'label': 'Calhoun, Alabama' },
{ 'value': 'chambersal', 'label': 'Chambers, Alabama' },
{ 'value': 'cherokeeal', 'label': 'Cherokee, Alabama' },
{ 'value': 'chiltonal', 'label': 'Chilton, Alabama' },
{ 'value': 'choctawal', 'label': 'Choctaw, Alabama' },
{ 'value': 'clarkeal', 'label': 'Clarke, Alabama' },
{ 'value': 'clayal', 'label': 'Clay, Alabama' },
{ 'value': 'cleburneal', 'label': 'Cleburne, Alabama' },
{ 'value': 'coffeeal', 'label': 'Coffee, Alabama' },
{ 'value': 'colbertal', 'label': 'Colbert, Alabama' },
{ 'value': 'conecuhal', 'label': 'Conecuh, Alabama' },
{ 'value': 'coosaal', 'label': 'Coosa, Alabama' },
{ 'value': 'covingtonal', 'label': 'Covington, Alabama' },
{ 'value': 'crenshawal', 'label': 'Crenshaw, Alabama' },
{ 'value': 'cullmanal', 'label': 'Cullman, Alabama' },
{ 'value': 'daleal', 'label': 'Dale, Alabama' },
{ 'value': 'dallasal', 'label': 'Dallas, Alabama' },
{ 'value': 'dekalbal', 'label': 'DeKalb, Alabama' },
{ 'value': 'elmoreal', 'label': 'Elmore, Alabama' },
{ 'value': 'escambiaal', 'label': 'Escambia, Alabama' },
{ 'value': 'etowahal', 'label': 'Etowah, Alabama' },
{ 'value': 'fayetteal', 'label': 'Fayette, Alabama' },
{ 'value': 'franklinal', 'label': 'Franklin, Alabama' },
{ 'value': 'genevaal', 'label': 'Geneva, Alabama' },
{ 'value': 'greeneal', 'label': 'Greene, Alabama' },
{ 'value': 'haleal', 'label': 'Hale, Alabama' },
{ 'value': 'henryal', 'label': 'Henry, Alabama' },
{ 'value': 'houstonal', 'label': 'Houston, Alabama' },
{ 'value': 'jacksonal', 'label': 'Jackson, Alabama' },
{ 'value': 'jeffersonal', 'label': 'Jefferson, Alabama' },
{ 'value': 'lamaral', 'label': 'Lamar, Alabama' },
{ 'value': 'lauderdaleal', 'label': 'Lauderdale, Alabama' },
{ 'value': 'lawrenceal', 'label': 'Lawrence, Alabama' },
{ 'value': 'leeal', 'label': 'Lee, Alabama' },
{ 'value': 'limestoneal', 'label': 'Limestone, Alabama' },
{ 'value': 'lowndesal', 'label': 'Lowndes, Alabama' },
{ 'value': 'maconal', 'label': 'Macon, Alabama' },
{ 'value': 'madisonal', 'label': 'Madison, Alabama' },
{ 'value': 'marengoal', 'label': 'Marengo, Alabama' },
{ 'value': 'marional', 'label': 'Marion, Alabama' },
{ 'value': 'marshallal', 'label': 'Marshall, Alabama' },
{ 'value': 'mobileal', 'label': 'Mobile, Alabama' },
{ 'value': 'monroeal', 'label': 'Monroe, Alabama' },
{ 'value': 'montgomeryal', 'label': 'Montgomery, Alabama' },
{ 'value': 'morganal', 'label': 'Morgan, Alabama' },
{ 'value': 'perryal', 'label': 'Perry, Alabama' },
{ 'value': 'pickensal', 'label': 'Pickens, Alabama' },
{ 'value': 'pikeal', 'label': 'Pike, Alabama' },
{ 'value': 'randolphal', 'label': 'Randolph, Alabama' },
{ 'value': 'russellal', 'label': 'Russell, Alabama' },
{ 'value': 'shelbyal', 'label': 'Shelby, Alabama' },
{ 'value': 'stclairal', 'label': 'St. Clair, Alabama' },
{ 'value': 'sumteral', 'label': 'Sumter, Alabama' },
{ 'value': 'talladegaal', 'label': 'Talladega, Alabama' },
{ 'value': 'tallapoosaal', 'label': 'Tallapoosa, Alabama' },
{ 'value': 'tuscaloosaal', 'label': 'Tuscaloosa, Alabama' },
{ 'value': 'walkeral', 'label': 'Walker, Alabama' },
{ 'value': 'washingtonal', 'label': 'Washington , Alabama' },
{ 'value': 'wilcoxal', 'label': 'Wilcox, Alabama' },
{ 'value': 'winstonal', 'label': 'Winston, Alabama' },

{ 'value': 'aleutianseastak', 'label': 'Aleutians East, Alaska' },
{ 'value': 'aleutianswestak', 'label': 'Aleutians West , Alaska' },
{ 'value': 'anchorageak', 'label': 'Anchorage, Alaska' },
{ 'value': 'bethelak', 'label': 'Bethel , Alaska' },
{ 'value': 'bristolbayak', 'label': 'Bristol Bay, Alaska' },
{ 'value': 'denaliak', 'label': 'Denali, Alaska' },
{ 'value': 'dillinghamak', 'label': 'Dillingham , Alaska' },
{ 'value': 'fairbanksnorthstarak', 'label': 'Fairbanks North Star, Alaska' },
{ 'value': 'hainesak', 'label': 'Haines, Alaska' },
{ 'value': 'hoonahangoonak', 'label': 'Hoonah-Angoon , Alaska' },
{ 'value': 'juneauak', 'label': 'Juneau, Alaska' },
{ 'value': 'kenaipeninsulaak', 'label': 'Kenai Peninsula, Alaska' },
{ 'value': 'ketchikangatewayak', 'label': 'Ketchikan Gateway, Alaska' },
{ 'value': 'kodiakislandak', 'label': 'Kodiak Island, Alaska' },
{ 'value': 'kusilvakak', 'label': 'Kusilvak , Alaska' },
{ 'value': 'lakeandpeninsulaak', 'label': 'Lake and Peninsula, Alaska' },
{ 'value': 'matanuskasusitnaak', 'label': 'Matanuska-Susitna, Alaska' },
{ 'value': 'nomeak', 'label': 'Nome , Alaska' },
{ 'value': 'northslopeak', 'label': 'North Slope, Alaska' },
{ 'value': 'northwestarcticak', 'label': 'Northwest Arctic, Alaska' },
{ 'value': 'petersburgak', 'label': 'Petersburg , Alaska' },
{ 'value': 'princeofwaleshyderak', 'label': 'Prince of Wales-Hyder , Alaska' },
{ 'value': 'sitkaak', 'label': 'Sitka, Alaska' },
{ 'value': 'skagwayak', 'label': 'Skagway, Alaska' },
{ 'value': 'southeastfairbanksak', 'label': 'Southeast Fairbanks , Alaska' },
{ 'value': 'valdezcordovaak', 'label': 'Valdez-Cordova , Alaska' },
{ 'value': 'wrangellak', 'label': 'Wrangell, Alaska' },
{ 'value': 'yakutatak', 'label': 'Yakutat, Alaska' },
{ 'value': 'yukonkoyukukak', 'label': 'Yukon-Koyukuk , Alaska' },
{ 'value': 'apacheaz', 'label': 'Apache, Arizona' },
{ 'value': 'cochiseaz', 'label': 'Cochise, Arizona' },
{ 'value': 'coconinoaz', 'label': 'Coconino, Arizona' },
{ 'value': 'gilaaz', 'label': 'Gila, Arizona' },
{ 'value': 'grahamaz', 'label': 'Graham, Arizona' },
{ 'value': 'greenleeaz', 'label': 'Greenlee, Arizona' },
{ 'value': 'lapazaz', 'label': 'La Paz, Arizona' },
{ 'value': 'maricopaaz', 'label': 'Maricopa, Arizona' },
{ 'value': 'mohaveaz', 'label': 'Mohave, Arizona' },
{ 'value': 'navajoaz', 'label': 'Navajo, Arizona' },
{ 'value': 'pimaaz', 'label': 'Pima, Arizona' },
{ 'value': 'pinalaz', 'label': 'Pinal, Arizona' },
{ 'value': 'santacruzaz', 'label': 'Santa Cruz, Arizona' },
{ 'value': 'yavapaiaz', 'label': 'Yavapai, Arizona' },
{ 'value': 'yumaaz', 'label': 'Yuma, Arizona' },
{ 'value': 'arkansasar', 'label': 'Arkansas , Arkansas' },
{ 'value': 'ashleyar', 'label': 'Ashley, Arkansas' },
{ 'value': 'baxterar', 'label': 'Baxter, Arkansas' },
{ 'value': 'bentonar', 'label': 'Benton, Arkansas' },
{ 'value': 'boonear', 'label': 'Boone, Arkansas' },
{ 'value': 'bradleyar', 'label': 'Bradley, Arkansas' },
{ 'value': 'calhounar', 'label': 'Calhoun, Arkansas' },
{ 'value': 'carrollar', 'label': 'Carroll, Arkansas' },
{ 'value': 'chicotar', 'label': 'Chicot, Arkansas' },
{ 'value': 'clarkar', 'label': 'Clark, Arkansas' },
{ 'value': 'clayar', 'label': 'Clay, Arkansas' },
{ 'value': 'cleburnear', 'label': 'Cleburne, Arkansas' },
{ 'value': 'clevelandar', 'label': 'Cleveland, Arkansas' },
{ 'value': 'columbiaar', 'label': 'Columbia, Arkansas' },
{ 'value': 'conwayar', 'label': 'Conway, Arkansas' },
{ 'value': 'craigheadar', 'label': 'Craighead, Arkansas' },
{ 'value': 'crawfordar', 'label': 'Crawford, Arkansas' },
{ 'value': 'crittendenar', 'label': 'Crittenden, Arkansas' },
{ 'value': 'crossar', 'label': 'Cross, Arkansas' },
{ 'value': 'dallasar', 'label': 'Dallas, Arkansas' },
{ 'value': 'deshaar', 'label': 'Desha, Arkansas' },
{ 'value': 'drewar', 'label': 'Drew, Arkansas' },
{ 'value': 'faulknerar', 'label': 'Faulkner, Arkansas' },
{ 'value': 'franklinar', 'label': 'Franklin, Arkansas' },
{ 'value': 'fultonar', 'label': 'Fulton, Arkansas' },
{ 'value': 'garlandar', 'label': 'Garland, Arkansas' },
{ 'value': 'grantar', 'label': 'Grant, Arkansas' },
{ 'value': 'greenear', 'label': 'Greene, Arkansas' },
{ 'value': 'hempsteadar', 'label': 'Hempstead, Arkansas' },
{ 'value': 'hotspringar', 'label': 'Hot Spring, Arkansas' },
{ 'value': 'howardar', 'label': 'Howard, Arkansas' },
{ 'value': 'independencear', 'label': 'Independence, Arkansas' },
{ 'value': 'izardar', 'label': 'Izard, Arkansas' },
{ 'value': 'jacksonar', 'label': 'Jackson, Arkansas' },
{ 'value': 'jeffersonar', 'label': 'Jefferson, Arkansas' },
{ 'value': 'johnsonar', 'label': 'Johnson, Arkansas' },
{ 'value': 'lafayettear', 'label': 'Lafayette, Arkansas' },
{ 'value': 'lawrencear', 'label': 'Lawrence, Arkansas' },
{ 'value': 'leear', 'label': 'Lee, Arkansas' },
{ 'value': 'lincolnar', 'label': 'Lincoln, Arkansas' },
{ 'value': 'littleriverar', 'label': 'Little River, Arkansas' },
{ 'value': 'loganar', 'label': 'Logan, Arkansas' },
{ 'value': 'lonokear', 'label': 'Lonoke, Arkansas' },
{ 'value': 'madisonar', 'label': 'Madison, Arkansas' },
{ 'value': 'marionar', 'label': 'Marion, Arkansas' },
{ 'value': 'millerar', 'label': 'Miller, Arkansas' },
{ 'value': 'mississippiar', 'label': 'Mississippi , Arkansas' },
{ 'value': 'monroear', 'label': 'Monroe, Arkansas' },
{ 'value': 'montgomeryar', 'label': 'Montgomery, Arkansas' },
{ 'value': 'nevadaar', 'label': 'Nevada , Arkansas' },
{ 'value': 'newtonar', 'label': 'Newton, Arkansas' },
{ 'value': 'ouachitaar', 'label': 'Ouachita, Arkansas' },
{ 'value': 'perryar', 'label': 'Perry, Arkansas' },
{ 'value': 'phillipsar', 'label': 'Phillips, Arkansas' },
{ 'value': 'pikear', 'label': 'Pike, Arkansas' },
{ 'value': 'poinsettar', 'label': 'Poinsett, Arkansas' },
{ 'value': 'polkar', 'label': 'Polk, Arkansas' },
{ 'value': 'popear', 'label': 'Pope, Arkansas' },
{ 'value': 'prairiear', 'label': 'Prairie, Arkansas' },
{ 'value': 'pulaskiar', 'label': 'Pulaski, Arkansas' },
{ 'value': 'randolphar', 'label': 'Randolph, Arkansas' },
{ 'value': 'salinear', 'label': 'Saline, Arkansas' },
{ 'value': 'scottar', 'label': 'Scott, Arkansas' },
{ 'value': 'searcyar', 'label': 'Searcy, Arkansas' },
{ 'value': 'sebastianar', 'label': 'Sebastian, Arkansas' },
{ 'value': 'sevierar', 'label': 'Sevier, Arkansas' },
{ 'value': 'sharpar', 'label': 'Sharp, Arkansas' },
{ 'value': 'stfrancisar', 'label': 'St. Francis, Arkansas' },
{ 'value': 'stonear', 'label': 'Stone, Arkansas' },
{ 'value': 'unionar', 'label': 'Union, Arkansas' },
{ 'value': 'vanburenar', 'label': 'Van Buren, Arkansas' },
{ 'value': 'washingtonar', 'label': 'Washington , Arkansas' },
{ 'value': 'whitear', 'label': 'White, Arkansas' },
{ 'value': 'woodruffar', 'label': 'Woodruff, Arkansas' },
{ 'value': 'yellar', 'label': 'Yell, Arkansas' },

{ 'value': 'alamedaca', 'label': 'Alameda, California' },
{ 'value': 'alpineca', 'label': 'Alpine, California' },
{ 'value': 'amadorca', 'label': 'Amador, California' },
{ 'value': 'butteca', 'label': 'Butte, California' },
{ 'value': 'calaverasca', 'label': 'Calaveras, California' },
{ 'value': 'colusaca', 'label': 'Colusa, California' },
{ 'value': 'contracostaca', 'label': 'Contra Costa, California' },
{ 'value': 'delnorteca', 'label': 'Del Norte, California' },
{ 'value': 'eldoradoca', 'label': 'El Dorado, California' },
{ 'value': 'fresnoca', 'label': 'Fresno, California' },
{ 'value': 'glennca', 'label': 'Glenn, California' },
{ 'value': 'humboldtca', 'label': 'Humboldt, California' },
{ 'value': 'imperialca', 'label': 'Imperial, California' },
{ 'value': 'inyoca', 'label': 'Inyo, California' },
{ 'value': 'kernca', 'label': 'Kern, California' },
{ 'value': 'kingsca', 'label': 'Kings, California' },
{ 'value': 'lakeca', 'label': 'Lake, California' },
{ 'value': 'lassenca', 'label': 'Lassen, California' },
{ 'value': 'losangelesca', 'label': 'Los Angeles, California' },
{ 'value': 'maderaca', 'label': 'Madera, California' },
{ 'value': 'marinca', 'label': 'Marin, California' },
{ 'value': 'mariposaca', 'label': 'Mariposa, California' },
{ 'value': 'mendocinoca', 'label': 'Mendocino, California' },
{ 'value': 'mercedca', 'label': 'Merced, California' },
{ 'value': 'modocca', 'label': 'Modoc, California' },
{ 'value': 'monoca', 'label': 'Mono, California' },
{ 'value': 'montereyca', 'label': 'Monterey, California' },
{ 'value': 'napaca', 'label': 'Napa, California' },
{ 'value': 'nevadaca', 'label': 'Nevada , California' },
{ 'value': 'orangeca', 'label': 'Orange, California' },
{ 'value': 'placerca', 'label': 'Placer, California' },
{ 'value': 'plumasca', 'label': 'Plumas, California' },
{ 'value': 'riversideca', 'label': 'Riverside, California' },
{ 'value': 'sacramentoca', 'label': 'Sacramento, California' },
{ 'value': 'sanbenitoca', 'label': 'San Benito, California' },
{ 'value': 'sanbernardinoca', 'label': 'San Bernardino, California' },
{ 'value': 'sandiegoca', 'label': 'San Diego, California' },
{ 'value': 'sanfranciscoca', 'label': 'San Francisco, California' },
{ 'value': 'sanjoaquinca', 'label': 'San Joaquin, California' },
{ 'value': 'sanluisobispoca', 'label': 'San Luis Obispo, California' },
{ 'value': 'sanmateoca', 'label': 'San Mateo, California' },
{ 'value': 'santabarbaraca', 'label': 'Santa Barbara, California' },
{ 'value': 'santaclaraca', 'label': 'Santa Clara, California' },
{ 'value': 'santacruzca', 'label': 'Santa Cruz, California' },
{ 'value': 'shastaca', 'label': 'Shasta, California' },
{ 'value': 'sierraca', 'label': 'Sierra, California' },
{ 'value': 'siskiyouca', 'label': 'Siskiyou, California' },
{ 'value': 'solanoca', 'label': 'Solano, California' },
{ 'value': 'sonomaca', 'label': 'Sonoma, California' },
{ 'value': 'stanislausca', 'label': 'Stanislaus, California' },
{ 'value': 'sutterca', 'label': 'Sutter, California' },
{ 'value': 'tehamaca', 'label': 'Tehama, California' },
{ 'value': 'trinityca', 'label': 'Trinity, California' },
{ 'value': 'tulareca', 'label': 'Tulare, California' },
{ 'value': 'tuolumneca', 'label': 'Tuolumne, California' },
{ 'value': 'venturaca', 'label': 'Ventura, California' },
{ 'value': 'yoloca', 'label': 'Yolo, California' },
{ 'value': 'yubaca', 'label': 'Yuba, California' },

{ 'value': 'adamsco', 'label': 'Adams, Colorado' },
{ 'value': 'alamosaco', 'label': 'Alamosa, Colorado' },
{ 'value': 'arapahoeco', 'label': 'Arapahoe, Colorado' },
{ 'value': 'archuletaco', 'label': 'Archuleta, Colorado' },
{ 'value': 'bacaco', 'label': 'Baca, Colorado' },
{ 'value': 'bentco', 'label': 'Bent, Colorado' },
{ 'value': 'boulderco', 'label': 'Boulder, Colorado' },
{ 'value': 'broomfieldco', 'label': 'Broomfield, Colorado' },
{ 'value': 'chaffeeco', 'label': 'Chaffee, Colorado' },
{ 'value': 'cheyenneco', 'label': 'Cheyenne, Colorado' },
{ 'value': 'clearcreekco', 'label': 'Clear Creek, Colorado' },
{ 'value': 'conejosco', 'label': 'Conejos, Colorado' },
{ 'value': 'costillaco', 'label': 'Costilla, Colorado' },
{ 'value': 'crowleyco', 'label': 'Crowley, Colorado' },
{ 'value': 'custerco', 'label': 'Custer, Colorado' },
{ 'value': 'deltaco', 'label': 'Delta, Colorado' },
{ 'value': 'denverco', 'label': 'Denver, Colorado' },
{ 'value': 'doloresco', 'label': 'Dolores, Colorado' },
{ 'value': 'douglasco', 'label': 'Douglas, Colorado' },
{ 'value': 'eagleco', 'label': 'Eagle, Colorado' },
{ 'value': 'elpasoco', 'label': 'El Paso, Colorado' },
{ 'value': 'elbertco', 'label': 'Elbert, Colorado' },
{ 'value': 'fremontco', 'label': 'Fremont, Colorado' },
{ 'value': 'garfieldco', 'label': 'Garfield, Colorado' },
{ 'value': 'gilpinco', 'label': 'Gilpin, Colorado' },
{ 'value': 'grandco', 'label': 'Grand, Colorado' },
{ 'value': 'gunnisonco', 'label': 'Gunnison, Colorado' },
{ 'value': 'hinsdaleco', 'label': 'Hinsdale, Colorado' },
{ 'value': 'huerfanoco', 'label': 'Huerfano, Colorado' },
{ 'value': 'jacksonco', 'label': 'Jackson, Colorado' },
{ 'value': 'jeffersonco', 'label': 'Jefferson, Colorado' },
{ 'value': 'kiowaco', 'label': 'Kiowa, Colorado' },
{ 'value': 'kitcarsonco', 'label': 'Kit Carson, Colorado' },
{ 'value': 'laplataco', 'label': 'La Plata, Colorado' },
{ 'value': 'lakeco', 'label': 'Lake, Colorado' },
{ 'value': 'larimerco', 'label': 'Larimer, Colorado' },
{ 'value': 'lasanimasco', 'label': 'Las Animas, Colorado' },
{ 'value': 'lincolnco', 'label': 'Lincoln, Colorado' },
{ 'value': 'loganco', 'label': 'Logan, Colorado' },
{ 'value': 'mesaco', 'label': 'Mesa, Colorado' },
{ 'value': 'mineralco', 'label': 'Mineral, Colorado' },
{ 'value': 'moffatco', 'label': 'Moffat, Colorado' },
{ 'value': 'montezumaco', 'label': 'Montezuma, Colorado' },
{ 'value': 'montroseco', 'label': 'Montrose, Colorado' },
{ 'value': 'morganco', 'label': 'Morgan, Colorado' },
{ 'value': 'oteroco', 'label': 'Otero, Colorado' },
{ 'value': 'ourayco', 'label': 'Ouray, Colorado' },
{ 'value': 'parkco', 'label': 'Park, Colorado' },
{ 'value': 'phillipsco', 'label': 'Phillips, Colorado' },
{ 'value': 'pitkinco', 'label': 'Pitkin, Colorado' },
{ 'value': 'prowersco', 'label': 'Prowers, Colorado' },
{ 'value': 'puebloco', 'label': 'Pueblo, Colorado' },
{ 'value': 'rioblancoco', 'label': 'Rio Blanco, Colorado' },
{ 'value': 'riograndeco', 'label': 'Rio Grande, Colorado' },
{ 'value': 'routtco', 'label': 'Routt, Colorado' },
{ 'value': 'saguacheco', 'label': 'Saguache, Colorado' },
{ 'value': 'sanjuanco', 'label': 'San Juan, Colorado' },
{ 'value': 'sanmiguelco', 'label': 'San Miguel, Colorado' },
{ 'value': 'sedgwickco', 'label': 'Sedgwick, Colorado' },
{ 'value': 'summitco', 'label': 'Summit, Colorado' },
{ 'value': 'tellerco', 'label': 'Teller, Colorado' },
{ 'value': 'washingtonco', 'label': 'Washington , Colorado' },
{ 'value': 'weldco', 'label': 'Weld, Colorado' },
{ 'value': 'yumaco', 'label': 'Yuma, Colorado' },

{ 'value': 'fairfieldct', 'label': 'Fairfield, Connecticut' },
{ 'value': 'hartfordct', 'label': 'Hartford, Connecticut' },
{ 'value': 'litchfieldct', 'label': 'Litchfield, Connecticut' },
{ 'value': 'middlesexct', 'label': 'Middlesex, Connecticut' },
{ 'value': 'newhavenct', 'label': 'New Haven, Connecticut' },
{ 'value': 'newlondonct', 'label': 'New London, Connecticut' },
{ 'value': 'tollandct', 'label': 'Tolland, Connecticut' },
{ 'value': 'windhamct', 'label': 'Windham, Connecticut' },

{ 'value': 'kentde', 'label': 'Kent, Delaware' },
{ 'value': 'newcastlede', 'label': 'New Castle, Delaware' },
{ 'value': 'sussexde', 'label': 'Sussex, Delaware' },

{ 'value': 'washingtondc', 'label': 'Washington, District of Columbia' },

{ 'value': 'alachuafl', 'label': 'Alachua, Florida' },
{ 'value': 'bakerfl', 'label': 'Baker, Florida' },
{ 'value': 'bayfl', 'label': 'Bay, Florida' },
{ 'value': 'bradfordfl', 'label': 'Bradford, Florida' },
{ 'value': 'brevardfl', 'label': 'Brevard, Florida' },
{ 'value': 'browardfl', 'label': 'Broward, Florida' },
{ 'value': 'calhounfl', 'label': 'Calhoun, Florida' },
{ 'value': 'charlottefl', 'label': 'Charlotte, Florida' },
{ 'value': 'citrusfl', 'label': 'Citrus, Florida' },
{ 'value': 'clayfl', 'label': 'Clay, Florida' },
{ 'value': 'collierfl', 'label': 'Collier, Florida' },
{ 'value': 'columbiafl', 'label': 'Columbia, Florida' },
{ 'value': 'desotofl', 'label': 'DeSoto, Florida' },
{ 'value': 'dixiefl', 'label': 'Dixie, Florida' },
{ 'value': 'duvalfl', 'label': 'Duval, Florida' },
{ 'value': 'escambiafl', 'label': 'Escambia, Florida' },
{ 'value': 'flaglerfl', 'label': 'Flagler, Florida' },
{ 'value': 'franklinfl', 'label': 'Franklin, Florida' },
{ 'value': 'gadsdenfl', 'label': 'Gadsden, Florida' },
{ 'value': 'gilchristfl', 'label': 'Gilchrist, Florida' },
{ 'value': 'gladesfl', 'label': 'Glades, Florida' },
{ 'value': 'gulffl', 'label': 'Gulf, Florida' },
{ 'value': 'hamiltonfl', 'label': 'Hamilton, Florida' },
{ 'value': 'hardeefl', 'label': 'Hardee, Florida' },
{ 'value': 'hendryfl', 'label': 'Hendry, Florida' },
{ 'value': 'hernandofl', 'label': 'Hernando, Florida' },
{ 'value': 'highlandsfl', 'label': 'Highlands, Florida' },
{ 'value': 'hillsboroughfl', 'label': 'Hillsborough, Florida' },
{ 'value': 'holmesfl', 'label': 'Holmes, Florida' },
{ 'value': 'indianriverfl', 'label': 'Indian River, Florida' },
{ 'value': 'jacksonfl', 'label': 'Jackson, Florida' },
{ 'value': 'jeffersonfl', 'label': 'Jefferson, Florida' },
{ 'value': 'lafayettefl', 'label': 'Lafayette, Florida' },
{ 'value': 'lakefl', 'label': 'Lake, Florida' },
{ 'value': 'leefl', 'label': 'Lee, Florida' },
{ 'value': 'leonfl', 'label': 'Leon, Florida' },
{ 'value': 'levyfl', 'label': 'Levy, Florida' },
{ 'value': 'libertyfl', 'label': 'Liberty, Florida' },
{ 'value': 'madisonfl', 'label': 'Madison, Florida' },
{ 'value': 'manateefl', 'label': 'Manatee, Florida' },
{ 'value': 'marionfl', 'label': 'Marion, Florida' },
{ 'value': 'martinfl', 'label': 'Martin, Florida' },
{ 'value': 'miamidadefl', 'label': 'Miami-Dade, Florida' },
{ 'value': 'monroefl', 'label': 'Monroe, Florida' },
{ 'value': 'nassaufl', 'label': 'Nassau, Florida' },
{ 'value': 'okaloosafl', 'label': 'Okaloosa, Florida' },
{ 'value': 'okeechobeefl', 'label': 'Okeechobee, Florida' },
{ 'value': 'orangefl', 'label': 'Orange, Florida' },
{ 'value': 'osceolafl', 'label': 'Osceola, Florida' },
{ 'value': 'palmbeachfl', 'label': 'Palm Beach, Florida' },
{ 'value': 'pascofl', 'label': 'Pasco, Florida' },
{ 'value': 'pinellasfl', 'label': 'Pinellas, Florida' },
{ 'value': 'polkfl', 'label': 'Polk, Florida' },
{ 'value': 'putnamfl', 'label': 'Putnam, Florida' },
{ 'value': 'santarosafl', 'label': 'Santa Rosa, Florida' },
{ 'value': 'sarasotafl', 'label': 'Sarasota, Florida' },
{ 'value': 'seminolefl', 'label': 'Seminole, Florida' },
{ 'value': 'stjohnsfl', 'label': 'St. Johns, Florida' },
{ 'value': 'stluciefl', 'label': 'St. Lucie, Florida' },
{ 'value': 'sumterfl', 'label': 'Sumter, Florida' },
{ 'value': 'suwanneefl', 'label': 'Suwannee, Florida' },
{ 'value': 'taylorfl', 'label': 'Taylor, Florida' },
{ 'value': 'unionfl', 'label': 'Union, Florida' },
{ 'value': 'volusiafl', 'label': 'Volusia, Florida' },
{ 'value': 'wakullafl', 'label': 'Wakulla, Florida' },
{ 'value': 'waltonfl', 'label': 'Walton, Florida' },
{ 'value': 'washingtonfl', 'label': 'Washington , Florida' },

{ 'value': 'applingga', 'label': 'Appling, Georgia' },
{ 'value': 'atkinsonga', 'label': 'Atkinson, Georgia' },
{ 'value': 'baconga', 'label': 'Bacon, Georgia' },
{ 'value': 'bakerga', 'label': 'Baker, Georgia' },
{ 'value': 'baldwinga', 'label': 'Baldwin, Georgia' },
{ 'value': 'banksga', 'label': 'Banks, Georgia' },
{ 'value': 'barrowga', 'label': 'Barrow, Georgia' },
{ 'value': 'bartowga', 'label': 'Bartow, Georgia' },
{ 'value': 'benhillga', 'label': 'Ben Hill, Georgia' },
{ 'value': 'berrienga', 'label': 'Berrien, Georgia' },
{ 'value': 'bibbga', 'label': 'Bibb, Georgia' },
{ 'value': 'bleckleyga', 'label': 'Bleckley, Georgia' },
{ 'value': 'brantleyga', 'label': 'Brantley, Georgia' },
{ 'value': 'brooksga', 'label': 'Brooks, Georgia' },
{ 'value': 'bryanga', 'label': 'Bryan, Georgia' },
{ 'value': 'bullochga', 'label': 'Bulloch, Georgia' },
{ 'value': 'burkega', 'label': 'Burke, Georgia' },
{ 'value': 'buttsga', 'label': 'Butts, Georgia' },
{ 'value': 'calhounga', 'label': 'Calhoun, Georgia' },
{ 'value': 'camdenga', 'label': 'Camden, Georgia' },
{ 'value': 'candlerga', 'label': 'Candler, Georgia' },
{ 'value': 'carrollga', 'label': 'Carroll, Georgia' },
{ 'value': 'catoosaga', 'label': 'Catoosa, Georgia' },
{ 'value': 'charltonga', 'label': 'Charlton, Georgia' },
{ 'value': 'chathamga', 'label': 'Chatham, Georgia' },
{ 'value': 'chattahoocheega', 'label': 'Chattahoochee, Georgia' },
{ 'value': 'chattoogaga', 'label': 'Chattooga, Georgia' },
{ 'value': 'cherokeega', 'label': 'Cherokee, Georgia' },
{ 'value': 'clarkega', 'label': 'Clarke, Georgia' },
{ 'value': 'clayga', 'label': 'Clay, Georgia' },
{ 'value': 'claytonga', 'label': 'Clayton, Georgia' },
{ 'value': 'clinchga', 'label': 'Clinch, Georgia' },
{ 'value': 'cobbga', 'label': 'Cobb, Georgia' },
{ 'value': 'coffeega', 'label': 'Coffee, Georgia' },
{ 'value': 'colquittga', 'label': 'Colquitt, Georgia' },
{ 'value': 'columbiaga', 'label': 'Columbia, Georgia' },
{ 'value': 'cookga', 'label': 'Cook, Georgia' },
{ 'value': 'cowetaga', 'label': 'Coweta, Georgia' },
{ 'value': 'crawfordga', 'label': 'Crawford, Georgia' },
{ 'value': 'crispga', 'label': 'Crisp, Georgia' },
{ 'value': 'dadega', 'label': 'Dade, Georgia' },
{ 'value': 'dawsonga', 'label': 'Dawson, Georgia' },
{ 'value': 'decaturga', 'label': 'Decatur, Georgia' },
{ 'value': 'dekalbga', 'label': 'DeKalb, Georgia' },
{ 'value': 'dodgega', 'label': 'Dodge, Georgia' },
{ 'value': 'doolyga', 'label': 'Dooly, Georgia' },
{ 'value': 'doughertyga', 'label': 'Dougherty, Georgia' },
{ 'value': 'douglasga', 'label': 'Douglas, Georgia' },
{ 'value': 'earlyga', 'label': 'Early, Georgia' },
{ 'value': 'echolsga', 'label': 'Echols, Georgia' },
{ 'value': 'effinghamga', 'label': 'Effingham, Georgia' },
{ 'value': 'elbertga', 'label': 'Elbert, Georgia' },
{ 'value': 'emanuelga', 'label': 'Emanuel, Georgia' },
{ 'value': 'evansga', 'label': 'Evans, Georgia' },
{ 'value': 'fanninga', 'label': 'Fannin, Georgia' },
{ 'value': 'fayettega', 'label': 'Fayette, Georgia' },
{ 'value': 'floydga', 'label': 'Floyd, Georgia' },
{ 'value': 'forsythga', 'label': 'Forsyth, Georgia' },
{ 'value': 'franklinga', 'label': 'Franklin, Georgia' },
{ 'value': 'fultonga', 'label': 'Fulton, Georgia' },
{ 'value': 'gilmerga', 'label': 'Gilmer, Georgia' },
{ 'value': 'glascockga', 'label': 'Glascock, Georgia' },
{ 'value': 'glynnga', 'label': 'Glynn, Georgia' },
{ 'value': 'gordonga', 'label': 'Gordon, Georgia' },
{ 'value': 'gradyga', 'label': 'Grady, Georgia' },
{ 'value': 'greenega', 'label': 'Greene, Georgia' },
{ 'value': 'gwinnettga', 'label': 'Gwinnett, Georgia' },
{ 'value': 'habershamga', 'label': 'Habersham, Georgia' },
{ 'value': 'hallga', 'label': 'Hall, Georgia' },
{ 'value': 'hancockga', 'label': 'Hancock, Georgia' },
{ 'value': 'haralsonga', 'label': 'Haralson, Georgia' },
{ 'value': 'harrisga', 'label': 'Harris, Georgia' },
{ 'value': 'hartga', 'label': 'Hart, Georgia' },
{ 'value': 'heardga', 'label': 'Heard, Georgia' },
{ 'value': 'henryga', 'label': 'Henry, Georgia' },
{ 'value': 'houstonga', 'label': 'Houston, Georgia' },
{ 'value': 'irwinga', 'label': 'Irwin, Georgia' },
{ 'value': 'jacksonga', 'label': 'Jackson, Georgia' },
{ 'value': 'jasperga', 'label': 'Jasper, Georgia' },
{ 'value': 'jeffdavisga', 'label': 'Jeff Davis, Georgia' },
{ 'value': 'jeffersonga', 'label': 'Jefferson, Georgia' },
{ 'value': 'jenkinsga', 'label': 'Jenkins, Georgia' },
{ 'value': 'johnsonga', 'label': 'Johnson, Georgia' },
{ 'value': 'jonesga', 'label': 'Jones, Georgia' },
{ 'value': 'lamarga', 'label': 'Lamar, Georgia' },
{ 'value': 'lanierga', 'label': 'Lanier, Georgia' },
{ 'value': 'laurensga', 'label': 'Laurens, Georgia' },
{ 'value': 'leega', 'label': 'Lee, Georgia' },
{ 'value': 'libertyga', 'label': 'Liberty, Georgia' },
{ 'value': 'lincolnga', 'label': 'Lincoln, Georgia' },
{ 'value': 'longga', 'label': 'Long, Georgia' },
{ 'value': 'lowndesga', 'label': 'Lowndes, Georgia' },
{ 'value': 'lumpkinga', 'label': 'Lumpkin, Georgia' },
{ 'value': 'maconga', 'label': 'Macon, Georgia' },
{ 'value': 'madisonga', 'label': 'Madison, Georgia' },
{ 'value': 'marionga', 'label': 'Marion, Georgia' },
{ 'value': 'mcduffiega', 'label': 'McDuffie, Georgia' },
{ 'value': 'mcintoshga', 'label': 'McIntosh, Georgia' },
{ 'value': 'meriwetherga', 'label': 'Meriwether, Georgia' },
{ 'value': 'millerga', 'label': 'Miller, Georgia' },
{ 'value': 'mitchellga', 'label': 'Mitchell, Georgia' },
{ 'value': 'monroega', 'label': 'Monroe, Georgia' },
{ 'value': 'montgomeryga', 'label': 'Montgomery, Georgia' },
{ 'value': 'morganga', 'label': 'Morgan, Georgia' },
{ 'value': 'murrayga', 'label': 'Murray, Georgia' },
{ 'value': 'muscogeega', 'label': 'Muscogee, Georgia' },
{ 'value': 'newtonga', 'label': 'Newton, Georgia' },
{ 'value': 'oconeega', 'label': 'Oconee, Georgia' },
{ 'value': 'oglethorpega', 'label': 'Oglethorpe, Georgia' },
{ 'value': 'pauldingga', 'label': 'Paulding, Georgia' },
{ 'value': 'peachga', 'label': 'Peach, Georgia' },
{ 'value': 'pickensga', 'label': 'Pickens, Georgia' },
{ 'value': 'piercega', 'label': 'Pierce, Georgia' },
{ 'value': 'pikega', 'label': 'Pike, Georgia' },
{ 'value': 'polkga', 'label': 'Polk, Georgia' },
{ 'value': 'pulaskiga', 'label': 'Pulaski, Georgia' },
{ 'value': 'putnamga', 'label': 'Putnam, Georgia' },
{ 'value': 'quitmanga', 'label': 'Quitman, Georgia' },
{ 'value': 'rabunga', 'label': 'Rabun, Georgia' },
{ 'value': 'randolphga', 'label': 'Randolph, Georgia' },
{ 'value': 'richmondga', 'label': 'Richmond, Georgia' },
{ 'value': 'rockdalega', 'label': 'Rockdale, Georgia' },
{ 'value': 'schleyga', 'label': 'Schley, Georgia' },
{ 'value': 'screvenga', 'label': 'Screven, Georgia' },
{ 'value': 'seminolega', 'label': 'Seminole, Georgia' },
{ 'value': 'spaldingga', 'label': 'Spalding, Georgia' },
{ 'value': 'stephensga', 'label': 'Stephens, Georgia' },
{ 'value': 'stewartga', 'label': 'Stewart, Georgia' },
{ 'value': 'sumterga', 'label': 'Sumter, Georgia' },
{ 'value': 'talbotga', 'label': 'Talbot, Georgia' },
{ 'value': 'taliaferroga', 'label': 'Taliaferro, Georgia' },
{ 'value': 'tattnallga', 'label': 'Tattnall, Georgia' },
{ 'value': 'taylorga', 'label': 'Taylor, Georgia' },
{ 'value': 'telfairga', 'label': 'Telfair, Georgia' },
{ 'value': 'terrellga', 'label': 'Terrell, Georgia' },
{ 'value': 'thomasga', 'label': 'Thomas, Georgia' },
{ 'value': 'tiftga', 'label': 'Tift, Georgia' },
{ 'value': 'toombsga', 'label': 'Toombs, Georgia' },
{ 'value': 'townsga', 'label': 'Towns, Georgia' },
{ 'value': 'treutlenga', 'label': 'Treutlen, Georgia' },
{ 'value': 'troupga', 'label': 'Troup, Georgia' },
{ 'value': 'turnerga', 'label': 'Turner, Georgia' },
{ 'value': 'twiggsga', 'label': 'Twiggs, Georgia' },
{ 'value': 'unionga', 'label': 'Union, Georgia' },
{ 'value': 'upsonga', 'label': 'Upson, Georgia' },
{ 'value': 'walkerga', 'label': 'Walker, Georgia' },
{ 'value': 'waltonga', 'label': 'Walton, Georgia' },
{ 'value': 'warega', 'label': 'Ware, Georgia' },
{ 'value': 'warrenga', 'label': 'Warren, Georgia' },
{ 'value': 'washingtonga', 'label': 'Washington , Georgia' },
{ 'value': 'waynega', 'label': 'Wayne, Georgia' },
{ 'value': 'websterga', 'label': 'Webster, Georgia' },
{ 'value': 'wheelerga', 'label': 'Wheeler, Georgia' },
{ 'value': 'whitega', 'label': 'White, Georgia' },
{ 'value': 'whitfieldga', 'label': 'Whitfield, Georgia' },
{ 'value': 'wilcoxga', 'label': 'Wilcox, Georgia' },
{ 'value': 'wilkesga', 'label': 'Wilkes, Georgia' },
{ 'value': 'wilkinsonga', 'label': 'Wilkinson, Georgia' },
{ 'value': 'worthga', 'label': 'Worth, Georgia' },

{ 'value': 'hawaiihi', 'label': 'Hawaii , Hawaii' },
{ 'value': 'honoluluhi', 'label': 'Honolulu, Hawaii' },
{ 'value': 'kalawaohi', 'label': 'Kalawao, Hawaii' },
{ 'value': 'kauaihi', 'label': 'Kauai, Hawaii' },
{ 'value': 'mauihi', 'label': 'Maui, Hawaii' },

{ 'value': 'adaid', 'label': 'Ada, Idaho' },
{ 'value': 'adamsid', 'label': 'Adams, Idaho' },
{ 'value': 'bannockid', 'label': 'Bannock, Idaho' },
{ 'value': 'bearlakeid', 'label': 'Bear Lake, Idaho' },
{ 'value': 'benewahid', 'label': 'Benewah, Idaho' },
{ 'value': 'binghamid', 'label': 'Bingham, Idaho' },
{ 'value': 'blaineid', 'label': 'Blaine, Idaho' },
{ 'value': 'boiseid', 'label': 'Boise, Idaho' },
{ 'value': 'bonnerid', 'label': 'Bonner, Idaho' },
{ 'value': 'bonnevilleid', 'label': 'Bonneville, Idaho' },
{ 'value': 'boundaryid', 'label': 'Boundary, Idaho' },
{ 'value': 'butteid', 'label': 'Butte, Idaho' },
{ 'value': 'camasid', 'label': 'Camas, Idaho' },
{ 'value': 'canyonid', 'label': 'Canyon, Idaho' },
{ 'value': 'caribouid', 'label': 'Caribou, Idaho' },
{ 'value': 'cassiaid', 'label': 'Cassia, Idaho' },
{ 'value': 'clarkid', 'label': 'Clark, Idaho' },
{ 'value': 'clearwaterid', 'label': 'Clearwater, Idaho' },
{ 'value': 'custerid', 'label': 'Custer, Idaho' },
{ 'value': 'elmoreid', 'label': 'Elmore, Idaho' },
{ 'value': 'franklinid', 'label': 'Franklin, Idaho' },
{ 'value': 'fremontid', 'label': 'Fremont, Idaho' },
{ 'value': 'gemid', 'label': 'Gem, Idaho' },
{ 'value': 'goodingid', 'label': 'Gooding, Idaho' },
{ 'value': 'idahoid', 'label': 'Idaho , Idaho' },
{ 'value': 'jeffersonid', 'label': 'Jefferson, Idaho' },
{ 'value': 'jeromeid', 'label': 'Jerome, Idaho' },
{ 'value': 'kootenaiid', 'label': 'Kootenai, Idaho' },
{ 'value': 'latahid', 'label': 'Latah, Idaho' },
{ 'value': 'lemhiid', 'label': 'Lemhi, Idaho' },
{ 'value': 'lewisid', 'label': 'Lewis, Idaho' },
{ 'value': 'lincolnid', 'label': 'Lincoln, Idaho' },
{ 'value': 'madisonid', 'label': 'Madison, Idaho' },
{ 'value': 'minidokaid', 'label': 'Minidoka, Idaho' },
{ 'value': 'nezperceid', 'label': 'Nez Perce, Idaho' },
{ 'value': 'oneidaid', 'label': 'Oneida, Idaho' },
{ 'value': 'owyheeid', 'label': 'Owyhee, Idaho' },
{ 'value': 'payetteid', 'label': 'Payette, Idaho' },
{ 'value': 'powerid', 'label': 'Power, Idaho' },
{ 'value': 'shoshoneid', 'label': 'Shoshone, Idaho' },
{ 'value': 'tetonid', 'label': 'Teton, Idaho' },
{ 'value': 'twinfallsid', 'label': 'Twin Falls, Idaho' },
{ 'value': 'valleyid', 'label': 'Valley, Idaho' },
{ 'value': 'washingtonid', 'label': 'Washington , Idaho' },

];